### PR TITLE
Update offering-HIPAA-HITECH.md

### PR DESCRIPTION
**Pull request by msbemba**
Made changes from o365 to M365.

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/3083

**Comment by robmazz** [comment]
Rejecting - needs to be cleared and synced with supporting PDF download. Currently in discussions about updates and reformatting of this download.

**Comment by msbemba** [comment]
Thank you for the update @robmazz .I'll explain this to the user as well.

**Pull request closed without merging**
