### PR TITLE
Update cancel-your-subscription.md

### PR DESCRIPTION
**Pull request by msbemba**
adjusted moniker range to avoid repeated instrcutions

### CODE REVIEW

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/5935

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@cmcatee-MSFT Please merge this PR. Thanks

**Comment by yogkumgit** [comment]
@cmcatee-MSFT Gentle reminder

**Comment by cmcatee-MSFT** [comment]
Markdown problem already fixed. No change needed.

**Pull request closed without merging**
