### PR TITLE
Update web-protection-overview.md

### PR DESCRIPTION
**Pull request by msbemba**
Updated Custom policy to Customblocklist

### CODE REVIEW

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/6859

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@Dansimp Please merge this PR. Thanks

**Review by denisebmsft — APPROVED** [review]
thank you @msbemba

**Pull request merged**
