### PR TITLE
[Hold til mid-Dec] Update create-safe-sender-lists-in-office-365.md

### PR DESCRIPTION
**Pull request by andypunt**
Updating doc for secure by default.

### CODE REVIEW

**Review by chrisda — APPROVED** [review]
I made some linguistic updates.

**Comment by chrisda** [comment]
@andypunt, is this OK to publish (the feature is in place)?

**Comment by andypunt** [comment]
Can we commit this in mid-DEC?

**Comment by chrisda** [comment]
@andypunt, sure. No problem.

**Pull request merged**
