### PR TITLE
Update information-barriers.md

### PR DESCRIPTION
**Pull request by msbemba**
Updated the license requirement as Office365 A3 and A1 need Office 365 Advanced Compliance add-on

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/7943

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@robmazz Please merge this PR. Thanks.

**Comment by yogkumgit** [comment]
@robmazz Gentle reminder.

**Comment by tiburd** [comment]
Closing per author. Documentation is planned to be updated.

**Pull request closed without merging**
