### PR TITLE
Update password-policy-recommendations.md

### PR DESCRIPTION
**Pull request by msbemba**
Updated the minimum requirement to 8 as MS recommends 8 character limit as Password length requirements (greater than about 10 characters) can result in user behavior that is predictable and undesirable.

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/8948

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@kwekuako Please merge this PR. Thanks

**Comment by yogkumgit** [comment]
@kwekuako Gentle reminder. Thanks

**Pull request merged**
