### PR TITLE
Update intro-to-info-mgmt-policies.md

### PR DESCRIPTION
**Pull request by kyracatwork**
- Adding a callout related to the impact of changing the content type of an item on the policy
- Removed a weird fully-linked duplicate paragraph from the bottom of the article

### CODE REVIEW

**Comment by kyracatwork** [comment]
**Important - this PR **MUST** be reviewed/approved by Compliance team. @MSFTTracyP FYI, we do not want this to publish until manager review is complete, I can provide updates on this activity.

**Comment by cabailey** [comment]
Adding "Do not merge" label for safety.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by kyracatwork** [comment]
Tagging @cabailey & @MSFTTracyP - I got the approval from my manager on the Compliance team. This is approved to be published!

**Comment by cabailey** [comment]
Fixed merge conflicts with 18970 on private repo - closing

**Pull request closed without merging**
