### PR TITLE
Fixing a few spelling errors

### PR DESCRIPTION
**Pull request by modery**
Correcting SharePoint and OneDrive spellings - only minor changes done

### CODE REVIEW

**Comment by denisebmsft** [comment]
Hi @chrfox! Lots of files updated in this pull request. They might not all be yours, but at least some are. Please review, and if you're comfortable merging, please do that. Thank you!

**Comment by yogkumgit** [comment]
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

**Review by JohanFreelancer9 — COMMENTED** [review]
Copy review - Changes look good. But should all instances of "SharePoint Online" not be changed to just "SharePoint" and "OneDrive for Business" to just "OneDrive"? If not, all instances of "OneDrive For Business" should be changed to "OneDrive for Business" lower case "f". Thank you.

**Comment by yogkumgit** [comment]
@modery Please review the suggested changes and update the PR. Thanks.

**Comment by modery** [comment]
@yogkumgit  all good, PR updated

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@chrfox Please merge this PR. Thanks

**Comment by yogkumgit** [comment]
@tiburd Please merge this PR. Thanks

**Review by tiburd — APPROVED** [review]

**Pull request merged**
