### PR TITLE
Update DLP-create-test-tune-PowerShell.png

### PR DESCRIPTION
**Pull request by msbemba**
Changed the cmdlet parameter used from 

Get-DlpCompliancePolicy "Testing - Australia PII" | Select Distributionstatus

to

Get-DlpCompliancePolicy "Testing - Australia PII" -DistributionDetail| Select Distributionstatus

As the  policies which have been enabled with status "success" for a long time, but when using the former they are still showing status "pending". The actual DistributionStatus is only presented when adding -Distributiondetail.

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/7129

**Review by JohanFreelancer9 — APPROVED** [review]
No copy to review.

**Comment by yogkumgit** [comment]
@chrfox Please merge this PR. Thanks.

**Comment by chrfox** [comment]
Screen shot is in wrong dimensions and format and can't be used. Please fill out ADO work item request [ here](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Foffice.visualstudio.com%2FMAX%2F_workitems%2Fcreate%2FTask%3FtemplateId%3D2b3ec282-1f91-44a6-a77f-776c3fa70966%26ownerId%3D17bba195-cfcb-45a3-885b-71e438da299b&data=04%7C01%7CLaura.Williams%40microsoft.com%7C990aada841854d71541b08d97e0f14f6%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637679425505695632%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=JoNv1p%2Fir8tYNLffhP%2FBjTduYr%2BCMjd7GRxT3E%2BlvxE%3D&reserved=0)

**Pull request closed without merging**
