### PR TITLE
Update structured-freeform-setup.md

### PR DESCRIPTION
**Pull request by charv3n**
Adding information on how to enable the "AI Builder for Project Cortex" in the default environment.

### CODE REVIEW

**Comment by charv3n** [comment]
@microsoft-github-policy-service agree

**Comment by charv3n** [comment]
@microsoft-github-policy-service agree

**Comment by charv3n** [comment]
#sign-off

**Comment by charv3n** [comment]
#sign-off

**Comment by chuckedmonson** [comment]
In review.

**Pull request closed without merging**
