### PR TITLE
Add external dependencies for mdatp package

### PR DESCRIPTION
**Pull request by agarwalneetu**

### CODE REVIEW

**Comment by siosulli** [comment]
Hi @agarwalneetu 

Thank you so much for submitting this update! I have just a few suggested updates that it would be great to get your feedback on: 

**Microsoft Defender for Endpoint package external package dependencies **

The following external package dependencies exist for the **mdatp** package:
- The mdatp RPM package requires "glibc >= 2.17", "audit", "policycoreutils", "selinux-policy-targeted", "mde-netfilter" 
- For RHEL6 the mdatp RPM package requires "audit", "policycoreutils", "libselinux", "mde-netfilter"
- For DEBIAN the mdatp package requires "libc6 >= 2.23", "uuid-runtime", "auditd", "mde-netfilter" 

The mde-netfilter package also has the following package dependencies:
- mde-netfilter_DEBIAN_PACKAGE_DEPENDS on "libnetfilter-queue1",  "libglib2.0-0" 
- mde-netfilter_RPM_PACKAGE_DEPENDS on "libmnl", "libnfnetlink", "libnetfilter_queue", "glib2"

If the Microsoft Defender for Endpoint installation fails due to missing dependencies errors, you can manually download the pre-requisite dependencies. 

I just have one question as well! For  "mde-netfilter_DEBIAN_PACKAGE_DEPENDS on "libnetfilter-queue1",  "libglib2.0-0"" is that a command a user runs or is just stating the dependency? if it's the latter we can update to:

- for DEBIAN the mde-netfilter pacakage requires "libnetfilter-queue1",  "libglib2.0-0" 

Thanks!
Sinead

**Comment by agarwalneetu** [comment]
Hi  @siosulli , yes it's not a command but states the dependencies, it's a good suggestion, I'll update it accordingly.

**Comment by siosulli** [comment]
Thanks @agarwalneetu!

Did you review the other suggestions? we need to at a minimum spell out Microsoft Defender for Endpoint. 

Also, should this have the ')' in it? 

for DEBIAN mdatp package requires "libc6 (>= 2.23", "uuid-runtime", "auditd", "mde-netfilter" <br />

**Comment by agarwalneetu** [comment]
Hi @siosulli, what do you mean by the minimum spell out Microsoft Defender for Endpoint?

**Pull request merged**
