### PR TITLE
Update linux-preferences.md

### PR DESCRIPTION
**Pull request by msbemba**
removed the duplicate  Configure file hash computation feature as the value was incorrect

Fixes#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/10810

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@mjcaparas Please merge this PR. Thanks

**Comment by yogkumgit** [comment]
@mjcaparas Gentle reminder.

**Comment by mjcaparas** [comment]
I'm not finding the duplicate.

**Comment by yogkumgit** [comment]
@msbemba your comment please.

**Comment by msbemba** [comment]
@mjcaparas looks like this was done via another commit-  https://github.com/MicrosoftDocs/microsoft-365-docs/commit/bb1dafc7b2f3c1bcc8605c9dd591ef6cd2794cae

No action is needed now.

@yogkumgit  We can close the issue as the document is up to date.

Thanks
Sri

**Pull request closed without merging**
