### PR TITLE
Update assign-licenses-to-user-accounts-with-microsoft-365-powershell.md

### PR DESCRIPTION
**Pull request by msbemba**
Corrected the copy license assignment cmdlet

Per issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/9686

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@yogkumgit Validation has been passed

**Comment by yogkumgit** [comment]
@kelleyvice-msft Please merge this PR. Thanks

**Pull request merged**
