### PR TITLE
Update configure-extension-file-exclusions-microsoft-defender-antivir…

### PR DESCRIPTION
**Pull request by msbemba**
…us.md

Updated path examples for variables for %userprofile%

### CODE REVIEW

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/6415

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@denisebmsft Please merge this PR. Thanks

**Review by denisebmsft — APPROVED** [review]
Thank you @msbemba @yogkumgit @JohanFreelancer9

**Pull request merged**
