### PR TITLE
Update encryption.md

### PR DESCRIPTION
**Pull request by msbemba**
Added Encryption Risks and protection to the document as related topics

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/3160

**Comment by msbemba** [comment]
@KCCross Can this document be added to the Navigation section as well.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@KCCross Please merge this PR. Thanks.

**Pull request merged**
