### PR TITLE
Add section on configuring photo update settings

### PR DESCRIPTION
**Pull request by shivanioslo**
Submitted via Learn Editor.

### CODE REVIEW

**Comment by chrisda** [comment]
@shivanioslo, line 235 is missing the link (it had just http:// by itself, which I removed, because it was causing build errors.

**Comment by shivanioslo** [comment]
> @shivanioslo, line 235 is missing the link (it had just http:// by itself, which I removed, because it was causing build errors. 
Yes, @chrisda that would be the link to the page that is being worked on in this PR: https://github.com/microsoftgraph/microsoft-graph-docs/pull/24203

Once that one is approved, can we add the link?

Do you have any other comments or requested changes from me?

**Comment by cmcatee-MSFT** [comment]
@shivanioslo I can't open the link for PR 24203. Please update the file to include the link for "Manage user profile photo settings in Microsoft 365 using Microsoft Graph".

**Comment by cmcatee-MSFT** [comment]
@shivanioslo Please submit a new PR to add the missing URL.

**Pull request merged**
