### PR TITLE
Update attack-surface-reduction-rules-deployment-operationalize.md

### PR DESCRIPTION
**Pull request by msbemba**
Added Plain text (Kusto) to the document as users can copy paste

Fixes#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/10865

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@jweston-1 Please merge this PR. Thanks

**Comment by denisebmsft** [comment]
@yogkumgit Brit will review. I don't know if he sees comments here.

**Review by bweston-8 — APPROVED** [review]
Good revision. Approved.

**Pull request merged**
