### PR TITLE
Update InfoBarriers-PowerShellGenerator.xlsx

### PR DESCRIPTION
**Pull request by msbemba**
Fixed a broken link in the excel file.

### CODE REVIEW

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/2524

**Comment by yogkumgit** [comment]
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

**Review by JohanFreelancer9 — APPROVED** [review]
No copy to edit.

**Comment by yogkumgit** [comment]
@chrfox Please merge this PR. Thanks

**Comment by chrfox** [comment]
@msbemba I have no visibility into what was changed or even what topic this is offered from.  please provide more detail

**Comment by msbemba** [comment]
The excel file that is available in the document (in the TiP section) had a broken link for "Attributes for information barrier policies".. This PR fixes a broken link in the excel file.

Thanks
Sri

**Pull request merged**
