### PR TITLE
Update microsoft-defender-endpoint-mac.md

### PR DESCRIPTION
**Pull request by msbemba**
Added - Windows 10 Enterprise E5
- Microsoft Defender for Endpoint as Microsoft Defender for Endpoint for Mac is included -  Reference https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/minimum-requirements?view=o365-worldwide

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/4605

**Comment by AaronDinnage** [comment]
This is not showing up correctly on the specific Mac licensing requirements on the Mac-specific page here: https://docs.microsoft.com/microsoft-365/security/defender-endpoint/microsoft-defender-endpoint-mac?view=o365-worldwide#licensing-requirements

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@Dansimp Please merge this PR. Thanks.

**Comment by yogkumgit** [comment]
@Dansimp Gentle reminder, please merge this PR. Thanks

**Comment by AaronDinnage** [comment]
Confirmed live. Thank you.

**Pull request merged**
