### PR TITLE
Update scheduler-setup.md

### PR DESCRIPTION
**Pull request by msbemba**
Fixed powershell examples

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/5310

**Comment by JoanneHendrickson** [comment]
reviewing.

**Review by JohanFreelancer9 — APPROVED** [review]

**Review by shivbijlani — APPROVED** [review]
Looks good to me

**Comment by yogkumgit** [comment]
@JoanneHendrickson Please merge this PR. Thanks

**Comment by yogkumgit** [comment]
@JoanneHendrickson Gentle reminder.

**Comment by JoanneHendrickson** [comment]
updated with examples from PM.

**Pull request merged**
