### PR TITLE
Update customer-key-set-up.md

### PR DESCRIPTION
**Pull request by msbemba**
Corrected the syntax for Register-AzProviderFeature

### CODE REVIEW

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/1434

**Comment by msbemba** [comment]
@JohanFreelancer9  Please copy review

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@KCCross Please merge this PR. Thanks

**Comment by brdesai** [comment]
@msbemba I don't see the external site reflect this change yet. Who is going to merge the change to Master and publish the same? Thanks.

**Comment by msbemba** [comment]
@brdesai We are still waiting for the authour to merge the pull request. Once merged, It could take 48 hours to show up in the live document.

Thanks
Sri

**Pull request merged**
