### PR TITLE
Fixes launch script path in test base buildpackage.md

### PR DESCRIPTION
**Pull request by RayYuePro**
Fixes launch script path in test base buildpackage.md

### CODE REVIEW

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@Tinacyt Please merge this PR. thanks

**Comment by Tinacyt** [comment]
@RayYuePro please merge

**Comment by RayYuePro** [comment]
@Tinacyt updated latest code.

**Comment by RayYuePro** [comment]
@Tinacyt I don't have permission to merge, please help to merge, thanks.

**Comment by yogkumgit** [comment]
@Tinacyt Please merge this PR. If you cannot merge then please review and signoff. Thanks
cc: @tiburd

**Comment by Tinacyt** [comment]
> @Tinacyt Please merge this PR. If you cannot merge then please review and signoff. Thanks cc: @tiburd

Hi Yogesh, I don not see the 'signoff' label available so I've added they 'Merge large pull request' instead. hope that helps.

**Comment by RayYuePro** [comment]
@Tinacyt  goto https://github.com/MicrosoftDocs/microsoft-365-docs/pull/12319/files , and click "Review changes" and input comments like 'LGTM.' and click 'Approve', then click "submit review".

**Review by Tinacyt — APPROVED** [review]

**Comment by yogkumgit** [comment]
@tiburd Please merge this PR. Thanks

**Pull request merged**
