### PR TITLE
Update exclude-devices.md

### PR DESCRIPTION
**Pull request by msbemba**
Added a line that EDR will be disabled when excluded

Fixes#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/11424

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by yogkumgit** [comment]
@JohanFreelancer9

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@siosulli Please merge this PR. Thanks

**Comment by siosulli** [comment]
Hi @msbemba 

I actually just checked with PM and this is not the case, the devices is exclude from TVM but does not disable EDR.

Thanks,
Sinead

**Comment by siosulli** [comment]
Hi @msbemba 

I actually just checked with PM and this is not the case, the devices is exclude from TVM but does not disable EDR.

Thanks,
Sinead

**Comment by siosulli** [comment]
Hi @msbemba 

I actually just checked with PM and this is not the case, the devices is exclude from TVM but does not disable EDR.

Thanks,
Sinead

**Comment by siosulli** [comment]
Hi @msbemba 

I actually just checked with PM and this is not the case, the devices is exclude from TVM but does not disable EDR.

Thanks,
Sinead

**Comment by msbemba** [comment]
Thank you for confirming @siosulli

**Pull request closed without merging**
