### PR TITLE
Update secure-email-recommended-policies.md

### PR DESCRIPTION
**Pull request by martincoetzer**
Fixing table rendering
#sign-off @barlanmsft

### CODE REVIEW

**Comment by barlanmsft** [comment]
@JoeDavies-MSFT please merge

**Comment by JoeDavies-MSFT** [comment]
Looks like I don't have write access and am unable to merge this PR. Contact Celeste de Guzman.

**Comment by martincoetzer** [comment]
Can you help us please? @CelesteDG

**Comment by brianlic-msft** [comment]
Merged. This should go live within the hour.

**Pull request merged**
