### PR TITLE
Update gdpr-arc-Office365.md

### PR DESCRIPTION
**Pull request by msbemba**
Removed duplicate row 7.2.3

### CODE REVIEW

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/3393

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@robmazz Please merge this PR. Thanks

**Comment by robmazz** [comment]
@msbemba - closing, all GDPR topic updates need to be approved by CELA team. I will advise of this issue and merge as part of current GDPR review work.

**Pull request closed without merging**
