### PR TITLE
Update modern-desktop-deployment-and-management-lab.md

### PR DESCRIPTION
**Pull request by msbemba**
The existing link is broken. Found another lab kit from here -https://www.microsoft.com/en-in/evalcenter/download-lab-kit

Link to lab-  https://go.microsoft.com/fwlink/p/?linkid=2194898&clcid=0x4009

Made the change accordingly.

per issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/10175

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@cdmm12 Please merge this PR. Thanks

**Comment by msbemba** [comment]
Another one with the same issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/10194

**Comment by msbemba** [comment]
The Lab environment link is fixed.

**Pull request closed without merging**
