### PR TITLE
Update access-resources.md

### PR DESCRIPTION
**Pull request by msbemba**
Made a slight change from AD auth to Ad machine auth. Azure AD sends the details of the user's on-premises domain back to the device, along with the Primary Refresh Token, however, Apps and resources that depend on Active Directory machine authentication don't work because Azure AD joined devices don't have a computer object in AD.

### CODE REVIEW

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/3769

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@Sirkkuw Please merge this PR. Thanks.

**Comment by yogkumgit** [comment]
@cmcatee-MSFT Please merge this PR. Thanks.

**Pull request merged**
