### PR TITLE
Update m365-lighthouse-sign-up.md

### PR DESCRIPTION
**Pull request by ErikMoreau**
updated purchase location to marketplace, where it lives now

### CODE REVIEW

**Comment by SKjerland** [comment]
@ErikMoreau - I'm not seeing a Marketplace option within the Microsoft 365 admin center, and I can't find any record of this change in the admin center UI. Are you perhaps talking about the Azure Marketplace? Microsoft 365 Lighthouse cannot be purchased there. You might be confusing it with Azure Lighthouse, which is a completely different product.

If you're seeing a Marketplace option in the admin center, can you please provide a screenshot showing where it is? My Microsoft 365 Business Premium test tenant is showing that Microsoft 365 Lighthouse is still under **Billing** > **Purchase services**, as shown in this screenshot:

image

The only correction I see that needs to be made to the instructions in the article is to change Step 2 from "Go to **Billing** > **Purchase Services** > **Microsoft 365 Services**" to "Go to **Billing** > **Purchase services** > **Microsoft 365**". 

Thanks for your help confirming your update.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by ErikMoreau** [comment]
Hi Shari,

Looks like we currently have 2 possibilities....
I was assisting an other partner to get started, as he got stuck at the license part, I did find both options by testing multiple tenants (ss below), the one on the right seems to be the new experience, the one on the left the previous.

Hoping the 'new' will be the view for all tenants soon. If not we'll need to add both options to the page


[A screenshot of a computer  Description automatically generated]

Hope this helps!

Have A Great Day!

Erik

**Comment by SKjerland** [comment]
@ErikMoreau - Unfortunately, I'm not seeing any screenshots from you. It may be because you responded via email instead of adding them directly in GitHub. Is it possible to try again? Thanks!

**Comment by ErikMoreau** [comment]
> 

@SKjerland here's the screenshot with the difference marked
image

**Comment by SKjerland** [comment]
@ErikMoreau - Thanks! I can see both screenshots now. I need to consult with the Lighthouse product team on this before making any changes to the article. Please stay tuned.

**Comment by SKjerland** [comment]
@ErikMoreau - I just wanted to let you know that we didn't forget about this pull request. The product team wants to do a bit more research into the different versions of the Microsoft 365 admin center that we're seeing before we update the documentation. Thanks for your patience!

**Comment by ErikMoreau** [comment]
Thanks for the update!

**Comment by SKjerland** [comment]
@ErikMoreau - Thanks for your patience while we investigated the two different experiences. The UI that shows Marketplace is an experiment that one of our Microsoft 365 Support teams launched to a select number of customers. It's not something the Microsoft 365 team is planning on rolling out to everyone. We apologize for any inconvenience this has caused in signing up for Microsoft 365 Lighthouse. Since this is not a change that's being rolled out to a broader customer base, we won't be merging your documentation changes. I'm going to go ahead and close this pull request. We very much appreciate you alerting us to this and always welcome feedback on our documentation.

**Pull request closed without merging**
