### PR TITLE
Update activate-rms-in-microsoft-365.md

### LINKED ISSUE #11673: Activate Rights Management in admin center
The title says "Activate rights management in the admin center" but it doesn't actually say how to activate them in the admin center.

Is it possible? Or is only possible to enable RM with PowerShell?

If it is indeed possible, instructions should be added on this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5d20fbb5-c482-7944-b726-63b2b3e1ddbe
* Version Independent ID: 0a98d497-e6fa-3aa3-23ba-7939f5fb7a1e
* Content: [Activate rights management in the admin center - Microsoft 365 Enterprise](https://learn.microsoft.com/en-us/microsoft-365/enterprise/activate-rms-in-microsoft-365?source=recommendations&view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/activate-rms-in-microsoft-365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/activate-rms-in-microsoft-365.md)
* Service: **microsoft-365-enterprise**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

### PR DESCRIPTION
**Pull request by msbemba**
Made changes to the title and description as it cannot be activated via Admin center

Fixes https://github.com/MicrosoftDocs/microsoft-365-docs/issues/11673

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by yogkumgit** [comment]
@JohanFreelancer9

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@KCCross Please merge this PR. Thanks

**Comment by KCCross** [comment]
Creating a work item for Samson and myself based on this PR. This is more complicated than just changing the name of the article. IRM v. RMS needs clarification as well as which admin center. Waiting for post migration.

**Pull request closed without merging**
