### PR TITLE
Update hybrid-modern-auth-overview.md

### PR DESCRIPTION
**Pull request by gabymuntean**
Customers are asking is possible to have a restrictive list of URLs/IPs needed to allow on the Outlook client side, so that HMA to work.

The resources in the Office 365 URLs and IP address ranges - Microsoft 365 Enterprise | Microsoft Docs  article are sometimes not detailed enough, so that the customer understand which URLs/IPs are required and for what exact service/operation.

### CODE REVIEW

**Comment by yogkumgit** [comment]
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

**Comment by JohanFreelancer9** [comment]
@yogkumgit - this is really a question that needs to be answered. Once it is resolved, I'll do the copy review. Thanks.

**Comment by yogkumgit** [comment]
@LauraWi Please answer this question. Thanks

**Comment by LauraWi** [comment]
Hi @gabymuntean Looks like you are Msft internal. Can you find me on email, so I can possibly connect you with the right engineering contacts.  Not merging this commit because it's an editorial comment/question.

**Pull request closed without merging**
