### PR TITLE
Update mmd-app-requirements.md

### PR DESCRIPTION
**Pull request by dannoakes**
Modifying the references to exceptions to the service plan the item in the first paragraph was contradictory to the last paragraph and has caused confusion.

### CODE REVIEW

**Comment by yogkumgit** [comment]
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

**Comment by jaimeo** [comment]
Good to go.

**Comment by dannoakes** [comment]
Thanks, do I need to take further action?

**Comment by jaimeo** [comment]
@dannoakes nope.

@denisebmsft I've approved. Will you merge or shall I?

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@jaimeo Please merge this PR. Thanks.

**Review by jaimeo — APPROVED** [review]

**Pull request merged**
