### PR TITLE
Update add-staff.md

### LINKED ISSUE #12310: out of date
Booking Calendars are now referred to as Booking Pages.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4fcbd22b-e14b-fe97-7b7f-eb672e84d382
* Version Independent ID: f9a024d7-6600-4922-02b5-2c8ceeae13ab
* Content: [Add staff to Bookings](https://learn.microsoft.com/en-us/microsoft-365/bookings/add-staff?view=o365-worldwide)
* Content Source: [microsoft-365/bookings/add-staff.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/bookings/add-staff.md)
* Service: **bookings**
* GitHub Login: @kwekuako
* Microsoft Alias: **kwekua**

### PR DESCRIPTION
**Pull request by msbemba**
Made changes to Booking page from booking calendar

Fixes https://github.com/MicrosoftDocs/microsoft-365-docs/issues/12310

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by MSUMOLL** [comment]
interestingly, the confirmation email you get when creating a new booking page still refers to it as a booking calendar. Consistency is hard.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@kwekuako Please merge this PR. Thanks

**Comment by yogkumgit** [comment]
@kwekuako Gentle reminder

**Pull request merged**
