### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by msbemba**
updated Borken link

### CODE REVIEW

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/5863

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@MicrosoftHeidi Please merge this PR. Thanks

**Comment by yogkumgit** [comment]
@MicrosoftHeidi Gentle reminder, please merge this PR. Thanks

**Comment by tiburd** [comment]
Closing this PR - on the live Microsoft Docs site, the link works as expected.

**Pull request closed without merging**
