### PR TITLE
Update security-roadmap.md

### PR DESCRIPTION
**Pull request by msbemba**
Updated URL's for Secure score

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/6042

**Review by denisebmsft — APPROVED** [review]
Thank you @msbemba

**Review by denisebmsft — APPROVED** [review]
Thank you @msbemba

**Pull request merged**
