### PR TITLE
Update create-retention-policies.md

### PR DESCRIPTION
**Pull request by msbemba**
Removed the line "Support for adding searchable properties (for example, **subject:**) is coming soon." as it is live and document  keyword-queries-and-search-conditions.md is updated with property details

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/2562

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@cabailey Please merge this PR. Thanks.

**Comment by cabailey** [comment]
#sign-off  Confirmed by engineering

**Pull request merged**
