### PR TITLE
Update allowselfservicepurchase-powershell.md

### PR DESCRIPTION
**Pull request by snickler**
Updated to add PowerShell version requirement.

### CODE REVIEW

**Comment by yogkumgit** [comment]
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@cmcatee-MSFT Please merge this PR. Thanks.

**Comment by yogkumgit** [comment]
Gentle reminder @cmcatee-MSFT Please merge this PR. Thanks

**Comment by snickler** [comment]
@cmcatee-MSFT are you able to take a look at this? :)

**Review by cmcatee-MSFT — APPROVED** [review]

**Comment by cmcatee-MSFT** [comment]
@snickler I've verified with the product group that the addendum is OK to add. Thanks!

**Pull request merged**
