### PR TITLE
Update prerequisites.md

### PR DESCRIPTION
**Pull request by msbemba**
Added M365 Business premium as well to the document

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by msbemba** [comment]
issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/2237

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@jaimeo Please merge this PR. Thanks.

**Comment by jaimeo** [comment]
I'll be glad to once I have review/signoff from a Microsoft Managed Desktop SME.

**Comment by jaimeo** [comment]
SME advises this is incorrect.

**Pull request closed without merging**
