### PR TITLE
Update enable-archive-mailboxes.md

### PR DESCRIPTION
**Pull request by msbemba**
Updated the document to not reflect enabling archives in the compliance purview as it no longer exists

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by msbemba** [comment]
issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/9996

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@msbemba Shall we close it.

**Comment by msbemba** [comment]
Closing per author

**Pull request closed without merging**
