### PR TITLE
Update allowselfservicepurchase-powershell.md

### LINKED ISSUE #11944: Please add the information of Viva Learning on [View a list of self-service purchase products and their status]
[Enter feedback here]
Please add the information of Viva Learning on [View a list of self-service purchase products and their status] list.

Product: Viva Learning
ProductId: CFQ7TTC0HVZG

#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5082f7ed-ad40-04c1-5c6c-59e67b253257
* Version Independent ID: 3d8b109d-285c-952f-2fa4-9fa244c2a3f9
* Content: [Use AllowSelfServicePurchase for the MSCommerce PowerShell module](https://learn.microsoft.com/en-us/microsoft-365/commerce/subscriptions/allowselfservicepurchase-powershell?view=o365-worldwide)
* Content Source: [microsoft-365/commerce/subscriptions/allowselfservicepurchase-powershell.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/subscriptions/allowselfservicepurchase-powershell.md)
* Service: **microsoft-365-business**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**
imagefor change

### PR DESCRIPTION
**Pull request by msbemba**
Added Viva to the list

Fixes https://github.com/MicrosoftDocs/microsoft-365-docs/issues/11944

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@cmcatee-MSFT Please merge this PR. Thanks

**Comment by cmcatee-MSFT** [comment]
Verifying with PM that this should be added to the list.

**Comment by cmcatee-MSFT** [comment]
@msbemba @yogkumgit The product team said Viva Learning never went to GA, so they don't want this information added at this time.

**Pull request closed without merging**
