### PR TITLE
Update endpoint-dlp-learn-about.md

### PR DESCRIPTION
**Pull request by msbemba**
Added .zip and arj files to the list of monitored files as mentioned in the technet blog -https://techcommunity.microsoft.com/t5/security-compliance-and-identity/announcing-expanded-dlp-coverage-to-new-file-and-content-types/ba-p/2902869#:~:text=Protect%20sensitive%20files,inappropriate%20file%20transfer.

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by msbemba** [comment]
issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/7462

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@chrfox Please merge this PR. Thanks

**Comment by chrfox** [comment]
suport for archive files is being documented elsewhere and is not yet publicy

**Comment by msbemba** [comment]
Thank you @chrfox. I read the blog here - https://techcommunity.microsoft.com/t5/security-compliance-and-identity/announcing-expanded-dlp-coverage-to-new-file-and-content-types/ba-p/2902869 and was under the impression that this is already public. Do you know when this will be public so I can inform the user who raised the request?

Thanks
Sri

**Pull request closed without merging**
