### PR TITLE
Update sit-modify-edm-schema-configurable-match.md

### PR DESCRIPTION
**Pull request by maberzin**
Pipe delimiter is supported for EDM configurable match; however, detection of EDM corroborative evidence isn't supported for pipe delimited content. This will be separately documented later and is not directly related to configurable match.

### CODE REVIEW

**Comment by yogkumgit** [comment]
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by maberzin** [comment]
Adding @chrfox for visibility.

**Comment by yogkumgit** [comment]
@chrfox Please merge this PR. Thanks

**Comment by yogkumgit** [comment]
@chrfox Gentle reminder

**Pull request merged**
