### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by CHaase11**

### CODE REVIEW

**Comment by yogkumgit** [comment]
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

**Comment by jaimeo** [comment]
@CHaase11 this link doesn't work: [App Assure](/fasttrack/products-and-capabilities#app-assure) program

You can't format it that way across docsets. Can you provide the external URL for that destination?

**Comment by CHaase11** [comment]
> @CHaase11 this link doesn't work: [App Assure](/fasttrack/products-and-capabilities#app-assure) program
> 
> You can't format it that way across docsets. Can you provide the external URL for that destination?

Sorry! Here is the URL: https://docs.microsoft.com/en-us/fasttrack/products-and-capabilities#app-assure

**Comment by jaimeo** [comment]
No worries--I note it was that way in the original, which means it probably never worked! :^( I'll fix all the instances.

**Pull request merged**
