### PR TITLE
Update admin-submission.md

### PR DESCRIPTION
**Pull request by andypunt**
Updated the docs for the new security center page.

We need to also update the pics, but I am unable to do that.

### CODE REVIEW

**Comment by yogkumgit** [comment]
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

**Comment by andypunt** [comment]
Just to confirm, the screenshots in this doc need to be updated and I could not do that. I would also ask that an editor do a full check on the doc from top down to make sure it makes sense and works.


Andy

**Comment by chrisda** [comment]
@andypunt, be advised that the vendor army is sweeping through and updating all security/office-365-security topics from the SCC to the SC as we speak. I'm hesitant to approve this in case it collides with what they are already doing.

**Comment by andypunt** [comment]
Is the sweep to just change SCC to SC or includes all the trimmings like screenshots as well. If it includes screenshots and strings that come with the new UI, then I am fine with waiting. My ask would be that we front load this article if we can. Can we?


Andy

**Comment by chrisda** [comment]
@andypunt, no problem. I merged and we can deal with any issues later. I'll also update the screenshots when I get a chance.

**Comment by andypunt** [comment]
Thanks Andy! I'll update the screenshots next week.

________________________________
From: Andy Puntahachart ***@***.***>
Sent: Thursday, June 10, 2021 7:54 AM
To: MicrosoftDocs/microsoft-365-docs ***@***.***>; MicrosoftDocs/microsoft-365-docs ***@***.***>
Cc: Author ***@***.***>; Chris Davis (EXCHANGE) ***@***.***>; Daniel Simpson ***@***.***>; Ratula Chakrabarti (Aquent LLC) ***@***.***>
Subject: RE: [MicrosoftDocs/microsoft-365-docs] Update admin-submission.md (#5270)


Just to confirm, the screenshots in this doc need to be updated and I could not do that. I would also ask that an editor do a full check on the doc from top down to make sure it makes sense and works.





Andy

**Pull request merged**
