### PR TITLE
Update deployment-vdi-microsoft-defender-antivirus.md

### PR DESCRIPTION
**Pull request by msbemba**
Updated the document with non-persistent VDI's to reduce ambiguity. Let me know if there should be a mention of Non-persistent VDI's throughout the document or is the change at the beginning enough?

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/7666

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@denisebmsft Please merge this PR. Thanks

**Review by denisebmsft — APPROVED** [review]
Thank you @msbemba

**Pull request merged**
