### PR TITLE
Update dlp-exchange-conditions-and-actions.md

### PR DESCRIPTION
**Pull request by ybhargav1995**

### CODE REVIEW

**Comment by yogkumgit** [comment]
@ybhargav1995 Thanks for your feedback! New issues and pull requests for this content are closed while we update this content to support upcoming feature improvements.

**Comment by ybhargav1995** [comment]
So how do i add this then? @yogkumgit

**Comment by ybhargav1995** [comment]
@chrfox - Should I redo this change after the repo migration or something?

**Comment by chrfox** [comment]
@ybhargav1995 
Make the change now, but in the private repo, not the public one.  I can get it in before the migration.

https://review.learn.microsoft.com/en-us/office-authoring-guide/contribute-get-started-setup-quick-update?branch=main

**Comment by ybhargav1995** [comment]
@chrfox - made the changes here: https://github.com/MicrosoftDocs/microsoft-365-docs-pr/pull/21497

**Pull request closed without merging**
