### PR TITLE
Update list-recommendation-software.md

### PR DESCRIPTION
**Pull request by msbemba**
Updated application permission

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/6056

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@DulceMontemayor Please merge this PR. Thanks

**Comment by yogkumgit** [comment]
@DulceMontemayor Gentle reminder.

**Pull request merged**
