### PR TITLE
Update information-barriers.md

### PR DESCRIPTION
**Pull request by msbemba**
Updated licensing requirements per MC290063

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/6568

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@robmazz Please merge this PR. Thanks

**Comment by rsoakford** [comment]
@msbemba , thank you for updating me - it seems the changes to the document have not been merged - is that because the message center announcement regarding availability of Information Barriers feature for Microsoft 365 A1 and A3 licenses is no longer current?

**Comment by yogkumgit** [comment]
@robmazz Gentle reminder

**Comment by rsoakford** [comment]
Thank you @robmazz 👍

**Pull request merged**
