### PR TITLE
updated content to include requested information

### PR DESCRIPTION
**Pull request by VLG17**
https://github.com/MicrosoftDocs/microsoft-365-docs/issues/232

### CODE REVIEW

**Comment by mypil** [comment]
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

**Comment by jdeckerms** [comment]
@VLG17 Hi, are you on the Microsoft Managed Desktop product team?

**Comment by mypil** [comment]
@jdeckerms - @VLG17 is one of our technical freelancers for the MSFT Github Technical Writing and Editing Talent Store. I believe @kenwith can help explain our roles further. Thanks.

**Comment by jdeckerms** [comment]
@mypil Thanks for the explanation. Changes to Microsoft Managed Desktop documentation are carefully controlled as it is a new service. I will not be merging this pull request.

**Pull request closed without merging**
