### PR TITLE
Update mexico.md

### PR DESCRIPTION
**Pull request by msbemba**
Updated the country code for mexico

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/8862

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@cmcatee-MSFT Please merge this PR. Thanks

**Comment by yogkumgit** [comment]
@cmcatee-MSFT Gentle reminder. Thanks

**Comment by cmcatee-MSFT** [comment]
@msbemba & @yogkumgit The mexico.md file was retired, and is now replaced by [Find Microsoft 365 for business phone support numbers by country or region](https://learn.microsoft.com/en-us/microsoft-365/admin/support-contact-info?view=o365-worldwide). I'm working with our internal team to verify the alternate number for Mexico, and will update the new article when I have the correct information.

**Pull request closed without merging**
