### PR TITLE
Adding new Lighthouse topic

### PR DESCRIPTION
**Pull request by pabloang1**
@SKjerland - Adding new article, screenshot, and update toc entry for Lighthouse Vulnerability management.

### CODE REVIEW

**Comment by SKjerland** [comment]
@pabloang1 - Thanks! I'll review after my meeting.

**Review by SKjerland — APPROVED** [review]

**Comment by pabloang1** [comment]
@added lightbox attribute to image. Please confirm you see update on your end.

**Comment by pabloang1** [comment]
@SKjerland --- added lightbox attribute. Please confirm change was submitted.

**Comment by SKjerland** [comment]
@pabloang1 - Yup, I see the change. Thanks! I can go ahead and merge now.

**Pull request merged**
