### PR TITLE
Update insider-risk-management-browser-support.md

### PR DESCRIPTION
**Pull request by msbemba**
Updated the document to reflect Microsoft Purview Extension

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/9822

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@robmazz Please merge this PR. Thanks

**Comment by yogkumgit** [comment]
@robmazz Gentle reminder.

**Comment by yogkumgit** [comment]
Closing as per the comment in #9822

**Pull request closed without merging**
