### PR TITLE
Update tp_GraphicEOPATPP1P2_2.png

### PR DESCRIPTION
**Pull request by msbemba**
Made changes from ATP to MDO

### CODE REVIEW

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/5576

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by denisebmsft** [comment]
@MSFTTracyP please take a look. @msbemba thank you for the pull request! One thing that will need to be changed is the file name.... it cannot contain any underscores in it. Just alphanumeric characters and hyphens.

**Review by JohanFreelancer9 — CHANGES_REQUESTED** [review]
No copy to review but agree with @denisebmsft; filename needs to change.

**Comment by msbemba** [comment]
@JohanFreelancer9 and @denisebmsft  I have updated the file name.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@MSFTTracyP Please merge this PR. Thanks.

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@yogkumgit I'm not getting an option to resolve conflicts as it states Only those with write access to this repository can merge pull requests.

**Comment by yogkumgit** [comment]
@MSFTTracyP

**Comment by yogkumgit** [comment]
@MSFTTracyP Gentle reminder.

**Pull request closed without merging**
