### PR TITLE
Update validate-device.md

### PR DESCRIPTION
**Pull request by msbemba**
The Link is available only for US. if we change or remove the locale it results in  404

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/5733

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@jaimeo Please merge this PR. Thanks

**Comment by yogkumgit** [comment]
@jaimeo Gentle reminder

**Comment by jaimeo** [comment]
Removing the locale does not repro a 404 for me. But inserting other locales does, so it could be problematic for people in other locales. Looking into why that page isn't following our corporate guidelines re: locales. If I don't learn anything quickly, we can proceed with this as a stopgap.

**Pull request merged**
