### PR TITLE
Update sensitive-information-type-entity-definitions.md

### PR DESCRIPTION
**Pull request by msbemba**
added tfn as a  keyword  to the list of australian tax file number

### CODE REVIEW

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/2084

**Comment by mypil** [comment]
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by mypil** [comment]
@chrfox - PR has been copy edited and is ready for final review. This is based on issue #2084

Thank you.

**Comment by chrfox** [comment]
keywords must match what is hard coded in the product and they are only taken from the product team

**Pull request closed without merging**
