### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by nithasha-samad**

### CODE REVIEW

**Comment by mypil** [comment]
@nenonix @JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by mypil** [comment]
@robmazz - This PR has been copy/edited and is ready for final review. There is no author listed for this doc- README.md. Can you possibly assist to review this PR if it should be merged or closed? Or please let me know who has to be tagged to review this.

Thank you.

cc: @kenwith

**Comment by robmazz** [comment]
@mypil  - I think the GitHub admins cleared this language with CELA when the repo was configured, this may just be legal verbiage that needs to remain as-is, even though these are simple changes. Adding David Strome to confirm.

@dstrome - can you merge or close?

cc: @kenwith

**Comment by dstrome** [comment]
legal language can't be changed. closing without merging.

**Pull request closed without merging**
