### PR TITLE
Update multi-geo-capabilities-in-teams-in-microsoft-365.md

### PR DESCRIPTION
**Pull request by somyasinghal7**
update get-multigeo region cmdlet 2

### CODE REVIEW

**Comment by MikePlumleyMSFT** [comment]
@somyasinghal7 this information should go in the cmdlet reference article.

**Comment by somyasinghal7** [comment]
@MikePlumleyMSFT , can you please share the link for cmdlet reference article?

**Comment by somyasinghal7** [comment]
@MikePlumleyMSFT , I have raised PR to update this doc: https://learn.microsoft.com/en-us/microsoft-365/enterprise/multi-geo-capabilities-in-teams-in-microsoft-365?view=o365-worldwide
as we are changing this cmdlet

**Comment by somyasinghal7** [comment]
@microsoft-github-policy-service agree company="Microsoft"

**Pull request merged**
