### PR TITLE
Update indicator-manage.md

### PR DESCRIPTION
**Pull request by msbemba**
added a note as only 500 indicators can be uploaded for each batch

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/6763

**Comment by BlakeMsft** [comment]
Docs page has not been updated even though I was told a change has been made.

https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/indicator-manage?view=o365-worldwide#import-a-list-of-iocs

**Comment by msbemba** [comment]
@BlakeMsft The PR has not been merged yet by the author. It could take 24-48 hours for the document to reflect the changes post merging the Pull request.

Thanks
Sri

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@mjcaparas Please merge this PR. Thanks

**Pull request merged**
