### PR TITLE
Update configure-exchange-server-for-hybrid-modern-authentication.md

### PR DESCRIPTION
**Pull request by msbemba**
Corrected the "Get-OutlookAnywhere | FL server,url"  to Get-OutlookAnywhere | FL server, HostName as it is not applicable.

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/3623

**Comment by msbemba** [comment]
Issue #https://github.com/MicrosoftDocs/microsoft-365-docs/issues/3634

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by pkondrashov** [comment]
but why do you need Get-OutlookAnywhere - RPC/HTTP protocol is not used with HMA at all?
I would suggest to remove this line.
And BTW, in original blog we don't have it https://techcommunity.microsoft.com/t5/exchange-team-blog/announcing-hybrid-modern-authentication-for-exchange-on-premises/ba-p/607476

**Comment by msbemba** [comment]
@JohanFreelancer9 There have been some changes, can you copy review?

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by LauraWi** [comment]
Looping in @dstrome

**Comment by yogkumgit** [comment]
@dstrome Please merge this PR. Thanks.

**Pull request merged**
