### PR TITLE
Update microsoft-365-copilot-enable-users.md

### PR DESCRIPTION
**Pull request by bipinprakashtss**
github1
The copilot license for education/k12 customers is listed separately under extra features and assignment location is not as visible as it is for E3/E5 licenses.

### CODE REVIEW

**Comment by bipinprakashtss** [comment]
@camillepack Hoping to bump this thread/PR for approval and merge. I have seen a couple of other customers have similar questions (in the Edu space). So, this addendum to the learn document will be quite helpful. 
Thanks,
bp

**Comment by camillepack** [comment]
@bipinprakashtss Thanks for bringing this to my concern and great callout! I'm working to have this note added in the doc. Thanks.

**Comment by bipinprakashtss** [comment]
@camillepack Thank you so much for the quick response. I am hoping, I can be listed as a contributor. Thanks for considering.

**Comment by bipinprakashtss** [comment]
@microsoft-github-policy-service agree

**Pull request merged**
