### PR TITLE
Update usage-analytics-data-model.md

### PR DESCRIPTION
**Pull request by msbemba**
Don't see the tenant office licenses dataset anymore on multiple tenants. This PR removes that from the table..Please review and approve.

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/2672

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@Sirkkuw Please merge this PR. Thanks

**Comment by Sirkkuw** [comment]
@yogkumgit this topic was recently updated and the PG was involved. I think it is correct.

**Pull request closed without merging**
