### PR TITLE
Update cross-tenant-mailbox-migration.md

### PR DESCRIPTION
**Pull request by msbemba**
Updated the shortcut link

Per issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/9761

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@tiburd Please merge this PR. Thanks

**Comment by tiburd** [comment]
close > reopen

**Comment by tiburd** [comment]
@msbemba 
Hi,

Are you able to update the branch?

I'm unable to update the branch. Thomas (admin) said that this might be because you might have checked a setting that allows others to update your PRs...

Please @ mention me after you update the branch so that I can merge the PR.

Thank you!

**Pull request merged**
