### PR TITLE
Update tvm-remediation.md

### PR DESCRIPTION
**Pull request by msbemba**
Made changes to the navigation as it has changed.

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by msbemba** [comment]
issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/8319

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@Dansimp Please merge this PR. Thanks

**Comment by chrisda** [comment]
Topic was moved to a different location:

<https://docs.microsoft.com/microsoft-365/security/defender-vulnerability-management/tvm-remediation>

I made the same changes in a different PR.

Closing

**Pull request closed without merging**
