### PR TITLE
Update evaluate-mde.md

### PR DESCRIPTION
**Pull request by msbemba**
removed the broken link as all of these fall under attack surface reduction

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/7951

**Comment by yogkumgit** [comment]
@mjcaparas Please merge this PR. Thanks

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@mjcaparas Please merge this PR. Thanks

**Pull request merged**
