### PR TITLE
Update office-365-service-encryption.md

### PR DESCRIPTION
**Pull request by msbemba**
Corrected the link. The page has been moved from blogs.office.com to Microsoft.com/blogs/. Also note that the link only works with en-us(locale)

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/7601

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@KCCross Please merge this PR. Thanks

**Comment by yogkumgit** [comment]
@tiburd Please help us here. Thanks

**Comment by yogkumgit** [comment]
@tiburd please merge this PR. Thanks

**Pull request merged**
