### PR TITLE
Update manage-deployment-of-add-ins.md

### PR DESCRIPTION
**Pull request by msbemba**
Corrected the navigation path to deploy add-ins

### CODE REVIEW

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/2865

**Comment by msbemba** [comment]
@JohanFreelancer9  Please copy review

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@Sirkkuw Please merge this PR. Thanks.

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review. We have made some changes to this suggested by author.

**Pull request merged**
