### PR TITLE
Fixed typo in whats-new-in-preview.md

### LINKED ISSUE #2723: Typo - Accessibility is misspelled
"Accessibility" is misspelled as "acessibility"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3fe9020-6803-bee8-7fcc-fae3971e6feb
* Version Independent ID: 480b994c-7d3f-d234-8847-e415360c6bf7
* Content: [What's new in the Microsoft 365 admin center? - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/whats-new-in-preview?view=o365-worldwide)
* Content Source: [microsoft-365/admin/whats-new-in-preview.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/whats-new-in-preview.md)
* Service: **o365-administration**
* GitHub Login: @adefowler
* Microsoft Alias: **anfowler**

### PR DESCRIPTION
**Pull request by dariomws**
Closes https://github.com/MicrosoftDocs/microsoft-365-docs/issues/2723.

### CODE REVIEW

**Comment by yogkumgit** [comment]
@adefowler Please merge this PR. Thanks.

**Comment by yogkumgit** [comment]
@adefowler  Gentle reminder, please merge this PR. Thanks.

**Comment by yogkumgit** [comment]
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@Kateyanne Please merge this PR. Thanks.

**Pull request merged**
