### PR TITLE
Update customer-key-overview.md

### PR DESCRIPTION
**Pull request by brucehuy**
@lindalu-MSFT submitting a change

### CODE REVIEW

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@KCCross Please merge this PR. Thanks

**Review by lindalu-MSFT — APPROVED** [review]

**Comment by lindalu-MSFT** [comment]
@yogkumgit This is out of date with the base so you'll need to update/pull the latest into your branch before you merge.

**Comment by yogkumgit** [comment]
@brucehuy

**Comment by yogkumgit** [comment]
@brucehuy  Please update/pull the latest into your branch. Merge is pending. Thanks

**Comment by yogkumgit** [comment]
@brucehuy Please update this PR as guided. In the event of no response, we may close this PR. Thanks

**Comment by yogkumgit** [comment]
@brucehuy Thanks for your feedback! New issues and pull requests for this content are closed while we update this content to support upcoming feature improvements.

**Pull request closed without merging**
