### PR TITLE
Update threat-protection-integration.md

### PR DESCRIPTION
**Pull request by msbemba**
Made changes to the Microsoft defender for cloud description.

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/9639

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@mjcaparas Please merge  this PR. Thanks

**Comment by yogkumgit** [comment]
@denisebmsft please relook into it, not merged yet. Thanks

**Pull request merged**
