### PR TITLE
presevationhold

### PR DESCRIPTION
**Pull request by PramodBalusu**
Updated  note

### CODE REVIEW

**Comment by cabailey** [comment]
Hi @PramodBalusu For consistency, I think it should it be "Preservation Hold library"?

**Comment by PramodBalusu** [comment]
> Hi @PramodBalusu For consistency, I think it should it be "Preservation Hold library"?

Yes

**Review by robertoyms — APPROVED** [review]
Correct, content from the PHL is technically still on the site and therefore part of the site's quota.

**Comment by cabailey** [comment]
Great - thanks for confirming both of you.  

@PramodBalusu : If you make the casing change, I'll merge so this can go live today.

**Comment by PramodBalusu** [comment]
> Great - thanks for confirming both of you.
> @PramodBalusu : If you make the casing change, I'll merge so this can go live today.

@cabailey  You can merge this. Thanks

**Comment by cabailey** [comment]
@PramodBalusu I'm not seeing the casing change agreed ("Preservation Hold Library" to "Preservation Hold library"  No need to close the PR, just make the change and push it to this PR.

**Comment by cabailey** [comment]
@PramodBalusu Change confirmed. Merging now.

**Comment by cabailey** [comment]
#sign-off

**Pull request merged**
