### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Carol-Gibbons**
Adding new images for https://learn.microsoft.com/en-us/microsoft-365/enterprise/setup-guides-for-microsoft-365?view=o365-worldwide

### CODE REVIEW

**Comment by Carol-Gibbons** [comment]
I may have done this pull request incorrectly using my fork to add two images to the media directory.  I want to replace the current images in our Setup guides article.  Please close if I did this wrong.  Thank you.

**Comment by denisebmsft** [comment]
Hello @Carol-Gibbons. Thank you for your submission! One thing I'll need to fix is, the images can't have underscores in their filenames. I'll see if I can make that adjustment. In the meantime, we'll need you to sign the Contributor License Agreement. Please let me know if you have any questions. Thanks again!

**Comment by Carol-Gibbons** [comment]
@microsoft-github-policy-service agree [company="microsoft"]

**Comment by Carol-Gibbons** [comment]
@microsoft-github-policy-service agree

**Review by JohanFreelancer9 — APPROVED** [review]
No copy to review.

**Pull request merged**
