### PR TITLE
Authored a document describing how to migrate from MDE to MDB and how to troubleshoot problems migrating from MDE to MDB

### PR DESCRIPTION
**Pull request by 4D5A**

### CODE REVIEW

**Comment by denisebmsft** [comment]
Hello @4D5A. Thank you so much for your contribution. I am reviewing this and hope to merge it soon.

**Comment by 4D5A** [comment]
Thank you @denisebmsft. This is my first microsoft-365-docs PR so please let me know if I made any mistakes. I look forward to contributing more in the future!

**Comment by denisebmsft** [comment]
> Thank you @denisebmsft. This is my first microsoft-365-docs PR so please let me know if I made any mistakes. I look forward to contributing more in the future!

You did great for a first pull request! Are you by chance a Microsoft employee? If you are, please ping me so I can show you how to link your GitHub account to your microsoft.com account.

**Comment by 4D5A** [comment]
> > Thank you @denisebmsft. This is my first microsoft-365-docs PR so please let me know if I made any mistakes. I look forward to contributing more in the future!
> 
> You did great for a first pull request! Are you by chance a Microsoft employee? If you are, please ping me so I can show you how to link your GitHub account to your microsoft.com account.

No, I am not a Microsoft employee (but that would be cool!).

**Comment by denisebmsft** [comment]
@4D5A I have moved this pull request to our private repository so I can work on it some more and push it out. I'm closing this public one but will come back and comment when the content is about to go live. Thank you again for your contribution!

**Comment by 4D5A** [comment]
Thank you, @denisebmsft ! I appreciate any feedback you can provide so I can improve and make future contributions.

**Comment by denisebmsft** [comment]
@4D5A that's awesome! One thing I did change was the author's name to mine. Not to take credit for your work, but in fact, to enable it to publish. In order to publish any article in our official documentation, it has to have a name that corresponds to an account in our internal system. 

Another thing is, I am confirming is the order of assigning new licenses and unassigning old licenses. Your original draft had the sequence of unassigning Defender for Endpoint licenses before assigning Defender for Business licenses. I actually switched the order of those steps in the hopes this minimizes risk during the switchover. 

There were some other stylistic things we do in docs that I can share in another post. Just minor things we adhere to in our style and voice guidelines.

Currently, I have the draft in tech review, pending publishing in early August. I will keep you posted on the outcome.

Also, just in case you didn't already know, we do have a GitHub repository for community content: https://docs.microsoft.com/microsoft-365/community. There's a lot of good stuff there from kind contributors like you!

**Comment by 4D5A** [comment]
Thank you. That makes sense! I think it would make more sense to assign the Defender for Business licenses first as you edited it.

Thank you for your work on this. I wasn't aware that there was official documentation and community content. Can you share your recommendation on when to publish to the official documentation and when to publish to the community content?

Thank you!

**Pull request closed without merging**
