### PR TITLE
Spelling fixes

### PR DESCRIPTION
**Pull request by modery**
Replacing Microsoft Flow with Power Automate. Also, some minor spelling fixes

### CODE REVIEW

**Comment by markjjo** [comment]
@modery Changes to topics owned by markjjo look good. Topics are

**Review by cabailey — APPROVED** [review]
Approve naming changes for Power Automate in my articles\

**Review by mjcaparas — APPROVED** [review]

**Comment by chrisda** [comment]
I approve

**Review by cmcatee-MSFT — APPROVED** [review]

**Review by MSFTTracyP — APPROVED** [review]
Okay.

**Pull request merged**
