### PR TITLE
Update get-remediation-one-activity.md

### PR DESCRIPTION
**Pull request by msbemba**
Updated application permissions required

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/6058

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@jweston-1 Please merge this PR. Thanks.

**Comment by yogkumgit** [comment]
@jweston-1 Gentle reminder

**Pull request merged**
