### PR TITLE
HMA with linked mailboxes - 2-way trust and domain-wide authenticatio…

### PR DESCRIPTION
**Pull request by gabymuntean**
…n required

We have different customers using linked mailboxes (account/resource forest) which want to implement HMA. The requirements from the documentation does not touch such scenario.
Moreover from the field experience it seems selective auth is not enough, as we need domain-wide auth for HMA to work.

Could we please update the articles below to include a statement related to HMA and linked mailboxes implementation?
How to configure Exchange Server on-premises to use Hybrid Modern Authentication
Hybrid modern authentication overview and prerequisites for using it with on-premises Skype for Business and Exchange servers

Attached (in the ContentIdea https://dev.azure.com/ContentIdea/ContentIdea/_workitems/edit/123230) you can find the discussion on the tech aliases about such requirements and the troubleshooting from the Active Directory team to support this statement, as my colleague trace from end to end in the logs proving that Exchange fails to get the Kerberos token when only 1-way trust is setup between the forests, which is our minimal requirement when implementing linked mailboxes.

Thank you,
Gabriel

### CODE REVIEW

**Comment by yogkumgit** [comment]
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

**Review by JohanFreelancer9 — COMMENTED** [review]
@yogkumgit - this is a request for additional information, and not ready for copy editing.

**Comment by yogkumgit** [comment]
@kelleyvice-msft Please merge this PR. Thanks.

**Comment by LauraWi** [comment]
@dstrome -- are you able to provide review from an Exchange perspective?

**Comment by gabymuntean** [comment]
Hi guys, I appreciate your comments on this one, as it already passed a while and we couldn't issue any statement regarding this one.
Normally if it was not tested, then there is no statement :) but this is being requested and used by a lot of customers nowadays.
Thank you.

**Pull request merged**
