### PR TITLE
Update binaries.md

### PR DESCRIPTION
**Pull request by cnwolisa**
Added min and max size of the zip package

### CODE REVIEW

**Comment by yogkumgit** [comment]
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@mansipatel-usl Please merge this PR. Thanks

**Comment by yogkumgit** [comment]
@mansipatel-usl Gentle reminder.

**Comment by mansipatel-usl** [comment]
@yogkumgit How can I switch someone else from my team to be approver? I'm going on vacation for 1.5 months and won't have access to approve for a while. Is this something we can make @v-zhifufeng owner of?

**Review by mansipatel-usl — APPROVED** [review]

**Comment by yogkumgit** [comment]
@tiburd

**Comment by garycentric** [comment]
@cnwolisa 

Notes must be left-aligned with the preceding text. In this case, the preceding paragraph is in the first column, but the note has four space characters before it. That means that it's treated as a code block, and the result looks like this:

image

As a Microsoft employee, you are strongly encouraged to work in the private repos, not the public. The private repos provide checks for build integrity, checks for spelling & grammar, and preview links of modified pages. You can find out more about working in the private repos in [Get started for contributors without write access](https://review.docs.microsoft.com/en-us/office-authoring-guide/getting-started-read-only?branch=master). If you have any questions about getting started, please post in [Ask an Admin](https://aka.ms/askanadmin) in Teams.

**Pull request merged**
