### PR TITLE
Wrong option selection

### PR DESCRIPTION
**Pull request by joinimran**
Wrong option was selected under set up web-only access for guest users.

Problem: https://github.com/MicrosoftDocs/microsoft-365-docs/issues/1633

### CODE REVIEW

**Comment by joinimran** [comment]
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

**Comment by mypil** [comment]
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by mypil** [comment]
@MikePlumleyMSFT - PR has been copy edited and is ready for final review. This is based on issue #1633.

Thank you.

cc: @kenwith

**Comment by MikePlumleyMSFT** [comment]
The existing text is actually correct. We're requiring managed devices for mobile apps and desktop clients. Since guests would generally not have devices managed by the organization, they would have to use the browser.

**Pull request closed without merging**
