### PR TITLE
Adding additional URLs required for Hybrid Wizard

### PR DESCRIPTION
**Pull request by mukeshHCW**
Copy of #3886 PR. I had created that in working branch and not the public branch.

### CODE REVIEW

**Comment by yogkumgit** [comment]
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by mukeshHCW** [comment]
@JohanFreelancer9 : When will this be live on public facing page.

**Comment by JohanFreelancer9** [comment]
@yogkumgit

**Comment by yogkumgit** [comment]
@kelleyvice-msft

**Pull request merged**
