### PR TITLE
Update offering-DoD-DISA-L2-L4-L5.md

### PR DESCRIPTION
**Pull request by msbemba**
Added Power apps to the IL4 list of SAAS Services - Reference link https://docs.microsoft.com/en-us/power-platform/admin/powerapps-us-government

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/3227

**Comment by msbemba** [comment]
@robmazz From my research I see that power app operational procedures meet the requirements aligning with the DISA SRG IL4 compliance framework.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@robmazz Please merge this PR. Thanks

**Comment by robmazz** [comment]
@msbemba - closing, this offering is currently under review by DISA team, will advise of you suggestion.

**Pull request closed without merging**
