### PR TITLE
Update ediscovery-load-non-office-365-data-into-a-review-set.md

### PR DESCRIPTION
**Pull request by msbemba**
Changed the version to V8.1 as the Purview portal suggests the same and it works

Fixes#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/11174

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@robmazz Please merge this PR> Thanks

**Comment by yogkumgit** [comment]
@robmazz Gentle reminder.

**Comment by yogkumgit** [comment]
Closing as per the comment in #11174

**Pull request closed without merging**
