### PR TITLE
Updates for changeover to the Microsoft 365 compliance center

### PR DESCRIPTION
**Pull request by jdmartinez36**
Updated these documents with navigation and screenshots to reflect the change to using the Microsoft 365 compliance center for retention labels.

Notes for Overview of event-driven retention:

- Updated navigation
- Description updated based on seo work in the SEO Marvel project
- Minor readability and standards updates
- Updated screenshots where necessary

Notes for Overview of file plan manager:

- Updated navigation
- Updated metadata description for SEO (lowered character count)
- Removed Default retention label policy section (Note indicates the feature was removed 4/11/2019)
- Minor readability and standards updates
- Updated screenshots where necessary

The new screenshots were created based on any significant changes. Some screenshots still include the Security & Compliance window in the background. As that is not the focus (and pretty much out of focus visually) and the other windows/.csv images have not changed, I left them as is.

I could not verify all the different retention label settings listed in "Navigating your file plan". Added the ms.custom tag seo-marvel-may2020 for tracking purposes.

### CODE REVIEW

**Comment by jdmartinez36** [comment]
For review by @DaniHalfin and @cabailey.

**Comment by cabailey** [comment]
@jdmartinez36  That's great - thank you!  Will need more time to review carefully.  It would be helpful to have a staging link so can check pictures in context - I might know a way to do that.  In the meantime, a question about style:  I see you have replaced all references to other articles that had "see" to "go to".  I thought we used "go to" for product UI navigation only and not documentation articles?  Or has this guidance changed?

**Comment by jdmartinez36** [comment]
@cabailey 

This is what I found in the MS Writing Style Guide: Use go to to describe the process of going to another document, place, or webpage. Don't use click or click on.

It’s in the 5.10.41 link section. It’s possible I have an outdated version of the guide. I have a file provided, as I can't access the guide online. The last update listed is from September 2019.

**Comment by cabailey** [comment]
Still waiting to hear back about the guidance for "see" vs. "go to" for linked article titles.  I'm thinking it might be best to change them back for consistency - checking this repo, the "see" phrase is used predominantly before article titles (1157 hits) whereas "go to" seems to be reserved for UI or direct URL links.

**Comment by jdmartinez36** [comment]
@cabailey 

Understood. Do you want me to change them back now and push the commit, or wait until the review is complete?

**Comment by cabailey** [comment]
I'll chase up on Monday so wait for now, just wanted to give you an update. I haven't had time to look at the changes yet but should be able to do so Monday as well.  Apologies for the wait.

**Comment by jdmartinez36** [comment]
@cabailey 
No worries! Thanks for the update!

**Comment by cabailey** [comment]
@jdmartinez36 Could you please revert the ones that reference articles on this doc site.  Also, remove the screenshot in the columns section (no longer matches).

**Comment by jdmartinez36** [comment]
@cabailey Hi Carol. I've reverted the link references back to "see", but I'm not sure which column screenshot you want me to remove. I'm assuming it's in the file-plan-manager article, and there's one under the "Label settings columns" section and one under the "Retention label file plan descriptors columns". Files are file-plan-label-columns and file-plan-descriptors-on-labels-tab.

**Comment by cabailey** [comment]
@jdmartinez36  Remove file-plan-label-columns.png  Also, in event-driven-retention.md, please change back "For more information, see [Disposition of content](disposition.md)".

**Comment by jdmartinez36** [comment]
@cabailey I've reverted the link text back and removed the image. Also reverted the Disposition link back. Which is kind of strange, since I don't remember changing any links. Then again, I just inched closer to 40. My mind is probably going. Let me know if you have any other edits.

**Comment by cabailey** [comment]
@jdmartinez36  Thanks for all your work!  The link changed in master, so I wonder if you didn't pull down the latest updates from master?  I'll take it from here - pulled down your branch as we discussed, using #3595.

FYI @DaniHalfin

**Pull request closed without merging**
