### PR TITLE
Update alert-policies.md

### PR DESCRIPTION
**Pull request by ssaini-pm**
Adding missed mention for all EOP, MDO P1 or P2 add on subsciption as a SKU option for 2 alerts.

### CODE REVIEW

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@robmazz  Please merge this PR. Thanks.

**Comment by yogkumgit** [comment]
@robmazz Gentle reminder.

**Comment by tiburd** [comment]
I am unable to confirm the changes in this PR, and there is a file conflict, so I am removing myself as an assignee.

**Comment by yogkumgit** [comment]
@ssaini-pm Thanks for your feedback! New issues and pull requests for this content are closed while we update this content to support upcoming feature improvements.

**Pull request closed without merging**
