### PR TITLE
Update encryption-office-365-tls-certificates-changes.md

### LINKED ISSUE #12234: Outdated suspense dates
This page says: "Services began transitioning to the new Root CAs in January 2022 and will continue through October 2022." It's now June 2023, and the page should be updated to indicate the current state of the rollout. Is it done? Is it still ongoing? The world wonders.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c23df2b9-0e0e-1a54-2f42-effb9387459a
* Version Independent ID: c23df2b9-0e0e-1a54-2f42-effb9387459a
* Content: [Office TLS certificate changes - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/encryption-office-365-tls-certificates-changes?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/encryption-office-365-tls-certificates-changes.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/encryption-office-365-tls-certificates-changes.md)
* Service: **o365-seccomp**
* GitHub Login: @pshelton-skype
* Microsoft Alias: **pshelton**

### PR DESCRIPTION
**Pull request by msbemba**
Made changes to the date

Fixes https://github.com/MicrosoftDocs/microsoft-365-docs/issues/12234

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@pshelton-skype Please merge this PR. Thanks

**Comment by pshelton-skype** [comment]
I don't have permissions to merge commits.

**Comment by yogkumgit** [comment]
Closing as per the comment in #12234

**Pull request closed without merging**
