### PR TITLE
Update safe-links.md

### PR DESCRIPTION
**Pull request by msbemba**
Added a note about safe links not working on a public folder. I have tested and this is by design as multiple users will be accessing the same folder and it is not possible to wrap URL with a specific user.

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/5030

**Comment by msbemba** [comment]
@chrisda I see a Typo in the note. It should be "Safe" Sorry about that.

**Comment by chrisda** [comment]
OK. Fixed

**Pull request merged**
