### PR TITLE
Update dlp-microsoft-teams.md

### LINKED ISSUE #12025: Licence clarification
[Enter feedback here]
https://learn.microsoft.com/en-us/microsoft-365/compliance/dlp-microsoft-teams?view=o365-worldwide#dlp-licensing-for-microsoft-teams
In the above section, Does F5 Information Protection & Governance include Teams DLP? If yes, can you please update this page?

The below article clearly says F5 IP&G includes Teams DLP
https://learn.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance#microsoft-purview-data-loss-prevention-data-loss-prevention-dlp-for-teams

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ebaab3f7-d1d4-c649-efe8-f24913da4f3e
* Version Independent ID: c5710ebf-0ca5-ab46-c490-64ebc308defe
* Content: [Data loss prevention and Microsoft Teams - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/dlp-microsoft-teams?view=o365-worldwide#dlp-licensing-for-microsoft-teams)
* Content Source: [microsoft-365/compliance/dlp-microsoft-teams.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/dlp-microsoft-teams.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

### PR DESCRIPTION
**Pull request by msbemba**
Added F5 Information Protection & Governance to the list of licenses as per the Reference https://learn.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance#which-users-benefit-from-the-service-1

Fixes https://github.com/MicrosoftDocs/microsoft-365-docs/issues/12025

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@chrfox Please merge this PR. Thanks

**Comment by yogkumgit** [comment]
@chrfox Gentle reminder.

**Comment by yogkumgit** [comment]
Closing as per the comment in #12025

**Pull request closed without merging**
