### PR TITLE
Adding information about Admin Center updates for Office Scripts using Power Automate

### PR DESCRIPTION
**Pull request by AlexJerabek**
There's a new Admin Center option for controlling use of Office Scripts with Power Automate:

image

This PR documents that option.

### CODE REVIEW

**Review by petraronald — APPROVED** [review]

**Comment by AlexJerabek** [comment]
@denisebmsft When should we expect this PR to be reviewed and merged? 

Thanks!

**Comment by yogkumgit** [comment]
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@SKjerland Please merge this PR. Thanks.

**Comment by denisebmsft** [comment]
> @denisebmsft When should we expect this PR to be reviewed and merged?
> 
> Thanks!

Hello @AlexJerabek! You're in good hands with @SKjerland. She'll review and merge this.

**Comment by AlexJerabek** [comment]
@SKjerland, can this please be merged soon?

**Comment by AYOUBHSN14** [comment]
[h1@ayob10399731751.onmicrosoft.com](https://github.com/AlexJerabek/microsoft-365-docs/tree/AlexJ-OfficeScriptsAdminChanges) ``

**Comment by AlexJerabek** [comment]
@SKjerland, @denisebmsft, These admin center changes are live and we need these doc updates out.

**Comment by SKjerland** [comment]
Sorry for the delay, everyone! All notifications from GitHub have been going to a different folder than my inbox, and I haven't seen any of these requests. Seems my Outlook rule broke somehow.

**Pull request merged**
