### PR TITLE
Update readiness-assessment-tool.md

### PR DESCRIPTION
**Pull request by msbemba**
requires Intune administrator along with global reader or above to run the tool

### CODE REVIEW

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/5070

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@jaimeo Please merge this PR. Thanks.

**Comment by jaimeo** [comment]
This is not a good edit. The SME is double-checking some things and then we'll rewrite as needed based on that.

**Pull request closed without merging**
