### PR TITLE
Update session-timeouts.md

### PR DESCRIPTION
**Pull request by RomanMSFT**

### CODE REVIEW

**Comment by yogkumgit** [comment]
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

**Comment by JohanFreelancer9** [comment]
@yogkumgit, this is a request for additional information. Can you please follow up on this? Thanks.

**Comment by yogkumgit** [comment]
@MSFTTracyP Please help us here. Thanks

**Comment by tiburd** [comment]
@RomanMSFT 
Hi,
If you still want to submit this change, please create a new PR in the private repo and have it reviewed by the article author.
Thank you!

cc: @yogkumgit

**Pull request closed without merging**
