### PR TITLE
Update get-machine-group-exposure-score.md

### PR DESCRIPTION
**Pull request by msbemba**
Corrected the description to reflect device instead if Domain.

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy reveiw

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/5926

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by denisebmsft** [comment]
@siosulli if this is not yours please let me know.

**Comment by yogkumgit** [comment]
@siosulli Please reply or merge this PR. Thanks

**Comment by yogkumgit** [comment]
@siosulli Gentle reminder

**Pull request merged**
