### PR TITLE
Update data-classification-overview.md

### PR DESCRIPTION
**Pull request by msbemba**
Added prerequisites to document

### CODE REVIEW

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/1263

**Comment by mypil** [comment]
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by mypil** [comment]
@chrfox - PR has been copy edited and is ready for final review. This is based on issue #1263.

Thank you.

cc: @kenwith

**Comment by chrfox** [comment]
rejecting, this is already added to the sub topics

**Pull request closed without merging**
