### PR TITLE
Update support-contact-info.md

### LINKED ISSUE #12751: Sri Lanka‘s Phone number 2423 254 is incorrect.
Sri Lanka‘s Phone number 2423 254 is incorrect. 

it should be 0112423254

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4fd44420-06a6-a5aa-973c-fb5fdc1ff758
* Version Independent ID: 4fd44420-06a6-a5aa-973c-fb5fdc1ff758
* Content: [Find Microsoft 365 for business support phone numbers by country or region - Microsoft 365 admin](https://learn.microsoft.com/en-us/microsoft-365/admin/support-contact-info?view=o365-worldwide#sri-lanka)
* Content Source: [microsoft-365/admin/support-contact-info.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/support-contact-info.md)
* Service: **microsoft-365-business**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

### PR DESCRIPTION
**Pull request by msbemba**
Updated Srilanka Phone number

Fixes https://github.com/MicrosoftDocs/microsoft-365-docs/issues/12751

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@cmcatee-MSFT Please merge this PR> Thanks

**Comment by yogkumgit** [comment]
@cmcatee-MSFT Gentle reminder.

**Comment by Sarahxxy** [comment]
@cmcatee-MSFT 

Hi Cern, I found the content is not updated yet on webpage: https://learn.microsoft.com/en-us/microsoft-365/admin/support-contact-info?view=o365-worldwide#sri-lanka

Could you merge the change or let us know if you need other validation steps? Thanks.

**Pull request merged**
