### PR TITLE
Update advanced-hunting-expert-training.md

### PR DESCRIPTION
**Pull request by msbemba**
Updated the Youtube video on the site to the most recent one.

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/7629

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@schmurky Please merge this PR. Thanks

**Comment by schmurky** [comment]
It's the same video, no need to update. Kindly delete this branch.

**Pull request closed without merging**
