### PR TITLE
Update insider-risk-management-adaptive-protection.md

### PR DESCRIPTION
**Pull request by msbemba**
removed the ambiguous statement.

Fixes#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/11273

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@robmazz Please merge this PR. Thanks

**Comment by yogkumgit** [comment]
@robmazz Gentle reminder.

**Comment by yogkumgit** [comment]
Closing as per the comment in #11273

**Pull request closed without merging**
