### PR TITLE
Update migrate-from-e3.md

### PR DESCRIPTION
**Pull request by msbemba**
removed references of Outlook customer manager as it was retired earlier this year.

### CODE REVIEW

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/3734

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@Sirkkuw Please merge this PR. Thanks

**Comment by yogkumgit** [comment]
@cmcatee-MSFT Please merge this PR. Thanks.

**Comment by yogkumgit** [comment]
@cmcatee-MSFT Gentle reminder, Please merge this PR. Thanks.

**Pull request merged**
