### PR TITLE
Update linux-install-with-puppet.md

### PR DESCRIPTION
**Pull request by msbemba**
Made changes per issue@8152 as current snippet does not generate a working apt source list:

Changing release => $channel,
to
release => $facts['os']['distro']['codename']

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/8152

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@Dansimp Please merge this PR. Thanks

**Comment by akomakom** [comment]
I had initially suggested this change in #8152 as a **workaround**, not a fix.  It is almost certainly **not** the right way to address the problem.  It ignores the `$channel` parameter on Debian distributions.  

Perhaps something like this would be more appropriate:

```puppet

# Puppet manifest to install Microsoft Defender for Endpoint on Linux.
# @param channel The release channel based on your environment, insider-fast or prod.
# @param distro The Linux distribution in lowercase. In case of RedHat, Oracle Linux, Amazon Linux 2, and CentOS 8, the distro variable should be 'rhel'.
# @param version The Linux distribution release number, e.g. 7.4.

class install_mdatp (
$channel = 'insiders-fast',
$distro = undef,
$version = undef
){
    case $::osfamily {
        'Debian' : {
            $release = $channel ? {
                'prod' => $facts['os']['distro']['codename'],
                default => $channel
            }
            apt::source { 'microsoftpackages' :
                location => "https://packages.microsoft.com/config/${distro}/${version}/prod",
                release  => $release,
                repos    => 'main',
                key      => {
                    'id'     => 'BC528686B50D79E339D3721CEB3E94ADBE1229CF',
                    'server' => 'keyserver.ubuntu.com',
                },
            }
        }
        
....
```
(Use the release-appropriate channel for "prod".  For others, assume that there is a release by that name, eg 'insiders-fast')

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@akomakom I'm in touch with the author to see if this can be fixed in the backend.

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@yogkumgit the changes have been made. Waiting for author to verify and approve

**Comment by yogkumgit** [comment]
@Dansimp Please merge this PR. Thanks

**Pull request merged**
