### PR TITLE
Update mac-schedule-scan.md

### PR DESCRIPTION
**Pull request by msbemba**
Updated the links under ## Schedule a scan with Intune

fixes#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/10832

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Review by denisebmsft — APPROVED** [review]
Thank you @msbemba

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@mjcaparas Please merge this PR. Thanks

**Comment by yogkumgit** [comment]
@tiburd Please merge this PR. Thanks

**Pull request merged**
