### PR TITLE
Minor correction to M365 admin roles

### PR DESCRIPTION
**Pull request by ndambrosio**
Teams Service Administrator is now Teams Administrator

### CODE REVIEW

**Comment by 9910sameul9999** [comment]
Ok

**Review by 9910sameul9999 — APPROVED** [review]
Ok

**Comment by yogkumgit** [comment]
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@tiburd Please merge this PR. Thanks

**Pull request merged**
