### PR TITLE
Update add-storage-space.md

### PR DESCRIPTION
**Pull request by msbemba**
Made changes to the way we purchase add-s as it is in purchase services page now

Fixes https://github.com/MicrosoftDocs/microsoft-365-docs/issues/12688

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@cmcatee-MSFT Please merge this PR. Thanks

**Comment by yogkumgit** [comment]
@cmcatee-MSFT Gentle reminder. Thanks

**Comment by cmcatee-MSFT** [comment]
Article to be refreshed.

**Pull request closed without merging**
