### PR TITLE
Update tvm-remediation.md

### PR DESCRIPTION
**Pull request by msbemba**
Added more information about how to use Intune to remediate vulnerabilities to point 5

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/10227

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by siosulli** [comment]
Hi @msbemba! I'm just double checking this one as I see the link you added is already below point 6. Did you want to move it from there to the end of point 5? 

Thanks!
Sinead

**Comment by msbemba** [comment]
@siosulli Thank you for pointing that out. Yes, I thought at it is better to be placed after point 5 as we are discussing accept and reject which is discussed in the link.

I have now removed the line that's present after point 6. Let me know if that's Ok.

Thanks
Sri

**Pull request merged**
