### PR TITLE
Update ediscovery-search-and-delete-teams-chat-messages.md

### PR DESCRIPTION
**Pull request by msbemba**
Made changes to the Graph queries

Fixes#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/10694

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by yogkumgit** [comment]
@robmazz Please merge this PR. Thanks.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@robmazz Gentle reminder.

**Comment by yogkumgit** [comment]
Closing as per the comment in #10694

**Pull request closed without merging**
