### PR TITLE
Update customer-key-manage.md

### PR DESCRIPTION
**Pull request by msbemba**
Updated powershell example for Register-SPODataEncryptionPolicy(reference : https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/register-spodataencryptionpolicy?view=sharepoint-ps)

### CODE REVIEW

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/6487

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@KCCross Please merge this PR. Thanks

**Comment by yogkumgit** [comment]
@KCCross Gentle reminder.

**Pull request merged**
