### PR TITLE
Update modern-desktop-deployment-and-management-lab.md

### PR DESCRIPTION
**Pull request by msbemba**
Added recommendation of 300 GB as per the lab kit.

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/3500

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@JoeDavies-MSFT Please merge this PR. Thanks.

**Comment by JoeDavies-MSFT** [comment]
This change has already been made by the person who owns the download kit. Thanks.

**Pull request closed without merging**
