### PR TITLE
Update what-if-my-subscription-expires.md

### PR DESCRIPTION
**Pull request by msbemba**
Added enterprise subscription as well as the data and access remain the same

Fixes https://github.com/MicrosoftDocs/microsoft-365-docs-pr/issues/23661

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@cmcatee-MSFT Please merge this PR. Thanks

**Comment by yogkumgit** [comment]
@cmcatee-MSFT Gentle reminder. Thanks

**Comment by cmcatee-MSFT** [comment]
The article is getting a rewrite. I've raised this issue with the PM, and will make any changes in the new version, as needed.

**Pull request closed without merging**
