### PR TITLE
Update view-the-data-governance-reports.md

### PR DESCRIPTION
**Pull request by msbemba**
Added Hyperlink to the dashboard for easy access

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/3176

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@cabailey Please merge this PR. Thanks.

**Comment by cabailey** [comment]
#sign-off  Note that this article will soon be retired.  Customers should be using the Microsoft 365 compliance center instead of the Office 365 Security & Compliance center for this information.  See https://docs.microsoft.com/microsoft-365/compliance/data-classification-overview

**Pull request merged**
