### PR TITLE
Update classifier-learn-about.md

### PR DESCRIPTION
**Pull request by msbemba**
Fixed duplicate content in Pre-trained classifier section

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/8878

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@chrfox Please merge this PR. Thanks

**Comment by yogkumgit** [comment]
@chrfox Gentle reminder. Thanks

**Comment by chrfox** [comment]
already fixed in another PR

**Pull request closed without merging**
