### PR TITLE
Update respond-machine-alerts.md

### PR DESCRIPTION
**Pull request by msbemba**
Updated the Details on ISolation through live response as it is only supported on Macos

### CODE REVIEW

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/9610

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Review by eepyaich — COMMENTED** [review]
Apologies, but I think the "Use" after the new text needs to be changed to "use" (lower case 'u').

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@mjcaparas Please merge this PR. Thanks

**Pull request merged**
