### PR TITLE
Update create-dns-records-at-any-dns-hosting-provider.md

### PR DESCRIPTION
**Pull request by UpNorthCoder**
Fix issue #2648 MicrosoftDocs/feedback

### CODE REVIEW

**Comment by mypil** [comment]
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by mypil** [comment]
@D3Design - Which issue within this repo is this PR based on? Can you please share the link here?

Thank you.

**Comment by UpNorthCoder** [comment]
@mypil - I originally submitted it in Feedback, and decided to "fix it myself." 
Should I link it?
https://github.com/MicrosoftDocs/feedback/issues/2648

**Comment by mypil** [comment]
@D3Design - Thanks for submitting this PR to fix the issue you created. I will tag the author so he can review and to get his approval to merge this PR.

**Comment by mypil** [comment]
@pebaum - PR has been copy edited and is ready for final review. 

Thank you.

cc: @kenwith

**Pull request merged**
