### PR TITLE
Update enable-usage-analytics.md

### PR DESCRIPTION
**Pull request by msbemba**
Change the PNG file as It uses OAuth 2 instead of Microsoft account

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9  Please copy review

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/2737

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@Sirkkuw please merge this PR. Thanks.

**Comment by msbemba** [comment]
This also fixes  Issue# https://github.com/MicrosoftDocs/microsoft-365-docs/issues/2767

**Comment by yogkumgit** [comment]
@Sirkkuw Gentle reminder Please merge this PR. Thanks.

**Pull request merged**
