### PR TITLE
Update upgrade-distribution-lists.md

### PR DESCRIPTION
**Pull request by msbemba**
Cosmetic- Removed ' from the powershell cmdlet

### CODE REVIEW

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/4269

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@scotvidican Please help us in merging this PR. Thanks

**Comment by yogkumgit** [comment]
@scotvidican Gentle reminder. Please merge PR. Thanks

**Comment by yogkumgit** [comment]
@kwekuako Please merge this PR. Thanks

**Pull request merged**
