### PR TITLE
Update guidance arround Screen limitation

### PR DESCRIPTION
**Pull request by BasileJoly**
Update guidance arround Screen limitation, since August 2022 we can have 10.9" screens

### CODE REVIEW

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@BasileJoly Please review the validation, it should be passed. Thanks

**Comment by yogkumgit** [comment]
@BasileJoly gentle reminder

**Comment by BasileJoly** [comment]
I have reviewed already , all checks have been passed

**Comment by BasileJoly** [comment]
Can you just apply the change ?
It's very complicated to modify even after validation

**Review by BasileJoly — COMMENTED** [review]
i cannot approve

**Review by BasileJoly — COMMENTED** [review]
approve

**Comment by yogkumgit** [comment]
@LanaChin Please review and merge this PR. Thanks

**Comment by yogkumgit** [comment]
@LanaChin Gentle reminder.

**Review by samanro — APPROVED** [review]

**Comment by samanro** [comment]
This has been updated: https://learn.microsoft.com/en-us/microsoft-365/frontline/switch-from-enterprise-to-frontline?view=o365-worldwide

**Pull request closed without merging**
