### PR TITLE
Changed PDL sync SLA line

### PR DESCRIPTION
**Pull request by chhaya-sharma9**
Modified from "at least 24hours" to "atleast 48-72 hours"

### CODE REVIEW

**Comment by yogkumgit** [comment]
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

**Comment by MikePlumleyMSFT** [comment]
@AdwoodMicrosoft can you review?

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
Gentle reminder @AdwoodMicrosoft

**Comment by WayneEwington** [comment]
This is not the correct article to be updated with regards to waiting 24 hours for the PDL to replicated. As such this Pull Request should be rejected.

**Pull request closed without merging**
