### PR TITLE
Update turn-bookings-on-or-off.md

### PR DESCRIPTION
**Pull request by msbemba**
Corrected the navigation path for Bookings as it has changed

### CODE REVIEW

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/3142

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@kwekuako Please merge this PR. Thanks.

**Comment by yogkumgit** [comment]
@kwekuako Gentle reminder please merge this PR. Thanks.

**Pull request merged**
