### PR TITLE
Remove old Endpoints of Hybrid Exchange

### PR DESCRIPTION
**Pull request by mukeshHCW**
Remove old Endpoints of Hybrid Exchange and adding new endpoints

### CODE REVIEW

**Comment by yogkumgit** [comment]
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

**Comment by mukeshHCW** [comment]
@yogkumgit : this is urgent change as there are press leaks around this URL being stale and used by bounty hunters to show MS vulnerability. Please ensure the changes go live on https://docs.microsoft.com/en-us/microsoft-365/enterprise/additional-office365-ip-addresses-and-urls?view=o365-worldwide
immediately. Thanks.

**Comment by mukeshHCW** [comment]
cc: @JoeDavies-MSFT

**Comment by pandrew1** [comment]
@kelleyvice-msft @KCCross in case you can get to this faster than Joe today

**Pull request merged**
