### PR TITLE
added new platform update v4.18.2110-6.0

### PR DESCRIPTION
**Pull request by RAJU2529**
I added a new platform update version 4.18.2110-6.0 which is added on  3rd  November 2021, I verified this 4.18.2110-6.0 version under Windows 11 RTM build no 22000.318
Screenshot 2021-11-11 212416

### CODE REVIEW

**Comment by yogkumgit** [comment]
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@denisebmsft Please merge this PR. Thanks

**Review by denisebmsft — APPROVED** [review]
Thank you @RAJU2529

**Comment by RAJU2529** [comment]
@denisebmsft , Created new PR #7208 ,  added new version 4.18.2111.5-0 in this article, so please verify and merge if correct.

**Pull request merged**
