### PR TITLE
Update services-in-china.md

### PR DESCRIPTION
**Pull request by msbemba**
Made changes to the name of the company throughout the document as it is no longer 21vianet.. It is called Vnet

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/9936

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@SKjerland Please merge this PR. Thanks

**Comment by SKjerland** [comment]
@msbemba @yogkumgit - I've reached out to CELA to get their guidance. We need to confirm whether 21Vianet is keeping their name as is and operating as a division of VNET, or whether they've actually changed their name. If they did change their name, we need to know whether to update it to "Office 365 operated by VNET" or "Office 365 operated by VNET Group". I'm going to close this PR. If CELA tells us to update the name, then we'll need to make a broad update across our entire documentation set--not just this one article. My team will take on that work. I'll go ahead and reply to the customer in GitHub to let them know we're looking into it. Thanks!

**Comment by SKjerland** [comment]
Closing the loop on this. CELA has told us the name is NOT changing. The 21Vianet name should remain in the docs at this time.

**Pull request closed without merging**
