### PR TITLE
Update ediscovery-decryption.md

### PR DESCRIPTION
**Pull request by msbemba**
eDiscovery can unencrypt data that was protected on-premise after the AIP UL client was released so removed the imp note per issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/10095

### CODE REVIEW

**Comment by msbemba** [comment]
issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/10095

**Comment by msbemba** [comment]
@JohanFreelancer9 please copy review

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@robmazz Please merge this PR. Thanks

**Comment by yogkumgit** [comment]
Closing as per the comment in #10095

**Pull request closed without merging**
