### PR TITLE
Update endpoint-dlp-learn-about.md

### PR DESCRIPTION
**Pull request by msbemba**
Added a line stating that one needs to Turn ON device monitoring for to use Endpoint DLP

### CODE REVIEW

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/7298

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@chrfox Please merge this PR, Thanks

**Comment by chrfox** [comment]
Why is this change being suggested?

**Comment by msbemba** [comment]
@chrfox For customers who start out with Defender for Endpoint and want to use Endpoint DLP, it's not mentioned that device monitoring needs to be turned.

Related to issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/7298

Thanks
Sri

**Pull request merged**
