### PR TITLE
Create orgsettings_anonymous.png

### PR DESCRIPTION
**Pull request by msbemba**
The old screenshot was incorrect or has changed

### CODE REVIEW

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/3416

**Comment by msbemba** [comment]
@JohanFreelancer9  please copy review

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@Sirkkuw Please merge this PR. Thanks

**Comment by Sirkkuw** [comment]
@yogkumgit please do not merge these changes. I have updated the file recently.

**Comment by msbemba** [comment]
Thank you @Sirkkuw .

**Pull request closed without merging**
