### PR TITLE
Update linux-preferences.md

### PR DESCRIPTION
**Pull request by msbemba**
Checked and enabled is by default for behavior monitoring. Changed the document accordingly.

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/8546

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@mjcaparas Please merge this PR. thanks

**Comment by mjcaparas** [comment]
Rejecting this. PM has informed me default value is disabled.

**Comment by msbemba** [comment]
@mjcaparas Thank you. I have reopened the PR and updated the default value to disabled.

**Comment by yogkumgit** [comment]
@mjcaparas Please merge this PR. thanks

**Pull request merged**
