### PR TITLE
Update device-onboarding-offboarding-macos-intune.md

### PR DESCRIPTION
**Pull request by msbemba**
Added sysext.mobileconfig to the list of profiles that needs to be created.

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/7428

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@chrfox Please merge this PR. Thanks

**Comment by chrfox** [comment]
why is change being suggested?  This requested change conflicts with the guidance and review that the dev who wrote this code gave.

**Comment by msbemba** [comment]
Thank you, Chris. I see what you are saying. The tip states that .mobileconfig files can be individually downloaded or in a single combined file. I'll update the user who requested the change.

The reason for this request was that the sysext.mobileconfig is needed for the com.microsoft.wdav.epsext | UBF8T346G9 bundle to be identified.
Thanks
Sri

**Pull request closed without merging**
