### PR TITLE
Update dns-records-for-office-365-gcc-high.md

### PR DESCRIPTION
**Pull request by msbemba**
Added a related article (adding a new domain to an existing o365 tenant)

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/3597

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by dzazzo** [comment]
Ordinarily, I'd say yes, but on this one - no, this will add more confusion.  Domain management is not currently available within the Office 365 Admin portals for GCC High and DOD.  Hopefully will change soon, but not yet.

**Comment by dzazzo-msft** [comment]
No, this should not be approved.  Domain management is not currently available within the Office 365 Admin portals for GCC High and DOD. Hopefully will change soon, but not yet.

**Comment by msbemba** [comment]
@dzazzo-msft Thank you for the update. Ill close the PR.

**Pull request closed without merging**
