### PR TITLE
Update prevent-changes-to-security-settings-with-tamper-protection.md

### PR DESCRIPTION
**Pull request by msbemba**
Tamper Protection appears to be part of P1 under Next Gen Protection.

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/7307

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@denisebmsft Please merge this PR. Thanks

**Comment by denisebmsft** [comment]
@yogkumgit @msbemba I am confirming the requirements to manage tamper protection in an organization. I think it's not supported; MDE Plan 2 is required. But I am doublechecking that.

**Pull request merged**
