### PR TITLE
Update activity-reports.md

### PR DESCRIPTION
**Pull request by msbemba**
Fixed incorrect grammar.

### CODE REVIEW

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/6589

**Comment by msbemba** [comment]
@JohanFreelancer9 Please review

**Review by Cheeftainb — COMMENTED** [review]
Thank you for making the change, I assume it will take a few days until it takes effect, because I just checked after deleting cache and cookies + on a mobile phone that has never visited this page in the past, and the grammar issue is still present.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@tiburd Please merge this PR. Thanks

**Pull request merged**
