### PR TITLE
Update rule name title in attack-surface-reduction-rules.md

### PR DESCRIPTION
**Pull request by fbrettnich**
Links in Microsoft 365 Defender Portal already redirect to the new title link and are not discoverable

### CODE REVIEW

**Comment by yogkumgit** [comment]
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@jweston-1 Please merge this PR. Thanks

**Comment by jweston-1** [comment]
unable to 'git checkout' to resolve conflicts.

**Comment by yogkumgit** [comment]
@tiburd

**Comment by jweston-1** [comment]
I tried last week and again this morning, but have repeatedly received error messages.

Hovering over the branch name, 'fbrettnich:public' renders a message indicating 'this branch has been deleted'

***@***.***

**Comment by traya1** [comment]
Closing PR as the source fork that contained the proposed changes has been deleted.

If the changes are valid, resubmit via a new PR.

Thanks!

**Comment by fbrettnich** [comment]
> Closing PR as the source fork that contained the proposed changes has been deleted.
> 
> If the changes are valid, resubmit via a new PR.
> 
> Thanks!

I don't think that a deleted fork is a big problem... for the few changes it could have been solved otherwise. After 4 months of waiting, I delete the fork at some point

Feel free to fix it yourself :)

**Pull request closed without merging**
