### PR TITLE
Update add-licenses-using-product-key.md

### PR DESCRIPTION
**Pull request by msbemba**
Updated the document to reflect that the option to enter product key shows up only when you have an existing prepaid sub

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/9258

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@cmcatee-MSFT Please merge this PR. Thanks

**Comment by waded** [comment]
I'm still working with Microsoft billing & subscription support on this case and can't say certainly how it's supposed to work, but I don't feel like the two words added here close the hole I fell into. It seems likely (but I don't know this for sure) that NONE of this article is useful without an existing prepaid subscription, so that should be a preface on the entire article, rather than just this one sentence.

i.e. I'd update the title to "Add licenses to or extend an existing prepaid subscription by using a Microsoft 365 product key" and would reiterate in the introductory paragraph with some sort of tip/info formatting that this only applies to existing prepaid subscriptions, not commercial or whatever the other categories are.

**Review by cmcatee-MSFT — APPROVED** [review]

**Comment by yogkumgit** [comment]
@tiburd Please merge this PR, as author has approved the changes. Thanks

**Comment by tiburd** [comment]
@cmcatee-MSFT 
Hi,
Please fix the file conflict.
Thanks!

**Comment by cmcatee-MSFT** [comment]
Need to make other changes to this article, so I'm closing this PR and will include the changes in the internal PR.

**Comment by cmcatee-MSFT** [comment]
Article was retired and content moved here: https://learn.microsoft.com/en-us/microsoft-365/commerce/licenses/buy-licenses?view=o365-worldwide#add-licenses-to-a-prepaid-subscription-by-using-a-microsoft-365-product-key

**Pull request closed without merging**
