### PR TITLE
Update sensitivity-labels-sharepoint-default-label.md

### PR DESCRIPTION
**Pull request by Kausd**
Customers should know the limitations from the security point of view as well.

### CODE REVIEW

**Comment by yogkumgit** [comment]
@JohanFreelancer9

**Comment by JohanFreelancer9** [comment]
@yogkumgit, I am not clear on the content of this addition. Perhaps the document owner can help?

**Comment by yogkumgit** [comment]
@cabailey Please review the PR, if you find it suitable please merge this PR. Thanks

**Comment by cabailey** [comment]
The PM owner for this feature has asked for this PR to be rejected and closed, and has communicated internally with @Kausd. For future reference, an internal communication would have been better than a PR here.

**Pull request closed without merging**
