### PR TITLE
Update tenant-allow-block-list.md

### PR DESCRIPTION
**Pull request by msbemba**
Checked and found that the allow option does not exist anymore (apart from spoof). There is option only to block

reference  articles
https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/allow-block-email-spoof?view=o365-worldwide#create-block-sender-entries
https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/allow-block-urls?view=o365-worldwide
https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/allow-block-files?view=o365-worldwide

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by chrisda** [comment]
Unassigning from me and assigning to @RatulaC

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@RatulaC Please merge this PR. Thanks

**Comment by chrisda** [comment]
Closing. I just completed massive updates to these topics, which nullifies the need for these changes.

**Pull request closed without merging**
