### PR TITLE
Update buy-licenses.md

### PR DESCRIPTION
**Pull request by msbemba**
added a line "See Add licenses to a subscription paid for using a product key. When you add an extra product key, this will also allow you to reduce the existing license count if you wish."

### CODE REVIEW

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/4123

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@cmcatee-MSFT Please merge this PR. Thanks

**Comment by cmcatee-MSFT** [comment]
Per PM, no change needed at this time.

**Pull request closed without merging**
