### PR TITLE
Update audit-log-search.md with Microsoft Defender Experts

### PR DESCRIPTION
**Pull request by hyukjinkwonMicrosoft**
Add Microsoft Defender Experts audits and their record types to document

### CODE REVIEW

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by hyukjinkwonMicrosoft** [comment]
@JohanFreelancer9 could you assist me in merging the PR? Thank you

**Comment by JohanFreelancer9** [comment]
> @JohanFreelancer9 could you assist me in merging the PR? Thank you

@yogkumgit, could you please assist? Thanks.

**Comment by yogkumgit** [comment]
@robmazz Please merge this PR. Thanks

**Comment by robmazz** [comment]
@yogkumgit - FYI, discussed with PM, as internal stakeholder - he is opening the content request in our ADO per our process

**Pull request closed without merging**
