### PR TITLE
Removed "Number of Groups a user can be a member of" from office-365-groups.md

### LINKED ISSUE #2349: Number of Groups a user member of
In this article it was mentioned, user can be member of 1000 groups. However the below article says a user can be part of any number of groups. Which one is correct?

https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/azure-subscription-service-limits#active-directory-limits

### PR DESCRIPTION
**Pull request by dariomws**
Closes https://github.com/MicrosoftDocs/microsoft-365-docs/issues/2349.

Same as https://github.com/MicrosoftDocs/microsoft-365-docs/issues/2382.

"A user can be a member of any number of groups":
https://docs.microsoft.com/azure/active-directory/users-groups-roles/directory-service-limits-restrictions

@MikePlumleyMSFT Could you kindly confirm? Thanks!

### CODE REVIEW

**Comment by dariomws** [comment]
@msbemba I think this row is wrong. I'm proposing the removal, let's see if it gets approval.

Thanks!

**Comment by dariomws** [comment]
@MikePlumleyMSFT could you kindly review/confirm this PR? Thanks!

**Comment by dariomws** [comment]
@MikePlumleyMSFT could you kindly review/confirm this PR? Thanks!

**Comment by msbemba** [comment]
@MikePlumleyMSFT  We have received a confirmation from Arun and Mike that there is no limit. Could you please approve and merge this PR?

Thanks
Sri

**Pull request merged**
