### PR TITLE
Update customize-the-app-launcher.md

### PR DESCRIPTION
**Pull request by msbemba**
removed add app launcher tiles to the navigation bar ([learn more](https://support.microsoft.com/office/eb34a21b-52fa-4fbf-a8d5-146132242985)). as there seems to be no option to do this currently.

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/6885

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@twernermsft Please merge this PR. Thanks

**Comment by yogkumgit** [comment]
@twernermsft Gentle reminder

**Pull request merged**
