### PR TITLE
Change Localization Priority value

### PR DESCRIPTION
**Pull request by TinaMcN**
The localized topics get very high page views, let's change the value to "Priority" so that it will always be human translated.

### CODE REVIEW

**Comment by yogkumgit** [comment]
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@pebaum Please merge this PR. Thanks

**Comment by TinaMcN** [comment]
@denisebmsft pebaum is on leave, can you assign to someone else?

**Comment by yogkumgit** [comment]
@TinaMcN Thanks, can you please suggest who can take care of it.

**Comment by TinaMcN** [comment]
@denisebmsft do you know who can cover this in pebaum's absence?

**Pull request merged**
