### PR TITLE
Update comprehensive-guidance-on-linux-deployment.md

### PR DESCRIPTION
**Pull request by EdgarPMIA**
I confirmed internally that the consideration to avoid inspecting SSL traffic for Defender for Endpoint mentioned here in the Linux article, it is a consideration for all supported OS, Windows, Linux and MacOS. I thought of adding a note to the article to make it clear for customers.
If the note can be highlighted with the purple-ish color we use for notes, that'll be great. Is that something I need to do?

### CODE REVIEW

**Comment by siosulli** [comment]
@EdgarPMIA what do you mean by 'consideration' could we say recommendation? so something like this: 

Note: Verifying traffic isn't being inspected by SSL inspection (TLS inspection) is a general recommendation for Defender for Endpoint across all supported operating systems (Windows, Linux, and MacOS).

Thanks!
Sinead

**Comment by EdgarPMIA** [comment]
@siosulli Yes, it is a recommendation/advice to avoid using SSL inspection because it can break the communication between the endpoint and MDE cloud service. But let's go with recommendation and highlight that in that purple-ish color we use for notes on our articles. Btw, should I do that or is that something you do? I'm just asking to understand who does that bit ;-) thanks!

**Comment by siosulli** [comment]
Thanks @EdgarPMIA! 

Is this okay: 

> [!NOTE]
> It's generally recommended that traffic isn't inspected by SSL inspection (TLS inspection) for Defender for Endpoint across all supported operating systems (Windows, Linux, and MacOS).

If you put a note in the format above it will appear in the purple box! I have made the change this time but you can go ahead and do it in the future :).

**Comment by EdgarPMIA** [comment]
@siosulli Awesome Sinead, thanks for letting me know. I'll take that into consideration for future updates!!

But can you reword it a bit, like this:
It is generally recommended that traffic for Defender for Endpoint is not inspected by SSL inspection (TLS inspection). This applies to all supported operating systems (Windows, Linux, and MacOS).

Thanks!

**Comment by EdgarPMIA** [comment]
@siosulli Ah Sinead, fairly new to the process. This is my first article edit, but wanted to confirm what's the next step from here? Do I need to do anything else? or just wait for all the checks to be marked as "passed" and that's it? thanks!

**Comment by siosulli** [comment]
@EdgarPMIA - thanks, I have made your updates! 

That's all you need to do. I will look after merging it. There seems to be some build issues but they will be sorted soon I'm sure. 

Thanks so much for taking time to make the updates!

**Comment by EdgarPMIA** [comment]
@siosulli Hi, just to have an idea, after my changes are merged in the article, how long before is published? thank you!! and really happy to participate and contribute to improve our great articles!!

**Comment by siosulli** [comment]
@EdgarPMIA  - your updates will be live after 4:30 PM PST time today.

Look forward to working again soon!

**Pull request merged**
