### PR TITLE
Update report-monitor-microsoft-defender-antivirus.md

### PR DESCRIPTION
**Pull request by msbemba**
removed update compliance as it has been removed. Reference :- https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/troubleshoot-reporting?view=o365-worldwide

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/6320

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@denisebmsft Please merge this PR. Thanks

**Review by denisebmsft — APPROVED** [review]
Thank you @msbemba

**Pull request merged**
