### PR TITLE
Update office-365-worldwide-endpoints.md

### PR DESCRIPTION
**Pull request by pedossan**
For SharePoint this page shows:
tenant.sharepoint.com, tenant-my.sharepoint.com

But JSON lists:

"urls": [
"*.sharepoint.com"
],

Page update needed, so creating a PR

Regards

### CODE REVIEW

**Comment by pandrew1** [comment]
This is not a valid PR since this page is generated from the JSON web service referenced

**Comment by pedossan** [comment]
> This is not a valid PR since this page is generated from the JSON web service referenced

Any idea then why it does not get updated?

**Comment by yogkumgit** [comment]
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by JoeDavies-MSFT** [comment]
I cannot merge this PR because these lists are maintained internally. I have forwarded this issue to the product team who maintains these lists for their review.

**Pull request closed without merging**
