### PR TITLE
Update host-firewall-reporting.md

### PR DESCRIPTION
**Pull request by msbemba**
Made changes to the images as they were not rendered properly.

Also added details that Security and global admin can no host the firewall reporting.

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

Note that the images were not rendered properly. Let me know if this looks ok.

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/8350

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@denisebmsft Please merge this PR. Thanks

**Review by denisebmsft — APPROVED** [review]
Thank you @msbemba

**Pull request merged**
