### PR TITLE
Update ome-version-comparison.md

### PR DESCRIPTION
**Pull request by msbemba**
Multiple branding templates is only available in Microsoft Purview Advanced Message Encryption

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/8730

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@KCCross Please merge this PR. Thanks

**Comment by yogkumgit** [comment]
@KCCross Gentle reminder

**Comment by yogkumgit** [comment]
Closing as per the comment in #8730

**Pull request closed without merging**
