### PR TITLE
Update track-and-respond-to-emerging-threats-with-campaigns.md

### PR DESCRIPTION
**Pull request by nidhalferchichi**
There is no french page for this Document.
https://learn.microsoft.com/fr-ca/microsoft-365/security/office-365-security/step-by-step-guides/track-and-respond-to-emerging-threats-with-campaigns?view=o365-worldwide

Point to the same document in French.
I am not sure how you guys translate documents.
Thank you.

### CODE REVIEW

**Comment by yogkumgit** [comment]
@tiburd Please help

**Comment by tiburd** [comment]
Thank you for submitting this localization issue.

I submitted a translation bug: [341286](https://dev.azure.com/GlobalCollaborationService/Global%20Collaboration%20Service%20Project/_workitems/edit/341286)

I'm closing this PR because the Global Services team will handle it from here.

**Comment by tiburd** [comment]
Reported as fixed.

**Comment by nidhalferchichi** [comment]
Hello, Sorry for asking.
 
Did this issue cannot be considered as contribution ?
My name will not be added as contributor for this one ?

**Pull request closed without merging**
