### PR TITLE
Update about-admin-roles.md

### PR DESCRIPTION
**Pull request by msbemba**
The Name service admin has been changed to service support admin (checked in the admin center). Changed the role name in the document as well.

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/3003

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@kwekuako please merge this PR. Thanks.

**Comment by msbemba** [comment]
@kwekuako The document has been updated via another PR so this can be closed.

**Pull request closed without merging**
