### PR TITLE
Update updates.md

### PR DESCRIPTION
**Pull request by ChrisSweeneyMSFT**
Isn't the quality update frequency 7 days for broad now? :)

### CODE REVIEW

**Comment by yogkumgit** [comment]
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@jaimeo Please merge this PR. Thanks

**Comment by yogkumgit** [comment]
@jaimeo Gentle reminder

**Comment by jaimeo** [comment]
This was fixed in a separate PR last week.

**Pull request closed without merging**
