### PR TITLE
Update scheduler-setup.md

### PR DESCRIPTION
**Pull request by DanijelkMSFT**
link to scheduler pricing was broken I added the correct one.
wrong --> https://www.microsoft.com/microsoft-365/meeting-scheduler-pricing
working --> https://www.microsoft.com/en-us/microsoft-365/meeting-scheduler-pricing

### CODE REVIEW

**Comment by yogkumgit** [comment]
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

**Review by JohanFreelancer9 — COMMENTED** [review]
@DanijelkMSFT - I have tested it and the old link works fine. We specifically remove the locales from Microsoft docs. Could you please check again? Many thanks.

**Comment by DanijelkMSFT** [comment]
@JohanFreelancer9  - strange yes still getting error opening https://www.microsoft.com/microsoft-365/meeting-scheduler-pricing 
--> https://www.microsoft.com/library/errorpages/smarterror.aspx?correlationId=YhKRnG9tmUG9EETU.0.4.0 
screenshot attached
Errorpage

**Review by JohanFreelancer9 — APPROVED** [review]
@DanijelkMSFT - really strange. In that case, I'll approve the copy. Many thanks for the submission.

**Comment by yogkumgit** [comment]
@JoanneHendrickson Please merge this PR. Thanks

**Comment by JoanneHendrickson** [comment]
@DanijelkMSFT   @yogkumgit   This release of Scheduler is currently only available in English, and the licensing page for Scheduler has not been localized to any other language. That's why the link is broken if you have your language set to anything other then English.  Normally we remove the locale for the link, but in this case we need to retain it.  I will add an alert about availability to the content.

**Pull request merged**
