### PR TITLE
Update use-dkim-to-validate-outbound-email.md

### PR DESCRIPTION
**Pull request by msbemba**
Changed the enabled Parameter to true in order to enable DKIM

### CODE REVIEW

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/5497

**Comment by msbemba** [comment]
@JohanFreelancer9 please copy review

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by hudish** [comment]
@MSFTTracyP I shared my notes internally on this change, please pause and recheck: this change may be conflicting with overall article guidance (create new DKIM config in a disabled state, verify, _then_ enable)

**Comment by msbemba** [comment]
@hudish That makes sense. I'll cancel the PR and explain to the user.

Thank you.

**Pull request closed without merging**
