### PR TITLE
fix(links): Fix article links at bottom of Manage Protected Devices page

### PR DESCRIPTION
**Pull request by jmeridth**
[Manage protected devices with Microsoft 365 Business Premium](https://learn.microsoft.com/en-US/microsoft-365/business/manage-protected-devices).

Two of the links at the bottom 404 Page Not Found currently.

Can't replace third link `Add a managed device` aka `m365bp-app-protection-settings-for-android-and-ios.md` because it was "yanked" out [here](https://github.com/MicrosoftDocs/microsoft-365-docs/commit/f1a81d11fb327e5d1adfe53899cf0056081a4709) on 9/14/22.  I've tried to find where it was redone or replaced with no joy.

Signed-off-by: jmeridth <jmeridth@gmail.com>

### CODE REVIEW

**Review by JohanFreelancer9 — APPROVED** [review]
Copy review.

**Comment by jmeridth** [comment]
@denisebmsft could you please take a look at this PR?  I ask because you have made changes to this page previously.  Thank you in advance.  Cheers.

**Comment by jmeridth** [comment]
@efrene can you please take a look at this PR? Do I need to make any changes? Thanks /cc @denisebmsft

**Comment by jmeridth** [comment]
bump @efrene @denisebmsft

**Pull request merged**
