### PR TITLE
Azure DevOps rebranding

### PR DESCRIPTION
**Pull request by gewarren**
VSTS -> Azure DevOps Services renaming

### CODE REVIEW

**Review by Jominana — APPROVED** [review]

**Comment by jitojo** [comment]
> If this content applies to both VSTS and TFS, it should say Azure DevOps and TFS.
This only applys to the Cloud Service and all 5 offerings.

**Comment by kasangi** [comment]
The brand guidance we have for docs is to use “Azure DevOps Services and TFS” not “Azure DevOps and TFS.”


________________________________

**Comment by gewarren** [comment]
@kasangi Your original comment said "If this content applies to both VSTS and TFS, it should say Azure DevOps and TFS", so I'm a bit confused. Is it okay if we merge this now and we can refine it afterwards if necessary?

**Comment by jitojo** [comment]
@gewarren please let me know if there are any other questions. I think we are ready to push this through. 

Thanks for your help with this change.

**Comment by gewarren** [comment]
#sign-off

**Comment by gewarren** [comment]
@JGruszczyk Could you help us get this PR merged? I'm not sure what the process is for this repo. Thanks!

**Comment by gewarren** [comment]
Opened in the private repo as https://cpubwin.visualstudio.com/_git/microsoft-365/pullrequest/11447?_a=overview.

**Pull request closed without merging**
