### PR TITLE
Update create-dns-records-at-any-dns-hosting-provider.md

### PR DESCRIPTION
**Pull request by msbemba**
MX record to verify domain cannot be 0. it needs to be a large value not used already.

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/5486

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@scotvidican Please merge this PR. Thanks

**Comment by yogkumgit** [comment]
@scotvidican Gentle reminder.

**Pull request merged**
