### PR TITLE
Update classifier-learn-about.md

### PR DESCRIPTION
**Pull request by edwinchan-microsoft**
Updated supported file types for harassment, profanity, threat classifiers.

### CODE REVIEW

**Comment by edwinchan-microsoft** [comment]
@chrfox please see this PR, Thanks

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@chrfox Please merge this PR. Thanks

**Comment by edwinchan-microsoft** [comment]
Hi @***@***.***> could these changes be merged and published please?

Thanks,
Edwin

**Comment by edwinchan-microsoft** [comment]
merged

From: Edwin Chan ***@***.***>
Sent: Monday, February 7, 2022 7:53 AM
To: MicrosoftDocs/microsoft-365-docs ***@***.***>; Christopher J Fox (OFFICE) ***@***.***>
Subject: RE: [MicrosoftDocs/microsoft-365-docs] Update classifier-learn-about.md (PR #7543)

Hi @***@***.***> could these changes be merged and published please?

Thanks,
Edwin

**Pull request merged**
