### PR TITLE
Update mailbox-usage.md

### PR DESCRIPTION
**Pull request by msbemba**
Corrected the navigation for Mailbox usage report. the options have changed with the new admin center.

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/3558

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@kwekuako Please merge this PR. Thanks.

**Comment by msbemba** [comment]
issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/3599 and https://github.com/MicrosoftDocs/microsoft-365-docs/issues/3609 is also addressed in this PR as it is the same document.

**Pull request merged**
