### PR TITLE
Update information-barriers-policies.md

### PR DESCRIPTION
**Pull request by msbemba**
Made changes to the PS cmdlet from Connect-azureAd to   Connect-AzAccount  as it uses cmdlets from Az PowerShell modules. running it with connect-azuread throws an error  
Get-AzADServicePrincipal : The term 'Get-AzADServicePrincipal' is not recognized as the name of a cmdlet,

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/3374

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@chrfox Please merge this PR. Thanks.

**Comment by chrfox** [comment]
engineering review requested

**Comment by robmazz** [comment]
@chrfox  - I know we've turned over these topics, did the PG respond and approve?

**Pull request merged**
