### PR TITLE
added  windows 11 admx templates link

### PR DESCRIPTION
**Pull request by RAJU2529**
this is my own, after reading this article, I added windows 11 admx templates download link

### CODE REVIEW

**Comment by RAJU2529** [comment]
@denisebmsft , Please verify and merge PR #8621 . i added windows 11 admx templates link to below article
**https://docs.microsoft.com/microsoft-365/security/defender-endpoint/detect-block-potentially-unwanted-apps-microsoft-defender-antivirus?view=o365-worldwide**

**Comment by yogkumgit** [comment]
@JohanFreelancer9

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by RAJU2529** [comment]
@yogkumgit Sometimes I get   **Update Branch** Why this is happening?

**Review by denisebmsft — APPROVED** [review]
Thank you @RAJU2529 @yogkumgit @JohanFreelancer9

**Pull request merged**
