### PR TITLE
Update admin-support.md

### PR DESCRIPTION
**Pull request by StuEwen**
@jaimeo to review and schedule changes

### CODE REVIEW

**Comment by jaimeo** [comment]
@traya1 this is in the same situation as the other one I sent you. Different date: needs to go live 7/21.

**Comment by traya1** [comment]
Not a problem, I'll help guide the transition over to the internal repos.

**Comment by yogkumgit** [comment]
@jaimeo and @traya1 Please resolve. Thanks

**Comment by traya1** [comment]
Hi @StuEwen, 

Can you contact me on Teams so I can help you move the changes to the internal repos? Thanks!

**Pull request closed without merging**
