### PR TITLE
Update to PowerShell command $true is not a parameter

### PR DESCRIPTION
**Pull request by jerryyasir**
Changed from Get-InformationBarrierPoliciesApplicationStatus -All $true to Get-InformationBarrierPoliciesApplicationStatus -All as -All is now a switch.  Thanks,

### CODE REVIEW

**Comment by yogkumgit** [comment]
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@chrfox Please merge this PR. Thanks.

**Comment by chrfox** [comment]
investigating with PG

**Comment by chrfox** [comment]
merged

**Pull request merged**
