### PR TITLE
Update customer-key-overview.md

### PR DESCRIPTION
**Pull request by sathana87**

### CODE REVIEW

**Comment by yogkumgit** [comment]
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

**Review by JohanFreelancer9 — COMMENTED** [review]
I'm not sure what the intent is of this PR.

**Comment by yogkumgit** [comment]
@sathana87 Please explain the reason of creating this PR. Thanks

**Comment by yogkumgit** [comment]
@sathana87 Gentle reminder

**Comment by yogkumgit** [comment]
@sathana87 No reply. Closing it.

**Pull request closed without merging**
