### PR TITLE
Update manage-auto-claim-policies.md

### PR DESCRIPTION
**Pull request by msbemba**
Only Global admin is able to turn on or off. the other admin dont see this option per testing

### CODE REVIEW

**Comment by msbemba** [comment]
Issue#(https://github.com/MicrosoftDocs/microsoft-365-docs/issues/7183)

**Comment by yogkumgit** [comment]
@cmcatee-MSFT Please merge this PR. Thanks.

**Comment by yogkumgit** [comment]
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@cmcatee-MSFT Please merge this PR. Thanks

**Comment by tiburd** [comment]
Changes approved by tech reviewer via email. Merging this PR.

**Pull request merged**
