### PR TITLE
Update limited-periodic-scanning-microsoft-defender-antivirus.md

### PR DESCRIPTION
**Pull request by msftsichrist**
Rewrite the guidance to enterprises to make it explicit that this feature is not supported in Enterprise environments, and that there is no way to manage it or automate turning it on or off via group policy.

### CODE REVIEW

**Comment by denisebmsft** [comment]
@msftsichrist thank you so much for this pull request. As soona s you sign the CLA, I'll get it merged. I appreciate your help!

**Comment by msftsichrist** [comment]
@microsoft-github-policy-service agree company="Microsoft"

**Comment by msftsichrist** [comment]
@denisebmsft Just checking, I think I did the CLA correctly (it seems to indicate such) but not sure as I responded to the bot via email, please let me know if there's anything further to get this change made.

**Comment by denisebmsft** [comment]
> @denisebmsft Just checking, I think I did the CLA correctly (it seems to indicate such) but not sure as I responded to the bot via email, please let me know if there's anything further to get this change made.

Thank you! Merged!

**Pull request merged**
