### PR TITLE
Update configure-exchange-server-for-hybrid-modern-authentication.md

### PR DESCRIPTION
**Pull request by pamcdo**
I believe the EvoSTS object created by the HCW at one time just named the object 'EvoSTS' so the powershell command to look it up may have worked at one point. That is no longer the case. The object is made with a name of 'EvoSts - GUID' so an 'eq' doesn't work anymore.

I changed this to 'like' with a wildcard on the end and then output to a table to show the full name and the enabled status.

HMA like

### CODE REVIEW

**Comment by pamcdo** [comment]
That's not the one I meant to paste in, here's the actual example

hma like 2

**Comment by pamcdo** [comment]
I also noticed, when moving on to the next step in the doc, that the enablement is done by this command

Set-AuthServer -Identity EvoSTS -IsDefaultAuthorizationEndpoint $true

Which isn't going to work via a copy and paste since it's no longer named just EvoSTS. This will probably require a bigger edit to reflect the change that appears to have happened in the HCW.

**Comment by yogkumgit** [comment]
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@kelleyvice-msft Please merge this Pr. Thanks.

**Comment by pamcdo** [comment]
@kelleyvice-msft bump?

**Comment by pamcdo** [comment]
@kelleyvice-msft one more bump?

**Comment by pamcdo** [comment]
@kelleyvice-msft Just checking on this again

**Comment by LauraWi** [comment]
@dstrome  -- Another item requiring review from Exchange perspective. Thanks.

**Pull request merged**
