### PR TITLE
Update set-up.md

### PR DESCRIPTION
**Pull request by neillnolann**
[Microsoft365.com/setup](https://soft365setup.com/)
- [Set up Microsoft 365 Business Basic](setup-business-basic.md)
- [Set up Microsoft Business Standard](setup-business-standard.md)
- [Set up Microsoft 365 Business Premium](../../business/set-up.md)
- [Set up Microsoft 365 Apps for business](setup-apps-for-business.md)

### CODE REVIEW

**Comment by yogkumgit** [comment]
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by pebaum** [comment]
no way. this Microsoft365.com/setup link actually links to a phishing site

**Comment by lantrix** [comment]
> no way. this Microsoft365.com/setup link actually links to a phishing site

He managed to actually get a change in here #4175 which is now live on https://docs.microsoft.com/en-us/microsoft-365/admin/setup/setup?view=o365-worldwide

I've followed through and it is a fake "office licence keydownloader" and when I call their support line he asked me to setup a log me in download on my windows PC.

@pebaum I've seen @JohanFreelancer9 and @yogkumgit both request and approve the other PRs for this Neil user inserting the spammy/phishing links such as in #4175 - **how are they approving this phishing crap?!**

I will report the Github account and domains to their registrars.

I've put in #4531 to reverse the now live phishing link on the /docs.microsoft.com

**Comment by adirdidi** [comment]
The phishing link was removed. @lantrix thank you for your awareness.

**Pull request closed without merging**
