### PR TITLE
Update autoexpanding-archiving.md

### PR DESCRIPTION
**Pull request by msbemba**
Added m365 Apps for enterprise and business as auto-expanding archiving works

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/7985

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by cabailey** [comment]
@JohanFreelancer9  Since this in the M365 content set, I think we should list M365 apps first?

**Review by JohanFreelancer9 — CHANGES_REQUESTED** [review]
@msbemba - could you please move the M365 apps to the top of the list in accordance with @cabailey's request? Unfortunately, I am not able to edit lines outside the PR. Many thanks.

**Comment by msbemba** [comment]
@JohanFreelancer9 I have made the changes as suggested.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@cabailey Please merge this PR. Thanks

**Comment by cabailey** [comment]
#sign-off  Merging

**Pull request merged**
