### PR TITLE
Update dlp-chrome-get-started.md

### PR DESCRIPTION
**Pull request by msbemba**
tested with no admin rights and When set to NO it works

### CODE REVIEW

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/6100

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@chrfox Please merge this Pr. Thanks

**Comment by chrfox** [comment]
checking with engineering

**Pull request merged**
