### PR TITLE
Update add-storage-space.md

### PR DESCRIPTION
**Pull request by msbemba**
Verified M365 F3 also has the sharepoint extra file storage option. and added the information to the document.

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by msbemba** [comment]
issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/7707

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@cmcatee-MSFT Please merge this PR. Thanks

**Comment by yogkumgit** [comment]
@cmcatee-MSFT Gentle reminder.

**Pull request merged**
