### PR TITLE
Update m365d-enable.md

### PR DESCRIPTION
**Pull request by msbemba**
Removed the endpoint section as  Incidents, Hunting, Action center, or Threat analytics are under Home

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/4999

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@lomayor Please merge this PR. Thanks

**Comment by lomayor** [comment]
Resolved conflicts and merged.

@Dansimp -- please help find a new owner for this topic. Thanks!

**Pull request merged**
