### PR TITLE
Update office-365-encryption-for-skype-onedrive-sharepoint-and-exchan…

### PR DESCRIPTION
**Pull request by msbemba**
…ge.md

added reference to SP

### CODE REVIEW

**Comment by msbemba** [comment]
Issue #https://github.com/MicrosoftDocs/microsoft-365-docs/issues/1098

**Review by KCCross — CHANGES_REQUESTED** [review]
SSL still or TLS 1.2-only now?

**Comment by msbemba** [comment]
> SSL still or TLS 1.2-only now?

AFAIK it still uses SSL/TLS. Let me know if you would like to me correct this in the document.

**Comment by mypil** [comment]
@KCCross - Please assist to respond to the query of msbemba so he can make the changes to this PR if needed. Thank you.

**Comment by KCCross** [comment]
Samson - please confirm TLS 1.2-only.

**Comment by samschan-ms** [comment]
We are following what EXO does, nothing different than regular email.

**Review by samschan-ms — APPROVED** [review]
We follow EXO standard. so from what I know, it's TLS 1.2 (best effort)

**Comment by msbemba** [comment]
> We follow EXO standard. so from what I know, it's TLS 1.2 (best effort)

Thank you. I have made the correction.

**Comment by mypil** [comment]
@KCCross - Recommended changes has been made to this PR. Please assist to review and merge. 

Thank you.

**Pull request merged**
