### PR TITLE
Update change-email-address.md

### PR DESCRIPTION
**Pull request by msbemba**
Added steps to change the user's email address and UPN

### CODE REVIEW

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/1652

**Comment by mypil** [comment]
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by mypil** [comment]
@pebaum - PR has been copy edited and is ready for final review. This is based on issue #1652.

Thank you.

cc: @kenwith

**Comment by pebaum** [comment]
this article is being decommissioned and incorporated into another. closing without merging.

**Pull request closed without merging**
