### PR TITLE
SEO edits for design principles

### PR DESCRIPTION
**Pull request by jdmartinez36**
Edited title per the SEO expert's recommendation.

Added description with keywords.

Edited introduction to include keywords. The reviewer will want to verify that this makes sense, but 'enterprise resource planning' is a high value keyword for this article.

### CODE REVIEW

**Comment by jdmartinez36** [comment]
@DaniHalfin

**Review by samanro — CHANGES_REQUESTED** [review]
I'd differentiate - Kozetta... on security design principles, Ed on networking design prinicples, etc.

**Review by samanro — COMMENTED** [review]
Not sure what "enterprise resource planning" conveys? Are we sure those are the right keywords?

**Comment by jdmartinez36** [comment]
Hi @samanro 

I'm not really sure about the "enterprise resource planning" myself. I can get in touch with the SEO expert who made the recommendation and ask him how that came about. He'll also be taking over these edits in the next day or so, and he might be able to answer directly

**Comment by jdmartinez36** [comment]
@samanro 

Edited image alt tags as requested to differentiate the fields of expertise.

**Review by samanro — CHANGES_REQUESTED** [review]
Need to keep "Microsoft 365 Enterprise" in title, no "enterprise resource planning" for the title. Ok for para below.

**Comment by tuco-ulf** [comment]
@DaniHalfin think this is ready to merge. Title looks changed back.

**Pull request merged**
