### PR TITLE
added new platform update v4.18.2110-5.0

### PR DESCRIPTION
**Pull request by RAJU2529**
I added a new platform update version **4.18.2110-5.0** which is added on 26th October 2021, I verified this 4.18.2110-5.0 version under **Windows 11 RTM build no 22000.282**

here is screenshot
Screenshot 2021-10-28 234842

### CODE REVIEW

**Comment by RAJU2529** [comment]
@e0i please verify this PR #6727

**Comment by yogkumgit** [comment]
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@denisebmsft

**Review by denisebmsft — APPROVED** [review]
Thank you @RAJU2529

**Pull request merged**
