### PR TITLE
Update prevent-changes-to-security-settings-with-tamper-protection.md

### PR DESCRIPTION
**Pull request by msbemba**
Added Windows 10 and Windows 11 Enterprise multi-session as they are to be treated as separate OS editions.

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/7147

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@denisebmsft Please merge this PR. Thanks

**Review by denisebmsft — APPROVED** [review]
Thank you @msbemba

**Pull request merged**
