### PR TITLE
Update alert-policies.md

### PR DESCRIPTION
**Pull request by johnengels**
Updating the alert table to contain the automated investigation information here instead of over in the AIR section.  That way it's one table to update and we avoid doc discrepancies when we make new alerts that have investigations.

### CODE REVIEW

**Comment by johnengels** [comment]
@Dansimp @MSFTTracyP - here is the alert documentation change to incorporate the AIR info.

**Comment by markjjo** [comment]
@johnengels PR merged. Thanks for making these changes.

**Comment by johnengels** [comment]
@markjjo - Two questions:
- how long does it typically take to get items updated?
- when I do a pull request, do I need to close the pull request to get the change into the queue?

**Comment by markjjo** [comment]
@johnengels I will reply with answers in email.

**Pull request merged**
