### PR TITLE
Update dlp-sensitivity-label-as-condition.md

### PR DESCRIPTION
**Pull request by msbemba**
Fixed Typo from "One drive for business" to "OneDrive for Business"

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/2967

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@chrfox Please merge this PR. Thanks.

**Comment by chrfox** [comment]
merged, thanks

**Pull request merged**
