### PR TITLE
Update advanced-hunting-overview.md

### PR DESCRIPTION
**Pull request by msbemba**
Added required admin roles

### CODE REVIEW

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/1704

**Comment by mypil** [comment]
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by mypil** [comment]
@lomayor - PR has been copy edited and is ready for final review. This is based on issue #1704.

Thank you.

cc: @kenwith

**Comment by lomayor** [comment]
@mypil, this is actually documented here:
https://docs.microsoft.com/microsoft-365/security/mtp/mtp-permissions

I suggest adding a link to that in the note instead. That topic covers more information, including how data is scoped by RBAC.

**Comment by mypil** [comment]
@msbemba - please apply the recommended changes from @lomayor 

Thank you!

**Comment by lomayor** [comment]
Thanks, @msbemba & @mypil. Tweaked the text and will now merge.

**Pull request merged**
