### PR TITLE
Typo "**P@ssw0rd**"→"**P\@ssw0rd**"

### PR DESCRIPTION
**Pull request by hyoshioka0128**
Bold with escape characters

https://docs.microsoft.com/en-us/microsoft-365/enterprise/use-powershell-to-perform-an-imap-migration-to-microsoft-365?view=o365-worldwide

### CODE REVIEW

**Comment by yogkumgit** [comment]
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@JoeDavies-MSFT Please merge this PR. Thanks.

**Comment by JoeDavies-MSFT** [comment]
@yogkumgit There are two more instances of **P@ssw0rd** in the current article. Can you correct them as well in this PR? Thanks

**Comment by JoeDavies-MSFT** [comment]
@yogkumgit Correction: There are two more instances of "**P\@ssw0rd**" in the current article.

**Comment by JoeDavies-MSFT** [comment]
@yogkumgit Correction: There are two more instances of ****P@ssw0rd**** in the current article.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@hyoshioka0128 Please review again and see the comment made by @JoeDavies-MSFT Thanks.

**Comment by hyoshioka0128** [comment]
@yogkumgit - Fixed the remaining two "P\@ssw0rd". Thanks.

**Pull request merged**
