### PR TITLE
update insider-risk-management-settings

### PR DESCRIPTION
**Pull request by msbemba**
Updated Png files for  risk insider file

### CODE REVIEW

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/2857

**Comment by msbemba** [comment]
@JohanFreelancer9  Please copy review

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@robmazz Please merge this PR. Thanks.

**Comment by robmazz** [comment]
@msbemba - If you have updated screenshots for insider risk management topics (or for any other feature in the future), please send directly to me for review. Much easier to handle outside of submitting through the public repo process. Happy to meet to discuss if needed.

**Comment by msbemba** [comment]
@robmazz Thank you, Robert. Are we changing the screenshots in the backend or should I leave this branch intact?

I work on most of these docs and would like to meet and discuss anytime you are available.

Thanks
Sri

**Pull request closed without merging**
