### PR TITLE
Update search-the-audit-log-in-security-and-compliance.md

### PR DESCRIPTION
**Pull request by msbemba**
Since the table has been removed, updated the document accordingly.

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by msbemba** [comment]
issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/9988

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@robmazz Please merge this PR. Thanks

**Comment by yogkumgit** [comment]
@robmazz Gentle reminder

**Comment by landryr888** [comment]
# #

**Comment by yogkumgit** [comment]
Closing as per the comment in #9988

**Pull request closed without merging**
