### PR TITLE
Update activate-defender-rbac.md

### PR DESCRIPTION
**Pull request by msbemba**
Added a  note on availability to GCC

Fixes https://github.com/MicrosoftDocs/microsoft-365-docs-pr/issues/23596

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@siosulli Please merge this PR. Thanks

**Comment by yogkumgit** [comment]
@siosulli Gentle reminder.

**Comment by denisebmsft** [comment]
Moved to defender-docs-pr repo https://github.com/MicrosoftDocs/defender-docs-pr/pull/195

**Pull request closed without merging**
