### PR TITLE
add missing --value in linux mdatp commands table

### PR DESCRIPTION
**Pull request by l3nnartt**

### CODE REVIEW

**Comment by l3nnartt** [comment]
$ mdatp edr early-preview enabled
Unrecognized command 'enabled'. Expected one of:
  disable       Disable early preview
  enable        Enable early preview

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@Dansimp Please merge this PR. Thanks

**Comment by yogkumgit** [comment]
@Dansimp Gentle reminder. Thanks

**Comment by l3nnartt** [comment]
any news?

**Comment by l3nnartt** [comment]
thx

**Pull request merged**
