### PR TITLE
[DO NOT MERGE] Edits for retention articles

### PR DESCRIPTION
**Pull request by jdmartinez36**
Edited for the following items:

1. Changed if/if not ordered lists to unordered lists.
2. Indented notes to align with associated steps where necessary.
3. Changed heading levels for consistency (jumped from 2 to 4 in some cases).
4. Removed colon at end of section in retention-policies-teams and replaced with period.

The author should verify the heading level for "When a user leaves the organization". In the Teams article, it is a stand-alone H2, but in Exchange and SharePoint, it's an H3 sub-heading. In both cases, the content doesn't seem directly associated with the H2 preceding it.

### CODE REVIEW

**Comment by jdmartinez36** [comment]
@tiburd 

Articles ready for review.
Second commit is for a note indentation I had missed.

**Comment by tiburd** [comment]
Hi, Carol/@cabailey, 

We’ve completed the edit pass of your articles. Please review them and let me know if we’ve changed the technical meaning anywhere. You have five business days for the review (If you need longer, let me know). 

When your review is complete, and you’re satisfied with the changes, our team will do the final merge to confirm there are no remaining PR issues.

Thanks!

**Comment by cabailey** [comment]
@jdmartinez36 Thank you for your edits.  For #1 please change back to ordered lists.  If you look at the articles on the live site, you will see that they refer to numbers in the diagrams and if you remove these references, the information loses context.

**Comment by jdmartinez36** [comment]
Hi @cabailey 

I've reverted back to the numbered lists.

**Comment by cabailey** [comment]
@jdmartinez36  Thanks for reverting the lists.  Please also reverts the indents for the notes - in both cases they are not specific to the bullet above but relevant to the whole section.

**Comment by jdmartinez36** [comment]
Hi @cabailey 

I've reverted the note positions.

**Comment by cabailey** [comment]
@jdmartinez36  Thanks for reverting these notes.  This PR is ready for final checking to merge.  I'm fixing the "When a user leaves the organization" heading levels with another PR.  This content was pulled from another article, which explains the inconsistent level headings & appreciate the fresh check.

**Pull request merged**
