### PR TITLE
[DO NOT MERGE] Update plan-your-setup.md

### PR DESCRIPTION
**Pull request by 1justingilmore**
@DaniHalfin

### CODE REVIEW

**Comment by mypil** [comment]
@DaniHalfin - PR is ready for final review. This is related to the SEO project.

Thank you.

**Comment by tuco-ulf** [comment]
@DaniHalfin can we get this reviewed?

**Review by Sirkkuw — CHANGES_REQUESTED** [review]
It really is a set up, not a move to Microsoft 365 for business. In the last bit moving is ok, but we nirmally talk about setting up.

**Comment by DaniHalfin** [comment]
@tuco-ulf - can you follow up on the request above? Thanks 😀

**Comment by tuco-ulf** [comment]
@DaniHalfin looks like I'll have to create another PR to get into this to make the changes - Justin is no longer around to give me permissions.

**Pull request closed without merging**
