### PR TITLE
Update deploy-manage-removable-storage-intune.md

### LINKED ISSUE #13285: Wrong description to Scenario 3.
Scenario 3: Block read and execute access to specific file extension
For this scenario, you need to create two groups: one removable storage group for any removable storage and another group for unallowed file extensions. You also need to create one policy: deny read and execute access to any file under the **allowed file extension** group for defined removable storage group.

The description is wrong, and it should be "You also need to create one policy: deny read and execute access to any file under the **unallowed file extension** group for defined removable storage group."

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 19b5fda8-c875-aac3-385d-43c88feed731
* Version Independent ID: 19b5fda8-c875-aac3-385d-43c88feed731
* Content: [Deploy and manage Removable Storage Access Control using Intune](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/deploy-manage-removable-storage-intune?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/deploy-manage-removable-storage-intune.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/deploy-manage-removable-storage-intune.md)
* Service: **defender-endpoint**
* Sub-service: **asr**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

### PR DESCRIPTION
**Pull request by msbemba**
Made changes to scenario3

Fixes https://github.com/MicrosoftDocs/microsoft-365-docs/issues/13285

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy reivew

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@Dansimp Please merge this PR. Thanks

**Review by denisebmsft — APPROVED** [review]
Thank you @msbemba

**Review by denisebmsft — APPROVED** [review]
Thank you @msbemba

**Pull request merged**
