### PR TITLE
Update bookings-in-outlook.md

### PR DESCRIPTION
**Pull request by msbemba**
Updated the  Set-SharingPolicy cmdlet

### CODE REVIEW

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/8978

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@kwekuako Please merge this Pr. Thanks

**Review by Esirrr — APPROVED** [review]

**Comment by yogkumgit** [comment]
@kwekuako Gentle reminder. Thanks

**Pull request merged**
