### PR TITLE
Update add-or-replace-your-onmicrosoftcom-domain.md

### PR DESCRIPTION
**Pull request by msbemba**
Removed the note as I was able to remove an onmicrosoft.com domain from the Azure portal.

Fixes#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/10480

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@efrene Please merge this PR. Thanks

**Comment by yogkumgit** [comment]
@efrene Please merge this PR. Thanks

**Comment by efrene** [comment]
Followed up with this with engineering.  They said verified that although you can see the delete button in the Azure portal, you still will not be able to remove an onmicrosoft.com domain.  It will fail and you will see an error.   They recommend leaving the note as is.

**Pull request closed without merging**
