### PR TITLE
Update protection-stack-microsoft-defender-for-office365.md

### PR DESCRIPTION
**Pull request by msbemba**
Updated points 2 and 3, removed 4 as it is the same

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/6277

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@MSFTTracyP Please merge this PR. Thanks

**Comment by chrisda** [comment]
@msbemba, fundamentally, the problem with line 4 was a simple typo. Instead of ZAP for phishing, it should have been ZAP for spam, so I added it back and fixed it.

4. **ZAP for spam** retroactively detects and neutralizes malicious spam messages that have already been delivered to Exchange Online mailboxes.

**Pull request merged**
