### PR TITLE
Update remove-licenses-from-users.md

### PR DESCRIPTION
**Pull request by msbemba**
Added Exchange online data to reduce ambuiguity.

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/4757

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@cmcatee-MSFT Please merge this PR. Thanks

**Comment by yogkumgit** [comment]
@cmcatee-MSFT Gentle reminder.

**Comment by cmcatee-MSFT** [comment]
@yogkumgit I'm still trying to get approval from the PG.

**Comment by cmcatee-MSFT** [comment]
@yogkumgit Finally received confirmation from PG, so I'll approve the PR.

**Pull request merged**
