### PR TITLE
Updated table in apply-sensitivity-label-automatically.md

### LINKED ISSUE #2341: Document conflict
Conflict 

https://docs.microsoft.com/en-us/microsoft-365/compliance/classifier-getting-started-with?view=o365-worldwide

"Where can you use trainable classifiers" section  states that "Trainable Classifiers" can be used as a condition in  Auto Labeling. The table in the following page - contradicts this statement.

https://docs.microsoft.com/en-us/microsoft-365/compliance/apply-sensitivity-label-automatically?view=o365-worldwide#compare-auto-labeling-for-office-apps-with-auto-labeling-policies 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f3c5c98-9f47-9512-b932-2f72822796d2
* Version Independent ID: fd477cf9-4ee0-544f-10c6-f3dfccb10186
* Content: [Getting started with trainable classifiers (preview) - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/classifier-getting-started-with?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/classifier-getting-started-with.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/classifier-getting-started-with.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

### PR DESCRIPTION
**Pull request by dariomws**
Closes https://github.com/MicrosoftDocs/microsoft-365-docs/issues/2341.

@chrfox could you kindly confirm this information?

I found it's supported for both here:
https://docs.microsoft.com/microsoft-365/compliance/classifier-getting-started-with#where-you-can-use-trainable-classifiers

### CODE REVIEW

**Comment by yogkumgit** [comment]
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

**Review by JohanFreelancer9 — COMMENTED** [review]
The copy looks good but please check the formatting of the table.

**Comment by dariomws** [comment]
> The copy looks good but please check the formatting of the table.

Done, thanks!

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by cabailey** [comment]
No, the change proposed in apply-sensitivity-label-automatically.md is not correct.  Trainable classifiers are not supported in auto-labeling policies for sensitivity labels and the value needs to remain as No.  As documented in the table, trainable classifiers are supported for sensitivity labels only when you use the label setting of auto-labeling in Office apps.

Assigning to @chrfox to comment on the other changed file, which he owns.

**Comment by dariomws** [comment]
Thanks @cabailey for your feedback, I really appreciate it. I updated both articles to reflect that only Office auto labeling is supported.

Also, I think we should also update the following article:
https://docs.microsoft.com/microsoft-365/compliance/classifier-creating-a-trainable-classifier
At the end of the article:
"22. Once published your classifier will be available as a condition in Office autolabeling with sensitivity labels, auto-apply retention label policy based on a condition and in Communication compliance"

What do you think? Thanks!

**Pull request merged**
