### PR TITLE
Update add-custodians-to-case.md

### PR DESCRIPTION
**Pull request by msbemba**
tested and could see all types of groups showing up here. So changed it from Distribution groups to groups

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by msbemba** [comment]
issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/6575

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@markjjo Please merge this PR. Thanks

**Comment by yogkumgit** [comment]
@markjjo Gentle reminder.

**Comment by yogkumgit** [comment]
Issue# 6575 is closed by Author so closing this PR. Thanks

**Pull request closed without merging**
