### PR TITLE
Update enable-attack-surface-reduction.md

### PR DESCRIPTION
**Pull request by msbemba**
Updated the license requirement as the full set of ASR rules and features is only supported if you have an enterprise license for Windows 10.

REference :- https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/attack-surface-reduction-faq?view=o365-worldwide#do-i-need-to-have-an-enterprise-license-to-run-asr-rules-

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/6456

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@martyav Please merge this PR. Thanks

**Comment by yogkumgit** [comment]
@martyav Gentle reminder.

**Comment by yogkumgit** [comment]
@tiburd Please reach out to @martyav and help us in merging this PR. Thanks

**Comment by tiburd** [comment]
@martyav  @jweston-1 
Hi,

Can one of you please review this small change to resolve issue #6456?

Thank you!

**Comment by martyav** [comment]
@tiburd, @yogkumgit  and @msbemba -- very sorry for the delay. Although I have edited the doc in the past, I've mostly been working on documentation that is not hosted on Github lately. 

I just checked in with a subject matter expert and the changes proposed are correct.

**Review by martyav — APPROVED** [review]

**Comment by tiburd** [comment]
@martyav - Thank you! I'll merge the PR.

**Pull request merged**
