### PR TITLE
Update mac-install-with-intune.md

### PR DESCRIPTION
**Pull request by msbemba**
Made changes to the sequence of screenshot

Fixes#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/11149

### CODE REVIEW

**Comment by yogkumgit** [comment]
@JohanFreelancer9

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@Dansimp Please merge this PR. Thanks

**Comment by yogkumgit** [comment]
@mjcaparas Please mergre this PR. Thanks

**Comment by yogkumgit** [comment]
@mjcaparas Gentle reminder.

**Pull request merged**
