### PR TITLE
added  new version of platform update

### PR DESCRIPTION
**Pull request by RAJU2529**
i added a new version of the platform update v **4.18.2110-3.0** under windows defender after I checked in windows 11 64bit RTM 22000.282

Screenshot 2021-10-23 185230

### CODE REVIEW

**Comment by RAJU2529** [comment]
@e0i, please verify this PR #6683

**Comment by o0nj** [comment]
@yogkumgit Can help reviewing this PR. Thanks.

**Comment by yogkumgit** [comment]
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

**Comment by yogkumgit** [comment]
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

**Review by JohanFreelancer9 — APPROVED** [review]

**Review by denisebmsft — APPROVED** [review]
Thank you @RAJU2529

**Pull request merged**
