### PR TITLE
Update use-content-search-for-targeted-collections.md

### LINKED ISSUE #11566: add -IncludeSoftDeletedRecipients in the line 33 of the script.
[Enter feedback here]

How about to add the parameter "-IncludeSoftDeletedRecipients" on the script.
So our customer will be able to search also on the deleted users.
Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 136c161f-13b8-fb62-01de-53b1219b5290
* Version Independent ID: f1843c14-29da-d831-c7ce-9e3f624a01ed
* Content: [Use Content search for targeted collections - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/use-content-search-for-targeted-collections?view=o365-worldwide&source=docs)
* Content Source: [microsoft-365/compliance/use-content-search-for-targeted-collections.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/use-content-search-for-targeted-collections.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

### PR DESCRIPTION
**Pull request by msbemba**
Added -IncludeSoftDeletedRecipients parameter so that it can search deleted users as well

fixes https://github.com/MicrosoftDocs/microsoft-365-docs/issues/11566

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by yogkumgit** [comment]
@JohanFreelancer9

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@robmazz Please merge this PR> Thanks

**Comment by yogkumgit** [comment]
Closing as per the comment in #11566

**Pull request closed without merging**
