### PR TITLE
Update scheduler-setup.md

### PR DESCRIPTION
**Pull request by msbemba**
Mentioned that Scheduler is an add-on and not a part of any subscription.

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/5752

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@AshaIyengar21 Please merge this PR. Thanks

**Comment by yogkumgit** [comment]
@AshaIyengar21 Gentle reminder

**Pull request merged**
