### PR TITLE
Update allowselfservicepurchase-powershell.md

### PR DESCRIPTION
**Pull request by msbemba**
Fixed the value for setting per product

Fixes https://github.com/MicrosoftDocs/microsoft-365-docs-pr/issues/23623

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@cmcatee-MSFT Please merge this PR. Thanks

**Comment by yogkumgit** [comment]
@cmcatee-MSFT Gentle reminder.

**Comment by cmcatee-MSFT** [comment]
Confirmed with dev that using -Value is still valid, although -Enabled has also been added. Both can be used, but one only applies in certain situations. The dev felt it was better to leave it as-is.

**Pull request closed without merging**
