### PR TITLE
Update information-barriers-policies.md

### PR DESCRIPTION
**Pull request by msbemba**
Made changes to the last example as the existing policy 3 creates an asymmetric policy error

The table and the example have been updated

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/9517

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@robmazz Please merge this PR. Thanks

**Comment by yogkumgit** [comment]
@robmazz Gentle reminder. Thanks

**Comment by yogkumgit** [comment]
Closing as per the comment in #9517

**Pull request closed without merging**
