### PR TITLE
Update microsoft-365-docs-navigation-guide.md

### PR DESCRIPTION
**Pull request by mdanish-kh**
Fixed broken link.

### CODE REVIEW

**Review by JohanFreelancer9 — COMMENTED** [review]
Copy review - I do not see the need for this change. The original link seems to work fine. Thanks.

**Comment by mdanish-kh** [comment]
> Copy review - I do not see the need for this change. The original link seems to work fine. Thanks.

huh, that's odd. I dunno why it does not on my end 😕
image

There isn't a directory named `contribute` inside `microsoft-365-docs/` which the original link redirects to so I'm not sure how that link is working. 
image


In any case, I'll close this PR if you want me to.

**Comment by mdanish-kh** [comment]
welp, the relative link does work if I edit it in the public branch and see the diff. I guess it'll work when this gets merged as currently it refers to the README.md in my branch. We can just get rid of the relative link and use the **full path** to the README.md, but since other links used in the file were **relative**, I went with this approach.

**Review by JohanFreelancer9 — COMMENTED** [review]
Hi @mdanish-kh. Thanks again for your input. However, I have tested again and the original link does work It links to https://docs.microsoft.com/en-us/contribute/. So I would suggest you kindly close this PR. Many thanks.

**Comment by mdanish-kh** [comment]
> Hi @mdanish-kh. Thanks again for your input. However, I have tested again and the original link does work It links to https://docs.microsoft.com/en-us/contribute/. So I would suggest you kindly close this PR. Many thanks.

Oh, I'm dumb. I should've checked this on the main webpage instead of the github repo. Sorry for the inconvenience.

**Comment by JohanFreelancer9** [comment]
> > Hi @mdanish-kh. Thanks again for your input. However, I have tested again and the original link does work It links to https://docs.microsoft.com/en-us/contribute/. So I would suggest you kindly close this PR. Many thanks.
> 
> Oh, I'm dumb. I should've checked this on the main webpage instead of the github repo. Sorry for the inconvenience.

No problem at all.

**Pull request closed without merging**
