### PR TITLE
Added new event to the Search the audit log topic

### PR DESCRIPTION
**Pull request by ksenluu**
Added a new event, MarkedMessageChanged, to the Yammer activities table under the "Search the audit log in the compliance portal" topic

### CODE REVIEW

**Comment by ksenluu** [comment]
@markjjo please review the new Yammer event added

**Review by JohanFreelancer9 — APPROVED** [review]

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@robmazz Please merge this PR. Thanks

**Comment by ksenluu** [comment]
Updated the branch - is this good to be merged? @yogkumgit @JohanFreelancer9 Thanks!

**Comment by yogkumgit** [comment]
@robmazz Gentle reminder.

**Comment by robmazz** [comment]
@ksenluu - thanks for the feedback. I'll confirm this with the PG team and update as applicable. Thanks again.

**Pull request closed without merging**
