### PR TITLE
Update support.md

### PR DESCRIPTION
**Pull request by mertenar**
updating language to be more accurate to products being listed

### CODE REVIEW

**Comment by mypil** [comment]
@jdeckerms @lizap @DaniHalfin - Can you please assist to check, approve and merge the content of this PR?

**Comment by mypil** [comment]
@jdeckerms @lizap @DaniHalfin - I would like to follow up on this.  Can you please assist to check, approve and merge the content of this PR?

Thank you.

**Comment by jaimeo** [comment]
@mypil, jdeckerm is no longer w/ MS. In future, I'll ask @mertenar to flag me directly to be sure I'm aware of them.

**Comment by mypil** [comment]
@jaimeo - Thanks for this information. Are you the new doc owner who will be taking over all the articles from jdeckerm in this repository? Kindly confirm.

**Comment by jaimeo** [comment]
Not quite--it's not accurate to say I'm taking over docs formerly owned by jdeckerm. However, I do own all docs to do with Microsoft Managed Desktop, which this is. Aaron's tagging me on his PRs will help us catch these as well.

**Pull request merged**
