### PR TITLE
Update tvm-supported-os.md

### PR DESCRIPTION
**Pull request by msbemba**
Updated Amazon linux 2 to the list as it supported for MDATP and TVM

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/8477

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@siosulli Please merge this PR. Thanks

**Comment by siosulli** [comment]
@yogkumgit @JohanFreelancer9 

Thank you for looking at this PR. I'm close it as Amazon Linux2 is not yet supported for TVM.

**Comment by msbemba** [comment]
@siosulli Thank you for your response. I have made changes to reflect that it is not supported. Would you be able to approve and merge the PR?

**Comment by siosulli** [comment]
HI @msbemba, 

This table is for supported OS and platforms. It only includes not supported information when at least 1 platform is supported.

As soon as this support is available the product team will let me know and I will update. 

Thanks!

**Pull request closed without merging**
