### PR TITLE
api-luna is not a public endpoint or does not exists

### PR DESCRIPTION
**Pull request by AntoineJo**
Fixed with the standard public API endpoint

### CODE REVIEW

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@jweston-1 Please merge this PR. Thanks

**Comment by yogkumgit** [comment]
@jweston-1 Gentle reminder.

**Review by jweston-1 — APPROVED** [review]
Looks good. Please publish

**Comment by jweston-1** [comment]
Appproved

**Comment by yogkumgit** [comment]
@tiburd Please merge this PR. Thanks

**Pull request merged**
