### PR TITLE
Update prepare-tls-1.2-in-office-365.md

### PR DESCRIPTION
**Pull request by msbemba**
Added more information about what could happen if the customer's do not update to TlS1.2

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/2758

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@WorkShay Please merge this PR. Thanks.

**Comment by WorkShay** [comment]
@krowley is the person who owns this doc and can merge

**Comment by yogkumgit** [comment]
@krowley please merge this PR. Thanks

**Pull request closed without merging**
