### PR TITLE
Correct Invoke-CompatibilityCheck output location

### PR DESCRIPTION
**Pull request by awarre**
Invoke-CompatibilityCheck saves **output.csv** to the current working directory, not C:\windows\system32.

### CODE REVIEW

**Comment by yogkumgit** [comment]
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@kwekuako Please merge this PR. Thanks

**Comment by yogkumgit** [comment]
@kwekuako Gentle reminder, please merge this PR.

**Comment by yogkumgit** [comment]
@awarre Kindly resolve the conflict. Thanks

**Pull request merged**
