### PR TITLE
Update priority-accounts.md

### PR DESCRIPTION
**Pull request by msbemba**
Removed the broken link as the original document - https://docs.microsoft.com/Exchange/mail-flow-best-practices/mail-flow-insights/mfi-email-issues-for-priority-accounts has been modified.

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9  Please copy review

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/3036

**Comment by msbemba** [comment]
@kwekuako I have removed the link via the PR as the original link has been modified with new steps which do not contain details about email issues on priority account.

Thanks
Sri

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@kwekuako please merge this PR. Thanks

**Comment by yogkumgit** [comment]
@kwekuako Gentle reminder please merge this PR. Thanks.

**Comment by yogkumgit** [comment]
@kwekuako confirmed The topic has been updated and the link is going to the correct location. closing.

**Pull request closed without merging**
