### PR TITLE
Update unlimited-archiving.md

### PR DESCRIPTION
**Pull request by scorrea4099**
This bug concerns this documentation: Overview of unlimited archiving - Microsoft 365 Compliance | Microsoft Docs

The documentation reads:
You can delete items in a subfolder that points to an auto-expanded storage area, but the folder itself can't be deleted.

However, this is incorrect. As long as the user has at least one AuxArchive (i.e. auto-expanded) location, no folder can be deleted from the AuxArchive or the MainArchive. The documentation should be updated to reflect this. It does not matter which content mailbox GUID the folder points to.

### CODE REVIEW

**Comment by yogkumgit** [comment]
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

**Comment by markjjo** [comment]
@scorrea4099 Thanks for submitting. But not sure I understand the nuances of your change. Current doc says you can't delete folders. Is the point that folders in main archive can't be deleted either? Also, the current doc says that you can delete items in a folder, but you have removed this altogether.  Are you saying that you can't delete items either?

**Comment by markjjo** [comment]
@scorrea4099 You could also ping me in Teams (Markjjo) to discuss.

**Comment by markjjo** [comment]
@scorrea4099 PR merged. I updated the change based on our Teams chat. Updated topic should be live by end of day.

**Pull request merged**
