### PR TITLE
Update ti-indicator.md

### PR DESCRIPTION
**Pull request by msbemba**
Updated properties

Still need help with Some of the other properties description

category
educateUrl
bypassDurationHours
notificationId
notificationBody
version
mitreTechniques
historicalDetection
lookBackPeriod
generateAlert
additionalInfo
createdByDisplayName
certificateInfo

### CODE REVIEW

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/5887

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@mjcaparas Please merge this PR. Thanks

**Comment by mjcaparas** [comment]
For now document the ones with available info.

**Pull request merged**
