### PR TITLE
fixed misleading label

### PR DESCRIPTION
**Pull request by cpoDesign**
just followed the guide and fount it incorrect, hence for the update for your consideration

### CODE REVIEW

**Comment by mypil** [comment]
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by cpoDesign** [comment]
@JohanFreelancer9 @mypil I cannot complete the pr, what do I do next??

**Comment by mypil** [comment]
@cpoDesign - It will be the author @pebaum who will make the final decision whether this PR will be approved for merging.

**Comment by mypil** [comment]
@pebaum - PR has been copy edited and is ready for final review. 

Thank you.

cc: @kenwith

**Pull request merged**
