### PR TITLE
adding clarity regarding the order of events

### PR DESCRIPTION
**Pull request by AdwoodMicrosoft**

### CODE REVIEW

**Comment by yogkumgit** [comment]
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

**Comment by MikePlumleyMSFT** [comment]
@AdwoodMicrosoft which license are we referring to? Multi-Geo specifically or Microsoft 365 in general?

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@AdwoodMicrosoft Gentle reminder

**Comment by yogkumgit** [comment]
@AdwoodMicrosoft Kindly reply.

**Comment by MikePlumleyMSFT** [comment]
@WayneEwington can you clarify Adriana's PR?

**Comment by yogkumgit** [comment]
@MikePlumleyMSFT and @WayneEwington Gentle reminder

**Comment by yogkumgit** [comment]
@tiburd Please take this up. Thanks

**Pull request merged**
