### PR TITLE
Update allowselfservicepurchase-powershell.md

### PR DESCRIPTION
**Pull request by msbemba**
Made changes to the parameter in Update-MSCommerceProductPolicy

fixes#https://github.com/MicrosoftDocs/microsoft-365-docs-pr/issues/23790

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@cmcatee-MSFT Please merge this PR. Thanks

**Comment by yogkumgit** [comment]
@cmcatee-MSFT Gentle reminder

**Comment by cmcatee-MSFT** [comment]
-Value is still valid, although -Enabled can also be used. Dev said it only applies in certain cases, but for simplicity recommended leaving the article as-is to avoid confusion.

**Pull request closed without merging**
