### PR TITLE
Update manage-payment-methods.md

### PR DESCRIPTION
**Pull request by msbemba**
Added a clarity within the document from manage to "manage or put to use"

### CODE REVIEW

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/1798

**Comment by mypil** [comment]
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

**Comment by cmcatee-MSFT** [comment]
@mypil @JohanFreelancer9 I am currently verifying accuracy with the product team.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by cmcatee-MSFT** [comment]
Closing PR. Product team has requested different wording for clarification of who can manage & use payment methods. I'm working with them to update the intro accordingly.

**Pull request closed without merging**
