### PR TITLE
Update mde-p1-setup-configuration.md

### PR DESCRIPTION
**Pull request by msbemba**
Defender for endpoint plan 1 is called Defender lite. Added that detail to the document to reduce ambiguity.

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by msbemba** [comment]
issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/7354

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@denisebmsft Please merge this PR. Thanks

**Comment by denisebmsft** [comment]
Confirming... will merge following that.

**Review by denisebmsft — COMMENTED** [review]
Thank you @msbemba. The correct name of the plan is Microsoft Defender for Endpoint Plan 1. The former name will be updated in the system very soon.

**Pull request merged**
