### PR TITLE
Update office-365-service-encryption.md

### PR DESCRIPTION
**Pull request by msbemba**
Corrected link for Enhancing transparency and control for Office 365 customers

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/4752

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@KCCross Please merge this PR. Thanks

**Comment by yogkumgit** [comment]
@KCCross Gentle reminder

**Comment by tiburd** [comment]
The link has been updated via a different PR. Closing this PR.

**Pull request closed without merging**
