### PR TITLE
Update create-retention-policies.md

### PR DESCRIPTION
**Pull request by YuriySamorodov**
Minor changes to OneDrive settings:
- ```UserPrincipalName``` is a well known term for every Windows admin out there and it's one word, not three words
- Removed spaces in the URL for the sake of URL format
- Converted a sentence to the note for better readability

### CODE REVIEW

**Comment by cabailey** [comment]
Closing per our other thread (and this PR introduces other problems).  We're looking into moving these details to the OneDrive documentation, which is the right place for it rather than documentation for retention policies.  Happily, adaptive scopes that will soon be in public preview will eliminate these problems to get the URL exactly right, because you'll be able to specify a user and their OneDrive URL will be automatically picked up, even if it changes.

**Comment by YuriySamorodov** [comment]
Thanks @cabailey
Could you please advise where do I know more about adaptive scopes?
Kind regards.
Yuriy

**Comment by cabailey** [comment]
@YuriySamorodov  Initial announcement for private preview here: https://techcommunity.microsoft.com/t5/security-compliance-and-identity/announcing-multi-stage-disposition-in-microsoft-records/ba-p/2361849#scopes

As soon as it's released for public preview, the online docs will be updated. In the meantime, you can register for the following webinar:

Introducing Adaptive Policy Scopes for Information Governance and Records Management - September 21st
US/EMEA 16:00 GMT / 8:00 PST: Link to register - https://mipc.eventbuilder.com/event/45703 
APAC 13:00 AEDT: Link to register - https://mipc.eventbuilder.com/event/45704

You can monitor the release status with the M365 roadmap entry: https://www.microsoft.com/en-us/microsoft-365/roadmap?filters=&searchterms=70578

**Comment by YuriySamorodov** [comment]
Thanks @cabailey , really appreciate that!
Sounds like a retention done right!

**Pull request closed without merging**
