### PR TITLE
Update permissions-filtering-for-content-search.md

### PR DESCRIPTION
**Pull request by msbemba**
Updated "Action" parameter for New-ComplianceSecurityFilter syntax and examples 

reference - https://docs.microsoft.com/en-us/powershell/module/exchange/new-compliancesecurityfilter?view=exchange-ps

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/6802

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@markjjo Please merge this PR. Thanks

**Comment by markjjo** [comment]
Closing. Action parameter is not required. All actions are added by default.

**Pull request closed without merging**
