### PR TITLE
Update endpoint-dlp-getting-started.md

### PR DESCRIPTION
**Pull request by msbemba**
Added Permissions in the Security and Compliance Center. This gives them an insight as the Exchange role groups and Security & Compliance Center role groups don't share membership or permissions.

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by msbemba** [comment]
issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/3501

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@chrfox Please merge this PR. Thanks.

**Comment by chrfox** [comment]
Compliance center and Security center split long ago.  DLP in in the compliance center

**Pull request closed without merging**
