### PR TITLE
Update customer-key-set-up.md

### PR DESCRIPTION
**Pull request by msbemba**
Made changes to the navigation as it is changed from Request services to Deploy on the portal.

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/7466

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@KCCross Please merge this PR. Thanks

**Comment by yogkumgit** [comment]
@KCCross Gentle reminder

**Comment by yogkumgit** [comment]
@KCCross Awaiting your kind response. Thanks

**Pull request merged**
