### PR TITLE
Update offering-nz-cc-framework-nz.md

### PR DESCRIPTION
**Pull request by msbemba**
REmoved  "Microsoft NZ has worked with the GCIO team to develop a reference architecture for integrating Exchange Online and SEEMail described in the white paper [Office 365: SEEMail Integration and Reference Architecture](https://download.microsoft.com/download/8/5/9/859CDCEE-D293-47D8-9B6A-670B108B48E1/Microsoft_Office_365_white_paper_EN_US.pdf) as this is old and inaccurate.

@robmazz  let us know if there is another version of this document so we can replace it.

Thanks
Sri

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9  Please copy review

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/2653

**Comment by PeteHaigh-MSFT** [comment]
No newer doc - we're advising agencies and partners on an ad-hoc basis. Thanks for taking this down as we've been causing some confusion 🙄

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@robmazz Please merge this PR. Thanks.

**Pull request merged**
