### PR TITLE
Update threat-protection-integration.md

### PR DESCRIPTION
**Pull request by Phorpiex**
Endpoint endpoint double entry typo

### CODE REVIEW

**Comment by Phorpiex** [comment]
Endpoint endpoint  double entry

**Comment by Phorpiex** [comment]
Endpoint endpoint double entry typo

**Comment by yogkumgit** [comment]
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@tiburd Please merge this PR. Thanks

**Pull request merged**
