### PR TITLE
Update change-nameservers-at-any-domain-registrar.md

### PR DESCRIPTION
**Pull request by msbemba**
Corrected the Name server information to reflect ns3.bdm.microsoftonline.com and ns4.bdm.microsoftonline.com

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/2708

**Comment by yogkumgit** [comment]
@JohanFreelancer9 reminder, Please copy review

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@pebaum Please merge this PR. Thanks.

**Comment by yogkumgit** [comment]
@pebaum  Gentle reminder, Please merge this PR. Thanks.

**Comment by yogkumgit** [comment]
@pebaum This is pending almost for 3 weeks now, Please merge this PR. Thanks.

**Comment by pebaum** [comment]
this edit is already live

**Pull request closed without merging**
