### PR TITLE
Correct GDPR High Volume

### PR DESCRIPTION
**Pull request by TheAutisticTechie**
The High Volume was using the same Min and Max count as Low Volume. Corrected to be `Min 10` and `Max Any`

### CODE REVIEW

**Comment by yogkumgit** [comment]
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@chrfox Please merge this PR. Thanks

**Comment by chrfox** [comment]
@dltmurphy - thanks for this. The value in the console is actually 500, not Any.  Addressing this in a different PR.

**Comment by TheAutisticTechie** [comment]
I can amend this one quickly if its easier?

**Comment by TheAutisticTechie** [comment]
All of the other templates are set to `Any` for their `High Volume` FYI

**Pull request closed without merging**
