### PR TITLE
Update configure-siem.md

### PR DESCRIPTION
**Pull request by msbemba**
Updated new splunk add-on as the old one is deprecated.

### CODE REVIEW

**Comment by msbemba** [comment]
issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/9730

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Review by JohanFreelancer9 — APPROVED** [review]

**Review by denisebmsft — APPROVED** [review]
Thank you @msbemba

**Comment by msbemba** [comment]
@yogkumgit Validation has been passed.

**Comment by yogkumgit** [comment]
@mjcaparas Please merge this PR. Thanks

**Pull request merged**
