### PR TITLE
Update advanced-hunting-overview.md

### PR DESCRIPTION
**Pull request by msbemba**
Tested and found only Global admin and Security admin can run this query. whereas the Security reader cannot run or share the query. Please validate and approve.

Per @lomayor adding this information in the overview document

This is replacing PR #https://github.com/MicrosoftDocs/microsoft-365-docs/pull/4360 as conflicts were not getting resolved.

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

CC : @schmurky  for Merging

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/3857

**Comment by yogkumgit** [comment]
@schmurky Please merge this PR. Thanks

**Comment by schmurky** [comment]
Hi, @msbemba, circling back on this, can you clarify "Security reader cannot run or share the query". Now they use the federated RBAC model  so it's not telling the whole story. I plan to remove this addition and instead add a link in the Get access section on the same page to account for the required permission for hunting scenarios across workloads:  https://docs.microsoft.com/microsoft-365/security/defender/custom-roles

**Comment by schmurky** [comment]
Gentle nudge on feedback above @msbemba

**Comment by msbemba** [comment]
@schmurky You are right it does not tell us the whole story. I think the change that you proposed is more clear.

**Comment by schmurky** [comment]
Thanks! PR for this edit is here (FYI): https://github.com/MicrosoftDocs/microsoft-365-docs-pr/pull/8054

**Comment by yogkumgit** [comment]
@schmurky link is 404

**Comment by schmurky** [comment]
Please see the update here: https://docs.microsoft.com/en-us/microsoft-365/security/defender/advanced-hunting-overview?view=o365-worldwide

(Not sure why the PR was 404)

**Pull request merged**
