### PR TITLE
Update view-incidents-queue.md

### LINKED ISSUE #13107: "By default, the queue displays incidents seen in the last 30 days" is seems not correct now.
Hello team.

I think below line is not correct.
> By default, the queue displays incidents seen in the last 30 days, with the most recent incident showing at the top of the list, helping you see the most recent incidents first.

In my tenant, the queue displays incidents seen in **the last 6 months** by default.
Could you confirm that page is correct or not?

Best regards.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c12a247e-0591-e03a-4f65-7e91e9c143cd
* Version Independent ID: c14c46c7-a3f8-9e6a-fec9-5c8bb6010eb2
* Content: [View and organize the Incidents queue](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/view-incidents-queue?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/view-incidents-queue.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/view-incidents-queue.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

### PR DESCRIPTION
**Pull request by msbemba**
Updated default incidents display days

Fixes https://github.com/MicrosoftDocs/microsoft-365-docs/issues/13107

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@Dansimp Please merge this PR. Thanks

**Comment by yogkumgit** [comment]
@Dansimp Gentle reminder.

**Comment by Dansimp** [comment]
@diannegali  can you confirm that this is correct?

**Comment by diannegali** [comment]
Confirming that the update is correct. Merging this PR now.

**Pull request merged**
