### PR TITLE
Update insider-risk-management-policies.md

### PR DESCRIPTION
**Pull request by msbemba**
Removed add link option from the document

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/2569

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@robmazz Please merge this PR. Thanks

**Comment by robmazz** [comment]
Will update with correct link, thanks for catching this!

**Pull request closed without merging**
