### PR TITLE
⚡ Correction to Update audit-log-search.md

### PR DESCRIPTION
**Pull request by peter-myers**
Removed an incorrect sentence.

### CODE REVIEW

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@tiburd Please merge this PR. Thanks

**Comment by tiburd** [comment]
@robmazz 
Hi Rob,
Please review the change in this PR and let us know whether you approve the change. (Or merge if you approve, or close if you don't approve.)
Thanks!

**Comment by yogkumgit** [comment]
@robmazz Gentle reminder

**Comment by steelanddata** [comment]
@tiburd @yogkumgit @robmazz - I have completed my review of the article and approve the Power BI-related changes. If any additional action is required from me, please let me know what steps you need me to take.

**Review by steelanddata — APPROVED** [review]

**Pull request merged**
