### PR TITLE
Update overview-hardware-based-isolation.md

### PR DESCRIPTION
**Pull request by msbemba**
Updated the links on the document for Defender for endpoint and m365 defender

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/6239

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@mjcaparas Please merge this PR. Thanks

**Comment by Jwaegebaert** [comment]
@msbemba Hi there. Thanks for your PR. But the issue references that the links are broken for _Windows Defender Application Guard_ and for _Windows Defender System Guard_. Currently, I don't see any change to those links in this PR.

**Comment by msbemba** [comment]
Since the changes are from internal repo, you will not be able to validate. You will notice the updated links once the PR is merged.

**Pull request merged**
