### PR TITLE
Update use-network-upload-to-import-pst-files.md

### PR DESCRIPTION
**Pull request by anepu**
hello, this is my first time proposing a change, I hope more will come :)
I've modified the syntax on lines 136 and 155
However, I feel like the whole documentation for AzCopy.exe should be changed as the cmdlets presented here do not work anymore with the last AzCopy.exe tool -> https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-v10

### CODE REVIEW

**Comment by yogkumgit** [comment]
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

**Review by JohanFreelancer9 — APPROVED** [review]
Copy review.

**Comment by yogkumgit** [comment]
@markjjo Please merge this PR. Thanks

**Comment by markjjo** [comment]
@anepu PST Import only supports Azcopy v8. To be specific, PST import supports the version of Azcopy that can be download from this link in the network upload UI; currently, that is v8. [This requirement is docuented.](https://docs.microsoft.com/en-us/microsoft-365/compliance/use-network-upload-to-import-pst-files?view=o365-worldwide#step-1-copy-the-sas-url-and-install-azcopy) You can still use the v10 the syntax that you suggest to upload your PSTs, but the documentation needs to show syntax for v8. Thanks for submitting, but closing this PR.

**Pull request closed without merging**
