### PR TITLE
Update gdpr-dsr-Office365.md

### PR DESCRIPTION
**Pull request by msbemba**
Removed references of OUTlook customer manager as it has been deprecated

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/3385

**Comment by yogkumgit** [comment]
@JohanFreelancer9 Please copy review, reminder, Thanks

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by robmazz** [comment]
@msbemba and @yogkumgit - this content was migrated to another repo, will incorporate these updates into the topic in the new location on separate PR.

**Pull request closed without merging**
