### PR TITLE
Update detailed-properties-in-the-office-365-audit-log.md

### PR DESCRIPTION
**Pull request by andypunt**
Improved grammar and added event 29.

### CODE REVIEW

**Comment by whh5599** [comment]
所有检查均已通过
1次成功检查

**Comment by mypil** [comment]
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by markjjo** [comment]
@andypunt PR merged

**Comment by markjjo** [comment]
@andypunt PR merged

**Pull request merged**
