### PR TITLE
Update prepare-tls-1.2-in-office-365.md

### PR DESCRIPTION
**Pull request by msbemba**
Made changes to the information about  deprecation of support for TLS 1.0 and 1.1

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/8238

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@KCCross Please merge this PR. Thanks

**Comment by yogkumgit** [comment]
@KCCross Gentle reminder

**Comment by KCCross** [comment]
I'm not prepared to state this w/o backup from internal folks. Closing this here and reopening a conversation internally.

**Pull request closed without merging**
