### PR TITLE
pull fabrikam's mailboxes into contoso

### PR DESCRIPTION
**Pull request by psykokwak4**

### CODE REVIEW

**Comment by yogkumgit** [comment]
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@JoeDavies-MSFT please merge this PR. Thanks

**Comment by psykokwak4** [comment]
Kindly let me know when it could get reviewed/checkedin.

**Comment by JoeDavies-MSFT** [comment]
@psykokwak4 Sorry for the delay in addressing this pull request. I have asked the product to team to review the changes before I merge. Thanks so much for your time and effort to submit this feedback.

**Comment by yogkumgit** [comment]
@tiburd Please take this up. Thanks

**Comment by psykokwak4** [comment]
No longer apply after 1 year.

**Pull request closed without merging**
