### PR TITLE
Update retention-policies-teams.md

### PR DESCRIPTION
**Pull request by msbemba**
Added IMportant tag to Highlight the section of what is not covered by retention

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/4850

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@cabailey Please merge this PR. Thanks.

**Comment by yogkumgit** [comment]
@Kateyanne Please merge this PR. Thanks

**Comment by cabailey** [comment]
#hold-off

**Comment by cabailey** [comment]
Closing - no need to highlight this paragraph.  The existing formatting is consistent with the other articles that cover the same information for what's included and excluded for retention.

**Pull request closed without merging**
