### PR TITLE
Update run-detection-test.md

### PR DESCRIPTION
**Pull request by msbemba**
tested and the alert triggers even without the folder created

Per issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/9678

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Review by JohanFreelancer9 — APPROVED** [review]

**Review by denisebmsft — APPROVED** [review]
Thank you @msbemba

**Review by denisebmsft — APPROVED** [review]
Thank you @JohanFreelancer9

**Comment by yogkumgit** [comment]
@mjcaparas Please merge this PR. Thanks

**Pull request merged**
