### PR TITLE
Update classifier-getting-started-with.md

### PR DESCRIPTION
**Pull request by MaratMussabekov**
#1224, replacement of  #1272

### CODE REVIEW

**Comment by MaratMussabekov** [comment]
Dear @chrfox , 
could you please have a look?
Thank you

**Comment by mypil** [comment]
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by mypil** [comment]
@chrfox - PR has been copy edited and is ready for final review. This is based on issue #1224.

Thank you.

cc: @kenwith

**Comment by chrfox** [comment]
automated pattern matching is not a classifier, "both types" of classifiers is meant to refer to the built-in classifiers and trainable classifiers. fixing note to reflect and closing this PR

**Pull request closed without merging**
