### PR TITLE
Upgrade localization priority

### PR DESCRIPTION
**Pull request by TinaMcN**
I received feedback that this topic is very sensitive, specially in the EU and important to keep human translated.

### CODE REVIEW

**Comment by yogkumgit** [comment]
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@pebaum Please merge this PR. Thanks

**Comment by TinaMcN** [comment]
@yogkumgit pebaum is on leave, can you assign to someone else?

**Comment by yogkumgit** [comment]
@pebaum and @scotvidican Please merge this PR. Thanks

**Comment by yogkumgit** [comment]
@pebaum Gentle reminder. Thanks

**Pull request merged**
