### PR TITLE
Update ediscovery-search-and-delete-teams-chat-messages.md

### PR DESCRIPTION
**Pull request by msbemba**
Made changes to the document as the URLhttps://graph.microsoft.com/v1.0/security/ediscovery/cases does not work and gives 400 bad request error.

Changing it with https://graph.microsoft.com/beta/compliance/ediscovery/cases works fine

fixes#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/10603

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 please copy review

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@tiburd Please merge this PR. Thabks

**Comment by yogkumgit** [comment]
@tiburd Please merge this Pr. Thanks

**Comment by tiburd** [comment]
close > reopen

**Pull request merged**
