### PR TITLE
Update whats-new.md

### PR DESCRIPTION
**Pull request by msbemba**
Change notation for the image from :::image type="content" source="../media/mcc-records-management-page.png" alt-text="Records management section in Microsoft 365 compliance center":::
to:
<Records management section in Microsoft 365 compliance center>

as it breaks appearing of images on live pages in machine translated content

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9  Please copy review

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/2611

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@btbennett Please merge this PR. Thanks.

**Comment by yogkumgit** [comment]
@btbennett  Gentle reminder, Please merge this PR. Thanks.

**Comment by yogkumgit** [comment]
@btbennett This merge is pending for more than one month now. Please merge this PR. Thanks,

**Pull request closed without merging**
