### PR TITLE
ProPlus (M365 App usage) released into Gallatin

### PR DESCRIPTION
**Pull request by Zhiliqiao888**
M365 App usage report is released into Gallatin

### CODE REVIEW

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@kwekuako Please merge this PR. Thanks

**Comment by Zhiliqiao888** [comment]
@kwekuako Can you merge? Thanks.

**Comment by Zhiliqiao888** [comment]
@kwekuako May I know after the merge, how long it will reflect in public documentation? Thank you.

**Comment by kwekuako** [comment]
@Zhiliqiao888, the change is now live. Usually take a few hours to reflect in the public docs. Thanks.

**Pull request merged**
