### PR TITLE
Update linux-install-with-ansible.md

### PR DESCRIPTION
**Pull request by msbemba**
Updated Keyserver for APT key to https://packages.microsoft.com/keys/microsoft.asc
Reference -https://docs.microsoft.com/en-us/windows-server/administration/linux-package-repository-for-microsoft-software

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/5202

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@mjcaparas Please merge this PR. Thanks

**Comment by konstruktoid** [comment]
This is a duplicate, see https://github.com/MicrosoftDocs/microsoft-365-docs/pull/4809

**Comment by mjcaparas** [comment]
Will close this one. Merged 4809 instead.

**Pull request closed without merging**
