### PR TITLE
Update information-barriers.md

### PR DESCRIPTION
**Pull request by msbemba**
Added - Microsoft 365 E3/A3 subscription as it seems to be listed as a s service under these subscriptions

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by msbemba** [comment]
issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/7840

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@robmazz Please merge this PR. Thanks

**Comment by yogkumgit** [comment]
@robmazz Gentle reminder. Thanks

**Comment by yogkumgit** [comment]
closing as per the comment in #7840

**Pull request closed without merging**
