### PR TITLE
Update add-domain.md

### PR DESCRIPTION
**Pull request by msbemba**
removed the hyperlink for domain connect which was pointing to https://www.domainconnect.org/

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/3448

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by pebaum** [comment]
this is a legitimate link to a legitimate website

**Comment by msbemba** [comment]
Thank you for the confirmation @pebaum

**Pull request closed without merging**
