### PR TITLE
Update device-requirements.md

### PR DESCRIPTION
**Pull request by msbemba**
The Site is available only in the US so the URL needs to be https://www.microsoft.com/en-us/windowsforbusiness/view-all-devices

If we remove the locale it results in  404.

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/5734

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@jaimeo Please merge this PR. Thanks

**Comment by yogkumgit** [comment]
@jaimeo Gentle reminder

**Comment by jaimeo** [comment]
Looking into why that page isn't following our corporate guidelines re: locales in URLs.

**Comment by jaimeo** [comment]
@msbemba to clarify, it does NOT 404 if your locale is en-us. But it does not appear to be a localized page, so if the locale is other than en-us, it does indeed fail as you report.

**Pull request merged**
