### PR TITLE
Update mac-install-manually.md

### PR DESCRIPTION
**Pull request by msbemba**
removed  Application installation (macOS 10.15 and older versions) and replaced it with Application installation (macOS 10.15) as MDE supports only 10.15 or higher versions of Mac OS

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/7605

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@Dansimp Please merge this PR. Thanks

**Review by JohanFreelancer9 — CHANGES_REQUESTED** [review]
Hi @msbemba, reading the rest of the article, I have noticed that the same change needs to be made to line 36, please.

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@JohanFreelancer9 Thank you for pointing it out. I have made changes to line 36 now, could you please review it?

Thanks
Sri

**Comment by yogkumgit** [comment]
@Dansimp Please merge this PR. Thanks

**Review by JohanFreelancer9 — APPROVED** [review]

**Pull request merged**
