### PR TITLE
Update set-up-content-understanding.md

### PR DESCRIPTION
**Pull request by msbemba**
Made changes tot he navigation to automate content understanding

### CODE REVIEW

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/3417

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@MikePlumleyMSFT Please merge this PR. Thanks

**Comment by MikePlumleyMSFT** [comment]
@msbemba @yogkumgit "Organizational knowledge" is a temporary heading. "Files and content" should be rolling out soon.

**Pull request closed without merging**
