### PR TITLE
Update domains-faq.yml

### PR DESCRIPTION
**Pull request by msbemba**
Added explicit .com and .de to reduce ambiguity

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/8844

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@efrene Please merge this PR. Thanks

**Comment by efrene** [comment]
You can delete this PR. I had updated the article by removing the repeat and incorrect section.

**Comment by msbemba** [comment]
Thank you, @efrene 

@yogkumgit the issue can be closed.

**Pull request closed without merging**
