### PR TITLE
Update use-dmarc-to-validate-email.md

### PR DESCRIPTION
**Pull request by msbemba**
Removed instructions on adding DMARC record as it was pointing to a document which talks about adding MX and TXT records to connect your domain and nothing specific to DMARC. or another TXT record.

The document already contains instructions about forming DMARC records and best practices. So users will have to form the record and update it on their domain registrar for which the steps will be different depending on the host.

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/4881

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@scotvidican Please merge this PR. Thanks

**Comment by yogkumgit** [comment]
@scotvidican Gentle reminder

**Pull request merged**
