### PR TITLE
Update sensitive-information-type-learn-about.md

### PR DESCRIPTION
**Pull request by arastogi205**
@chrfox - I have made a couple of edits to the Learn about sensitive information types document. Please have a look and approve the changes if they look good. Please note that one of the changes is to create a table. I hope the format i have followed is correct.

### CODE REVIEW

**Comment by chrfox** [comment]
HI @arastogi205 
The table doesn't render correctly, so I'll have to look into that. In addition the publishing system is having a major outage, so it may be a day or two before I can get this rendered to work on it

**Comment by yogkumgit** [comment]
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

**Comment by chrfox** [comment]
@arastogi205 
clsoing this without merging. I have added the confidence level results aggregation information in a different format in a different place.  The diagram is unnecessary. The second note is not appropriate for the topic.  All statements about possible future actions belong in a blog post, the roadmap or the message center.  Also, as of this writing the build and publishing system is still down, so publishing will not be immediate.

**Comment by arastogi205** [comment]
@chrfox - can you share where you have added the confidence level result aggregation. Since, the publishing is not immediate, I am not sure how can I view the changes made.

**Pull request closed without merging**
