### PR TITLE
Update ome-faq.yml

### PR DESCRIPTION
**Pull request by shelri**
https://o365exchange.visualstudio.com/Enterprise%20Cloud/_workitems/edit/2173601/

### CODE REVIEW

**Comment by yogkumgit** [comment]
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@KCCross Please merge this PR. Thanks

**Comment by KCCross** [comment]
This isn't correct. eDiscovery *is* supported, just not with custom branding templates.

**Comment by KCCross** [comment]
Asking Samson to confirm before I do anything with this. Samson, here's the quote from eDiscovery content.

To make it easier to manage encrypted content in the eDiscovery workflow, Microsoft 365 eDiscovery tools now incorporate the decryption of encrypted files attached to email messages and sent in Exchange Online.

**Pull request merged**
