### PR TITLE
added info about the limit

### PR DESCRIPTION
**Pull request by MaratMussabekov**
#989

### CODE REVIEW

**Comment by mypil** [comment]
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by mypil** [comment]
@chrfox - PR has been copy edited and is ready for final review. This is based on issue #989

Thank you.

cc: @kenwith

**Comment by chrfox** [comment]
I am checking with the PG on this issue before publication

**Comment by chrfox** [comment]
approved

**Pull request merged**
