### PR TITLE
Update non-windows.md

### PR DESCRIPTION
**Pull request by msbemba**
Removed DLP for the nonsupported section as macOS now supports Endpoint DLP - reference - https://docs.microsoft.com/en-us/microsoft-365/compliance/endpoint-dlp-getting-started?view=o365-worldwide

### CODE REVIEW

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/8920

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@mjcaparas Please merge this PR. Thanks.

**Comment by mjcaparas** [comment]
@msbemba - But you're removing the DLP support in the Linux section. I think it should be on the mac section right?

**Comment by yogkumgit** [comment]
@msbemba

**Comment by yogkumgit** [comment]
@msbemba Gentle reminder. Thanks

**Comment by mjcaparas** [comment]
@msbemba please update to mac section not linux

**Comment by msbemba** [comment]
@mjcaparas Sorry about that. I just fixed it.

**Pull request merged**
