### PR TITLE
Update minimum-requirements.md

### PR DESCRIPTION
**Pull request by yangsa666**
**PR Summary**

Add Windows Server 2022 Core edition in Supported Windows versions.

Add this because MDE supports this Windows OS version.

### CODE REVIEW

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@siosulli Please merge this PR. Thanks

**Comment by siosulli** [comment]
@yogkumgit I'm in the process of confirming if this is to be published to public docs.

Thanks!

**Comment by yangsa666** [comment]
> @yogkumgit I'm in the process of confirming if this is to be published to public docs.
> 
> Thanks!

Hi @siosulli , thanks for taking a look at this PR. Yes, we do need a double confirmation. Per my team's test, it works fine on Win Server 2022 Core edition, that's why I submitted this PR. Please kindly merge this PR once it's good to publish this to public. Appreciate your help.

**Comment by siosulli** [comment]
Thanks @yangsa666. The update I got back was:

We do support Windows Server 2022 Core edition on data center scenarios however there isn't enough validation done on this SKU to declare a wider support. The team said they will work on getting the test matrix updated to declare full support.

I will track this in a separate task on my backlog so as not to leave this ticket hanging around open! As soon as I get confirmation on support, I will make this update!

Thanks again,
Sinead

**Comment by yangsa666** [comment]
> Thanks @yangsa666. The update I got back was:
> 
> We do support Windows Server 2022 Core edition on data center scenarios however there isn't enough validation done on this SKU to declare a wider support. The team said they will work on getting the test matrix updated to declare full support.
> 
> I will track this in a separate task on my backlog so as not to leave this ticket hanging around open! As soon as I get confirmation on support, I will make this update!
> 
> Thanks again, Sinead

@siosulli  Thanks for the update. So, Win Server 2022 Core is not fully supported yet, officially. I'll also leave this PR  here and look forward to the next update from you.

**Comment by yangsa666** [comment]
@siosulli It looks like the document is already updated with including the Windows Server 2022 Core edition. So, let's close this PR.

**Pull request closed without merging**
