### PR TITLE
Update reports.md

### PR DESCRIPTION
**Pull request by StuEwen**
@jaimeo to review and schedule changes

### CODE REVIEW

**Comment by jaimeo** [comment]
@traya1 this needs to go live on 7/22 (not before). Can't follow the posted process b/c this isn't in the internal repo. I understand you can help moving this over to the private repo? I myself will not be able to be involved after this afternoon as I'll be OOF for more than a week.

**Comment by traya1** [comment]
Hi @StuEwen,

Can you ping me on Teams? I can help you stage the proposed changes in the PR over in the internal repo and get it ready for the requested publish date.

Thanks!

**Comment by yogkumgit** [comment]
@jaimeo and @traya1 Please resolve. Thanks

**Comment by traya1** [comment]
Hi @StuEwen, 

Can you contact me on Teams so I can help you move the changes to the internal repos? Thanks!

**Pull request closed without merging**
