### PR TITLE
Update device-control-removable-storage-access-control.md

### PR DESCRIPTION
**Pull request by tewchen**

### CODE REVIEW

**Comment by yogkumgit** [comment]
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@v-smandalika Please merge this PR. Thanks.

**Comment by yogkumgit** [comment]
@v-smandalika Please merge this PR. Thanks

**Comment by v-smandalika** [comment]
Hi @yogkumgit 

Apologies that we could not take this up with our Principal Manager Daniel Simpson.

Just FYI, we from the documentation team do not have the privileges to merge PRs; hence, we have taken this up with Daniel Simpson.  We will be getting an idea as to whether new tickets are to be created for us to import changes from this PR into our new PRs.

We have notified Daniel Simpson about this PR's status, and we will be reverting to you tomorrow.


Thanks,
Siddarth

**Comment by yogkumgit** [comment]
@Dansimp Please merge this PR. Thanks

**Pull request merged**
