### PR TITLE
Update api-hello-world.md

### PR DESCRIPTION
**Pull request by bmrodrigues**
URI corrected to MDE one --> securitycenter.windows.com

### CODE REVIEW

**Comment by bmrodrigues** [comment]
URI's wasn't correct

**Comment by adirdidi** [comment]
The URLs are correct, @mjcaparas please don't merge.

**Comment by yogkumgit** [comment]
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by adirdidi** [comment]
Repeating, the URLs are correct.
@mjcaparas Do **NOT** merge it, thanks.

**Pull request closed without merging**
