### PR TITLE
Update customizing.md

### PR DESCRIPTION
**Pull request by bmathew17**
Update intro

### CODE REVIEW

**Comment by jaimeo** [comment]
A problem with the way this is worded is that it basically says that MMD only provides those benefits on devices that stay up to date. But really, staying up to date is one of the benefits itself.... Also, "modern device" is jargon we are trying to phase out.

**Comment by bmathew17** [comment]
Fair comments. Just wish this would align with other messaging, also "pleasant experience" just sounds out of place here

**Comment by jaimeo** [comment]
Let's work this out internally. There's no reason that things have to be verbatim everywhere as long as the meaning is the same.

**Comment by yogkumgit** [comment]
@jaimeo Please merge this PR. Thanks.

**Comment by jaimeo** [comment]
Again, we'll work this out internally. If the contributor is a Microsoft person, please come to my office hours so we can discuss.

**Pull request closed without merging**
