### PR TITLE
Update get-help-support.md

### PR DESCRIPTION
**Pull request by msbemba**
updated the admin center link 

Fixes#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/11394

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@cmcatee-MSFT Please merge this PR. Thanks

**Review by cmcatee-MSFT — CHANGES_REQUESTED** [review]
Replace existing FWLink with https://go.microsoft.com/fwlink/p/?linkid=2024339
Do not use fully-qualified URLs for links.

**Comment by msbemba** [comment]
> Replace existing FWLink with https://go.microsoft.com/fwlink/p/?linkid=2024339 Do not use fully-qualified URLs for links.

Thank you @cmcatee-MSFT, I have made the changes

**Comment by yogkumgit** [comment]
@cmcatee-MSFT Please merge this PR. Thanks

**Review by cmcatee-MSFT — APPROVED** [review]

**Pull request merged**
