### PR TITLE
Update attack-surface-reduction-rules.md

### PR DESCRIPTION
**Pull request by msbemba**
Updated the document as ASR Rules are working against Server 2016

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/6413

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@jweston-1 Please merge this PR. Thanks

**Comment by yogkumgit** [comment]
@jweston-1 Gentle reminder

**Comment by yogkumgit** [comment]
@tiburd Kindly suggest, who can help us here. Thanks

**Comment by jweston-1** [comment]
Won't fix. 
The table containing this information has been changed, moving those columns (Server 2012 and Server 2016) into a separate table, per the product team. Accordingly, this update would conflict with existing 'approved' published content.  - 
Additional note: aforementioned changes already address issue.

**Comment by msbemba** [comment]
Thank you for the udpate.

**Pull request closed without merging**
