### PR TITLE
Update create-and-use-a-template-to-add-users.md

### PR DESCRIPTION
**Pull request by msbemba**
Made changes to the manage templates part that deletion is the only option and no editing allowed.

### CODE REVIEW

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/2069

**Comment by mypil** [comment]
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by mypil** [comment]
@SharS -  PR has been copy edited and is ready for final review. This is based on issue #2069

Thank you.

**Comment by yogkumgit** [comment]
@SharS Awaiting your response. Please revert. Thanks.

**Comment by yogkumgit** [comment]
@SharS  Gentle reminder, Please merge this PR. Thanks

**Comment by yogkumgit** [comment]
@SharS This is pending for a while, please merge this PR. Thanks

**Pull request merged**
