### PR TITLE
Update Onboard-Windows-10-multi-session-device.md

### PR DESCRIPTION
**Pull request by msbemba**
Updated to Azure Virtual desktop

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/5547

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@denisebmsft Please merge this PR. Thanks.

**Comment by yogkumgit** [comment]
@denisebmsft Gentle reminder, please merge this PR. Thanks

**Review by denisebmsft — APPROVED** [review]
Thank you @msbemba

**Pull request merged**
