### PR TITLE
Updated classifier-tc-definitions.md :Added new classifier definitions

### PR DESCRIPTION
**Pull request by ursenha**
Added 12 new Trainable Classifier Definitions

### CODE REVIEW

**Comment by ursenha** [comment]
Please do not complete/merge this PR. Ping me on teams before completing.

**Comment by ursenha** [comment]
> @microsoft-github-policy-service agree [company="{Microsoft}"]

**Comment by chrfox** [comment]
back to ursenha

line 221, I think the incorrect word is being used.  "abiding" is used and I think the term should be "binding"

**Comment by ursenha** [comment]
@microsoft-github-policy-service agree [company="Microsoft"]

**Comment by ursenha** [comment]
@microsoft-github-policy-service agree

**Pull request merged**
