### PR TITLE
Updated some steps in use-dkim-to-validate-outbound-email.md

### PR DESCRIPTION
**Pull request by dariomws**
image

### CODE REVIEW

**Comment by yogkumgit** [comment]
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@MSFTTracyP Please merge this PR. Thanks

**Comment by yogkumgit** [comment]
@MSFTTracyP Gentle reminder.

**Comment by chrisda** [comment]
Closing this PR as that section was already updated as part of the "deep link" fixes.

**Pull request closed without merging**
