### PR TITLE
Update advanced-hunting-devicelogonevents-table.md

### PR DESCRIPTION
**Pull request by msbemba**
Made changes to the remote IP description as it is the IP address the connection is coming from

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/7378

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@schmurky Please merge this PR. Thanks

**Comment by DulceMontemayor** [comment]
@yogkumgit please update the base branch and resubmit. @schmurky please validate before i merge. Thanks!

**Comment by yogkumgit** [comment]
@msbemba

**Comment by schmurky** [comment]
Hello I am checking with the PM and will give feedback soon.

**Comment by msbemba** [comment]
@yogkumgit   @schmurky 

I have updated the base branch

**Comment by schmurky** [comment]
I'm still waiting for feedback, sorry

**Comment by yogkumgit** [comment]
@schmurky Awaiting your kind response. Thanks

**Comment by schmurky** [comment]
Hi, Yogesh,

Hopefully I get an answer tomorrow, I followed up.

**Comment by yogkumgit** [comment]
@schmurky Please update, Thanks

**Review by schmurky — CHANGES_REQUESTED** [review]
please change to 
**IP address of the device from which the logon attempt was performed**

**Comment by msbemba** [comment]
@schmurky I have made the requested changes.

**Pull request merged**
