### PR TITLE
Update identity-access-logical-architecture-teams.png

### PR DESCRIPTION
**Pull request by msbemba**
Corrected the identity-access-logical-architecture-teams.png file with Microsoft365 instead of O365

### CODE REVIEW

**Comment by denisebmsft** [comment]
Hi @chrfox. If you are not the right person to review the identity-access-logical-architecture-teams.png file that is part of this pull request, please loop that person in as well.

**Comment by yogkumgit** [comment]
@chrfox Please merge this PR. Thanks

**Comment by yogkumgit** [comment]
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

**Review by JohanFreelancer9 — APPROVED** [review]
No copy to review.

**Comment by chrfox** [comment]
This is not me, I don't even know what topic this is in

**Comment by chrfox** [comment]
This goes to Teams, HeidiP

**Comment by msbemba** [comment]
Thanks @chrfox  This PR fixes the Media file which has office365 groups instead of Microsoft 365 groups.

**Comment by yogkumgit** [comment]
@MicrosoftHeidi Please merge this PR. Thanks.

**Comment by MicrosoftHeidi** [comment]
I have no idea what this file is, or where it's come from, or what it's doing. I own no content in Microsoft-365-docs that I'm aware of, literally not my repository to work in.

**Comment by msbemba** [comment]
@dstrome Can you Help with Merging this PR? It fixes the Media file which has the wording office365 groups instead of Microsoft 365 groups.

**Comment by BrendaCarter** [comment]
the updated png looks good. what is the xls?

**Comment by msbemba** [comment]
@BrendaCarter The XLS is to be merged on a different PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2532. Please merge only the Png file.

Thanks
Sri

**Pull request merged**
