### PR TITLE
Update mac-whatsnew.md

### PR DESCRIPTION
**Pull request by msbemba**
Updated release and publish dates for Nov and Oct. Could not find details for august build

Fixes #https://github.com/MicrosoftDocs/microsoft-365-docs/issues/10284

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by msbemba** [comment]
@Dansimp I could not find the details for two builds -101.82.21 and 101.78.13. The remaining dates are updated.

**Comment by kash1064** [comment]
Hello @msbemba .
Thanks for your quickly support.

I had confirmed we could upgrade MDE to 101.87.30 on Current channel at least Nov.14/2022.
So I think these contents in this pull request is not correctly.

Could you confirm that?
Best regards.

**Comment by msbemba** [comment]
Nov 5 is the date it was made available. Are you saying you could not do it until Nov 14th ?

**Comment by kash1064** [comment]
> Nov 5 is the date it was made available. 

Thanks.  I found this PR has future date.(Nov 25, 2022).
I thought this is wrong date, because I did upgrade MDE to 101.87.30 at 11/14.

Best regards.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by msbemba** [comment]
> > Nov 5 is the date it was made available.
> 
> Thanks. I found this PR has future date.(Nov 25, 2022). I thought this is wrong date, because I did upgrade MDE to 101.87.30 at 11/14.
> 
> Best regards.

Got it. That has been fixed now.

**Comment by kash1064** [comment]
Hello msbemba.
Thanks for your kind support !!
Best regards.

**Comment by yogkumgit** [comment]
@Dansimp Please merge this PR. Thanks

**Pull request merged**
