### PR TITLE
Updated 24hrs PDL sync SLA to 48 hrs

### PR DESCRIPTION
**Pull request by chhaya-sharma9**

### CODE REVIEW

**Comment by yogkumgit** [comment]
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by MikePlumleyMSFT** [comment]
@AdwoodMicrosoft can you confirm?

**Comment by yogkumgit** [comment]
@AdwoodMicrosoft Please reply.

**Comment by MikePlumleyMSFT** [comment]
Duplicate of [5384](https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5384)

**Pull request closed without merging**
