### PR TITLE
Update microsoft-defender-antivirus-windows.md

### PR DESCRIPTION
**Pull request by msbemba**
Made changes to the navigation as manage providers would be a better place to check the status of Microsoft defender antivirus.

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/9104

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@denisebmsft Please merge this PR. Thanks

**Review by denisebmsft — APPROVED** [review]
Thank you @msbemba @JohanFreelancer9 @yogkumgit

**Pull request merged**
