### PR TITLE
Update set-up-compliance-boundaries.md

### PR DESCRIPTION
**Pull request by msbemba**
updated New-ComplianceSecurityFilter with action parameter

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/6803

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@markjjo Please merge this PR. Thanks

**Comment by markjjo** [comment]
Closing. Action parameter not required. All actions added by default, which is why examples don't include this parameter.

**Pull request closed without merging**
