### PR TITLE
Update dlp-policy-reference.md

### PR DESCRIPTION
**Pull request by edmatosm**
Updating information about the required role to setup encryption. If the admin does not have the required role, they will not see any available encryption options. As per https://o365exchange.visualstudio.com/IP%20Engineering/_workitems/edit/3189465

### CODE REVIEW

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@chrfox Please merge this PR. Thanks

**Comment by chrfox** [comment]
confirming

**Comment by chrfox** [comment]
query out to PG for confirmation

**Comment by yogkumgit** [comment]
@edmatosm Thanks for your feedback! New issues and pull requests for this content are closed while we update this content to support upcoming feature improvements.

**Comment by edmatosm** [comment]
[like]  Eduardo Marques reacted to your message:
________________________________

**Pull request closed without merging**
