### PR TITLE
Added another alternative

### PR DESCRIPTION
**Pull request by mahage-msft**
@markjjo - This one will need some extra massaging, my grammars are horrible :)

### CODE REVIEW

**Comment by mypil** [comment]
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

**Comment by markjjo** [comment]
@mypil @johanfreelancer9 No need for Johan to copy edit. I have to review/revise and will take care of it.

**Comment by markjjo** [comment]
@mahage-msft I don't understand the scenario this is trying to address? The functionality is to copy messages to another mailbox but the alternative fix is to assign permissions to a mailbox. Can provide an example/explanation in email to me? I guess I don't understand how the legacy tool was being used and granting access to another user's mailbox seems like a security/privacy issue?

**Comment by markjjo** [comment]
@mahage-msft Thanks for the help with this. Will you please review my edits and revise as necessary? Thanks!

**Pull request merged**
