### PR TITLE
added option with Microsoft 365 E3

### PR DESCRIPTION
**Pull request by MaratMussabekov**
#1157

### CODE REVIEW

**Comment by mypil** [comment]
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by mypil** [comment]
@mjcaparas - PR has been copy edited and is ready for final review. This is based on issue #1157.
 
Thank you.

cc: @kenwith

**Comment by mjcaparas** [comment]
No. Do not add this line. I have added it before and it has generated support calls. Such SKU does not exist.

**Comment by MaratMussabekov** [comment]
Hello @mjcaparas,
thank you, but could you please clarify, **Identity & Threat Protection** is not being sold anymore? Am I understanding it correctly?
I am asking because there are still references to this product in documentation (like it was mentioned in #1157)
Thank you

**Comment by mypil** [comment]
@mjcaparas - Can you please assist to answer the query of MaratMussabekov?  

Please advise if another PR needs to be created or how we should respond to the customer so we can close issue #1157. Thank you.

cc: @kenwith

**Comment by mjcaparas** [comment]
It might still be sold, but in the context of the licensing page specifically for Microsoft Defender ATP, I'm not sure that it's applicable.

**Comment by MaratMussabekov** [comment]
Hello @mjcaparas,
thank you for clarification, but does it mean that the Tip about Identity & Threat Protection must be removed from [Office 365 Advanced Threat Protection](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/office-365-atp) article?
Because it is confusing: in [Office 365 Advanced Threat Protection](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/office-365-atp) it says that Microsoft E3 + Identity & Threat Protection is enough and in [Microsoft Threat Protection prerequisites](https://docs.microsoft.com/en-us/microsoft-365/security/mtp/prerequisites) it says that E5 license is required
Thank you

**Pull request closed without merging**
