### PR TITLE
Update prepare-tls-1.2-in-office-365.md

### PR DESCRIPTION
**Pull request by WorkShay**
Added staged rollout info

### CODE REVIEW

**Comment by yogkumgit** [comment]
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@WorkShay Please merge this PR. Thanks.

**Comment by WorkShay** [comment]
I don't have permissions to merge this PR. Please assign someone who is able to.

**Comment by yogkumgit** [comment]
@WorkShay Can you suggest who can merge this PR. Thanks in advance for your help.

**Comment by WorkShay** [comment]
KC Cross or someone else who @Meera<mailto:meerak@microsoft.com> can recommend.

Shayna

**Pull request merged**
