### PR TITLE
Incorrect platform in the image

### PR DESCRIPTION
**Pull request by sccmentor**
The section talks about iOS onboarding of devices into MDE, however the image in the section below is a Windows 10 device. Can the image be altered to show an iOS device and be reflective of the content being discussed.

3. Upon successful onboarding, the device will start showing up on the Devices list in the Microsoft 365 Defender portal.

    > [!div class="mx-imgBorder"]
    > :::image type="content" source="images/device-inventory-screen.png" alt-text="The Device inventory page" lightbox="images/device-inventory-screen.png":::

### CODE REVIEW

**Comment by yogkumgit** [comment]
@JohanFreelancer9

**Review by JohanFreelancer9 — COMMENTED** [review]
@yogkumgit, the submitter should have raised an issue and not opened a PR. Could you please help to resolve the issue before I can do a copy edit? Thanks.

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@yogkumgit  Do we know which document should be fixed? I'll be able to work on it once I have the document that needs the updated Image.

**Comment by yogkumgit** [comment]
@sccmentor as guided, please open an issue and link it with the document name. We will look into that issue and implement your feedback after review. We proceed here to close this PR. Thanks.

**Pull request closed without merging**
