### PR TITLE
Update index.yml

### PR DESCRIPTION
**Pull request by cnwolisa**
change the content link to be consistent with the page header

### CODE REVIEW

**Comment by yogkumgit** [comment]
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

**Comment by tiburd** [comment]
@cnwolisa 
Thank you for your submission.
The title is intentionally parallel with other titles in the index list instead of exactly matching the header of the page it links to.

**Comment by cnwolisa** [comment]
@tiburd not sure I understand why this PR was closed without being merged? The change is to the text from "Upload" to "Uploading" and yes I get the rationale for the titles not matching, the title Upload is quite misleading and was flagged by our customer. 
I am open to suggestion on what to rename the header of the page to but the index list title needs to change to remove the ambiguity it communicates.

**Comment by tiburd** [comment]
@cnwolisa 
Per Microsoft style, index entries do not have to match the titles of the pages that they link to.
If you are a Microsoft employee, please complete your [account setup](https://review.docs.microsoft.com/en-us/help/contribute/contribute-get-started-setup-github?branch=main).
Thanks!

**Pull request closed without merging**
