### PR TITLE
Update advanced-hunting-query-emails-devices.md

### PR DESCRIPTION
**Pull request by msbemba**
Added Device name and Device ID to DeviceFileEvents query to receive the values in the last project statement.

### CODE REVIEW

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/5814

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@schmurky Please merge this PR. Thanks

**Comment by yogkumgit** [comment]
@schmurky Please recheck, Pull status is still "Open"

**Pull request merged**
