### PR TITLE
Update get-vuln-by-software.md

### PR DESCRIPTION
**Pull request by msbemba**
Updated permissions on the document.

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/6061

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@siosulli Please merge this PR. Thanks

**Comment by yogkumgit** [comment]
@siosulli Gentle reminder

**Pull request merged**
