### PR TITLE
Update Onboard-Windows-10-multi-session-device.md

### PR DESCRIPTION
**Pull request by msbemba**
Added  document on how to add exclusions for Microsoft defender using PowerShell

### CODE REVIEW

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/4972

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@Dansimp Please merge this PR. Thanks.

**Comment by yogkumgit** [comment]
@Dansimp Gentle reminder, please merge this PR. Thanks.

**Pull request merged**
