### PR TITLE
Fixed a typo where link text was repeated in about-admin-roles.md

### PR DESCRIPTION
**Pull request by AntoniaBlume**
Fixed typo where link text was repeated at the end of paragraph 3.

### CODE REVIEW

**Comment by yogkumgit** [comment]
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@kwekuako Please merge this PR. Thanks.

**Comment by msbemba** [comment]
@kwekuako Looks like this has been fixed already in the document. So this PR can be closed. CC: @yogkumgit

**Comment by kwekuako** [comment]
Bug already fixed.

**Pull request closed without merging**
