### PR TITLE
Update create-and-manage-inactive-mailboxes.md

### PR DESCRIPTION
**Pull request by kellybos**
Inactive mailboxes are retained for 183 days after a hold is removed. The contents in this article need to make this difference between soft-deleted mailboxes (that were never Inactive) clear. Confirmed with Le-Wu Tung that this content should be updated and triaged by appropriate PM team.

### CODE REVIEW

**Comment by yogkumgit** [comment]
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@markjjo

**Comment by kellybos** [comment]
Can someone with the right access resolve this conflict? Mailboxes that were previously on hold will be available for 183 days, not 30 days. This article needs to have the correct information reflected to avoid escalations.

**Comment by markjjo** [comment]
@kellybos PR merged. Sorry for the delay.

**Pull request merged**
