### PR TITLE
Request removal of registry change speed up downloads.

### PR DESCRIPTION
**Pull request by marstev**
Removing references to using registry speed up downloads and adding additional suggestions to help with exporting process. Adding @markjjo regarding removal of this doc also. https://docs.microsoft.com/en-us/microsoft-365/compliance/increase-download-speeds-when-exporting-ediscovery-results?view=o365-worldwide.

### CODE REVIEW

**Comment by marstev** [comment]
@markjjo requesting removal of https://docs.microsoft.com/en-us/microsoft-365/compliance/increase-download-speeds-when-exporting-ediscovery-results?view=o365-worldwide also. Thanks.

**Comment by markjjo** [comment]
@marstev Please take a quick look at my revisions and let me know if they are ok or revise as necessary. You can click the Files tab and review the text in green. Here are the bullets I changed:

- We recommend downloading search results to a local computer. However, to eliminate your company's firewall or proxy infrastructure from causing issues when downloading search results, you might consider downloading search results to a virtual desktop outside of your network. This may decrease timeouts that occur in Azure data connections when exporting a large number of files. For more information about virtual desktops, see [Windows Virtual Desktop](https://azure.microsoft.com/services/virtual-desktop). 

- To improve performance when downloading search results, consider dividing searches that return a large set of results into smaller searches. For example, you can use date ranges in search queries to return a smaller set of results that can be downloaded faster.

**Comment by marstev** [comment]
> @marstev Please take a quick look at my revisions and let me know if they are ok or revise as necessary. You can click the Files tab and review the text in green. Here are the bullets I changed:
> 
> * We recommend downloading search results to a local computer. However, to eliminate your company's firewall or proxy infrastructure from causing issues when downloading search results, you might consider downloading search results to a virtual desktop outside of your network. This may decrease timeouts that occur in Azure data connections when exporting a large number of files. For more information about virtual desktops, see [Windows Virtual Desktop](https://azure.microsoft.com/services/virtual-desktop).
> * To improve performance when downloading search results, consider dividing searches that return a large set of results into smaller searches. For example, you can use date ranges in search queries to return a smaller set of results that can be downloaded faster.

This looks great.

**Comment by markjjo** [comment]
@marstev Thanks for reviewing! PR merged. I will reply to thread when updated topic is live

**Pull request merged**
