### PR TITLE
Update what-if-my-subscription-expires.md

### PR DESCRIPTION
**Pull request by msbemba**
The grace period of 30 days is similar to the expired state as Trial users also retain data during the grace period just like the expired state. I have made changes to reflect the same. Let me know if this is correct.

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/4562

**Review by JohanFreelancer9 — APPROVED** [review]
Copy is fine.

**Comment by yogkumgit** [comment]
@cmcatee-MSFT Please merge this PR. Thanks

**Comment by cmcatee-MSFT** [comment]
This issue has been addressed in another PR. This change is no longer needed.

**Pull request closed without merging**
