### PR TITLE
Update device-onboarding-offboarding-macos-intune.md

### PR DESCRIPTION
**Pull request by tewchen**

### CODE REVIEW

**Comment by tewchen** [comment]
@chrfox

**Comment by chrfox** [comment]
@tewchen 
This cannot be merged as is. I don't understand what you mean by "one of the highlight variables should be not emtpy:" And you need to send me the .png file, it cannot be embedded the way you have it.

**Comment by yogkumgit** [comment]
@tiburd Please help. Thanks

**Comment by tiburd** [comment]
Closing this PR.

@tewchen 
If you need to reopen this PR, please use the private repo and provide the required info stated above.

Thanks!

**Pull request closed without merging**
