### PR TITLE
Update recover-an-inactive-mailbox.md

### PR DESCRIPTION
**Pull request by msbemba**
Updated the document to reflect what happens **ExternalDirectoryObjectId** property is null or has value

### CODE REVIEW

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/8893

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@cabailey Please merge this PR. Thanks

**Comment by cabailey** [comment]
#sign-off for typo fix

**Pull request merged**
