### PR TITLE
Update loop-workspaces-configuration.md

### LINKED ISSUE #12895: Outdated license requirements?
Is this really true? 

> Loop workspaces currently require each user to have an Exchange Online license

1. Loop Workspaces are backed by Syntex repository services, which is powered by SharePoint. Why an Exchange Online license instead of a SharePoint Plan?
2. Recently you added a Microsoft Loop (Workspaces) service plan to M365 E5, E3, Business Premium and Business Standard licenses. I can also enable the Loop service plan even if Exchange or SharePoint service plan is disabled. 

It seems the license information on that page are outdated.

Best regards
Tobias

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 093c11ef-791c-c4bd-71e6-c3e6ecc347e1
* Version Independent ID: 093c11ef-791c-c4bd-71e6-c3e6ecc347e1
* Content: [Manage Loop workspaces in Syntex repository services](https://learn.microsoft.com/en-us/microsoft-365/loop/loop-workspaces-configuration?view=o365-worldwide)
* Content Source: [microsoft-365/loop/loop-workspaces-configuration.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/loop/loop-workspaces-configuration.md)
* Service: **sharepoint-online**
* GitHub Login: @v-smandalika
* Microsoft Alias: **v-smandalika**

### PR DESCRIPTION
**Pull request by msbemba**
Checked the recent Service that has been added( Loopwith workspace service plan)

Fixes https://github.com/MicrosoftDocs/microsoft-365-docs/issues/12895

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@v-smandalika Please merge this PR. Thanks

**Comment by chuckedmonson** [comment]
@MikePlumleyMSFT

**Comment by MikePlumleyMSFT** [comment]
@dancontoso can you review?

**Pull request merged**
