### PR TITLE
Update retention-policy-timings.png

### PR DESCRIPTION
**Pull request by msbemba**
Changed diagram to fix terminology (Consistent)

synced is changed to distributed and the status is changed to Enabled (Success) as seen in the portal

### CODE REVIEW

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/8262

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by cabailey** [comment]
Investigating

**Comment by cabailey** [comment]
These are good suggestions now the UI is updated, but I couldn't accept the file because it doesn't meet our accessibility requirements and would be inconsistent with the other diagrams for retention label timings. These are now updated, so closing this PR. For future reference, this would have been better as a GitHub Issue.

**Pull request closed without merging**
