### PR TITLE
Update managing-holds.md

### PR DESCRIPTION
**Pull request by msbemba**
made changes to the navigations as it is under ediscovery-->Premium

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by msbemba** [comment]
issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/9963

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@robmazz Please merge this PR. Thanks

**Comment by yogkumgit** [comment]
@robmazz Gentle reminder

**Comment by robmazz** [comment]
@msbemba - thanks, this also needs to be updated in several other topics. Making those updates in a separate PR.

**Pull request closed without merging**
