### PR TITLE
Update configure-extension-file-exclusions-microsoft-defender-antivir…

### PR DESCRIPTION
**Pull request by msbemba**
…us.md

Fixed the redirect to this for %LOCALAPPDATA%

per Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/9684

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Review by JohanFreelancer9 — APPROVED** [review]

**Review by denisebmsft — APPROVED** [review]
Thank you @msbemba

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@yogkumgit Validation has been passed.

Author has approved the changes

**Comment by yogkumgit** [comment]
@tiburd Please merge this PR. Thanks

**Pull request merged**
