### PR TITLE
Update recommended-settings-for-eop-and-office365.md

### PR DESCRIPTION
**Pull request by ssaini-pm**
The default action for “Safe Attachments unknown malware response” should be Block.

### CODE REVIEW

**Comment by yogkumgit** [comment]
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@MSFTTracyP Please merge this PR. Thanks

**Comment by yogkumgit** [comment]
@MSFTTracyP Gentle reminder

**Comment by chrisda** [comment]
@ssaini-pm, fortunately, I confirmed all of this yesterday based on other work I was doing in the UI and a recent cmdlet topic issue <https://github.com/MicrosoftDocs/office-docs-powershell/issues/8045>.

When you create a new Safe Attachments policy in the M365 Defender portal, the default value in the wizard is **Off**. 100% no doubt about this. I observed it just yesterday.

When you create a new Safe Attachments policy in PowerShell (New-SafeAttachmentPolicy), the default value of the _Action_ parameter is `Block`, but the value of the _Enable_ parameter is `$false`, which corresponds to **Off** in the UI.

The `-Enable $false` combination renders the value of the _Action_ parameter meaningless. The _Action_ parameter value only matters when the _Enable_ parameter is `$true` (the default value is `$false`).

That's what I've observed and what is documented in that other GitHub issue. If your change is related to a fix or something that is about to go live, please let me know.

Closing

**Pull request closed without merging**
