### PR TITLE
Update buy-or-edit-an-add-on.md

### PR DESCRIPTION
**Pull request by msbemba**
Made changes to MS Defender ATP availability -reference  https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-advanced-threat-protection-service-description

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/3596

**Comment by lukedaemon** [comment]
Hello @msbemba,
maybe I'm doing it wrong, but I see different information regarding Microsoft Defender for Office 365 and plans:

- [Microsoft Defender for Office 365 service description](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-advanced-threat-protection-service-description): It can be added to **Microsoft 365 Business Standard** plan (for example)
- [Buy or edit an add-on](https://docs.microsoft.com/en-us/microsoft-365/commerce/buy-or-edit-an-add-on?view=o365-worldwide#remove-an-add-on): it is available to **Office 365 Enterprise E1, E3, E4** only, not Microsoft 365 Business Standard.

So what I miss ?

Thank you,
Luca

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by msbemba** [comment]
@

> Hello @msbemba,
> maybe I'm doing it wrong, but I see different information regarding Microsoft Defender for Office 365 and plans:
> 
> * [Microsoft Defender for Office 365 service description](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-advanced-threat-protection-service-description): It can be added to **Microsoft 365 Business Standard** plan (for example)
> * [Buy or edit an add-on](https://docs.microsoft.com/en-us/microsoft-365/commerce/buy-or-edit-an-add-on?view=o365-worldwide#remove-an-add-on): it is available to **Office 365 Enterprise E1, E3, E4** only, not Microsoft 365 Business Standard.
> 
> So what I miss ?
> 
> Thank you,
> Luca

You are doing it right. The document needs to be updated, so I have this Pull request in place to update it.

**Comment by yogkumgit** [comment]
@cmcatee-MSFT Please merge this PR. Thanks.

**Comment by cmcatee-MSFT** [comment]
The table in question has been removed from the article.

**Pull request closed without merging**
