### PR TITLE
Update minimum-requirements.md

### PR DESCRIPTION
**Pull request by msbemba**
updated minimum requirements to reflect 2019 core edition

### CODE REVIEW

**Comment by msbemba** [comment]
issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/9858

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by kotras** [comment]
Thx for the update. I will check when the document reflects the changes.

**Comment by yogkumgit** [comment]
@mjcaparas Please merge this PR. Thanks

**Pull request merged**
