### PR TITLE
Update tls-1.0-and-1.1-deprecation-for-office-365.md

### PR DESCRIPTION
**Pull request by msbemba**
added WinHTTP value for TLS 1.3

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by msbemba** [comment]
issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/9017

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@WorkShay Please merge this PR. Thanks

**Comment by yogkumgit** [comment]
@WorkShay Gentle reminder. Thanks

**Pull request merged**
