### PR TITLE
Update communication-compliance-configure.md

### PR DESCRIPTION
**Pull request by MitsuhiroTakemoto**
According to the past escalation, 24 hours is not correct regarding Teams. 
48 hours should be correct.

### CODE REVIEW

**Comment by yogkumgit** [comment]
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@robmazz Please merge this PR. Thanks.

**Comment by robmazz** [comment]
@MitsuhiroTakemoto - thanks for the feedback. Going to close this PR and include your suggestion along with another clarification in this sentence in a new PR. Email is 24 hours, while Teams, Yammer and other 3-party services are 48 hours.

**Comment by MitsuhiroTakemoto** [comment]
Thanks a lot 😊

Best regards,
Mitsuhiro

**Pull request closed without merging**
