### PR TITLE
Update subscriptions-and-licenses.md

### PR DESCRIPTION
**Pull request by michaelcurnutt**

### CODE REVIEW

**Comment by yogkumgit** [comment]
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@michaelcurnutt Please implement the suggested changes, if you agree. Thanks

**Comment by yogkumgit** [comment]
@michaelcurnutt Gentle reminder

**Comment by yogkumgit** [comment]
@tiburd Please take an appropriate action to resolve this PR. Thanks

**Comment by tiburd** [comment]
@michaelcurnutt 
Thanks for your contribution, Michael!

When you get a chance, please complete your GitHub account setup so that it's "connected":

- [Office authoring guide - getting started - set up accounts](https://review.docs.microsoft.com/en-us/help/contribute/contribute-get-started-setup-github?branch=main)

Thanks!

**Pull request merged**
