### PR TITLE
Updating records page to clarify licensing

### PR DESCRIPTION
**Pull request by robertoyms**
We've realized that it wasn't clear from the documentation that declaring an item as a record with retention labels requires E5-level licensing. Adding a note to clarify this.

### CODE REVIEW

**Comment by mypil** [comment]
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by mypil** [comment]
@cabailey - PR has been copy edited and is ready for final review. 

Thank you.

cc: @kenwith

**Comment by cabailey** [comment]
@robertoyms  Thanks for making this clarification!  To avoid ambiguity with other licenses that might be required to edit content, should be it "don't require this license"?

**Comment by robertoyms** [comment]
Yes that works.

Roberto.

**Comment by cabailey** [comment]
@robertoyms  I don't see the additional clarifying words added yet, so for expediency, I'll merge this & do another PR myself to complete the sentence so it can live today.

**Pull request merged**
