### PR TITLE
Update create-ediscovery-holds.md

### PR DESCRIPTION
**Pull request by msbemba**
Made changes to the important Tag as cloud-based storage area is created in a hybrid scenrio

### CODE REVIEW

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/4488

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@markjjo Please merge this PR. Thanks.

**Comment by markjjo** [comment]
Revised comment and merged PR

**Pull request merged**
