### PR TITLE
Update linux-install-manually.md

### PR DESCRIPTION
**Pull request by msbemba**
Corrected the PROD repo for both Oracle 8.0-8.5 and Oracle 7.2-7.9

### CODE REVIEW

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/8958

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@Dansimp Please merge this PR. Thanks

**Comment by yogkumgit** [comment]
@Dansimp Gentle reminder. Thanks

**Pull request merged**
