### PR TITLE
Update dlp-configure-view-alerts-policies.md

### PR DESCRIPTION
**Pull request by msbemba**
Added Education licenses have access to DLP

https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/microsoft-365-education

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/8539

**Comment by msbemba** [comment]
@chrfox  As per https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/microsoft-365-education Education licenses have option to access DLP

Please verify and approve

**Comment by thewrabbit** [comment]
I don't believe the update is correct.

The update reads
- **Single-event alert configuration**: Organizations that have an E1, F1, or G1 subscription or an E3 or G3 subscription can create alert policies only where an alert is triggered every time an activity occurs.
- **Aggregated alert configuration**: To configure aggregate alert policies based on a threshold, you must have either of the following configurations:
  - An A1, A3 or A5 subscription
  - An E5 or G5 subscription
  - An E1, F1, or G1 subscription or an E3 or G3 subscription that includes one of the following features:
    - Office 365 Advanced Threat Protection Plan 2

I believe it should read as below as A1 and A3 will only have access to Single-event alert configuration unless they have an add in.

- **Single-event alert configuration**: Organizations that have an A1, E1, F1, or G1 subscription or an A3, E3 or G3 subscription can create alert policies only where an alert is triggered every time an activity occurs.
- **Aggregated alert configuration**: To configure aggregate alert policies based on a threshold, you must have either of the following configurations:
  - An A5 subscription
  - An E5 or G5 subscription
  - An A1, E1, F1, or G1 subscription or an A3, E3 or G3 subscription that includes one of the following features:
    - Office 365 Advanced Threat Protection Plan 2
    -

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by msbemba** [comment]
@thewrabbit The changes have been made to the PR

**Comment by yogkumgit** [comment]
@chrfox Please merge this PR. Thanks

**Comment by yogkumgit** [comment]
@chrfox Gentle reminder. Thanks

**Pull request merged**
