### PR TITLE
Update domains-faq.yml

### PR DESCRIPTION
**Pull request by msbemba**
It is now possible to change the sharepoint domain name - https://docs.microsoft.com/en-us/sharepoint/tenant-rename

Made changes to the document. Please review and approve.

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/5645

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@scotvidican Please merge this PR. Thanks

**Comment by yogkumgit** [comment]
@scotvidican Gentle reminder

**Comment by yogkumgit** [comment]
closing as per author's comment.

**Pull request closed without merging**
