### PR TITLE
Video redirects 2

### PR DESCRIPTION
**Pull request by lhcole613**

### CODE REVIEW

**Comment by officedocspr** [comment]
## STOP  Caution: Large pull request

This **public** repo applies limits on the number of files that can be merged in a single pull request (PR):

- **Warning** Warning message and ability to unblock PR using the *Merge large pull request*<sup>\*</sup> label - 30
- **Block** Block message and PR is blocked - 100

This pull request will change **49** files, which exceeds the **warning** limit of **30**.

Before this pull request can be merged, you must review the list of files it contains and their changes to confirm they are correct and intentional. **This includes files you did not change and/or do not own**. If there are changes you aren't familiar with, contact the individuals who submitted the commits included in this pull request and review the changes with them.

**The individual who merges this pull request is responsible for ensuring the changes included in it are correct, and for resolving any issues that might result in merging it.**

### To merge this pull request

If you have determined that the changes in this pull request are correct, add the **Merge large pull request**<sup>\*</sup> label to it, wait for the **max/pr-file-count** check to pass, and then click **Merge**. To add a label, click the gear icon next to **Labels** and then select **Merge large pull request**<sup>\*</sup>.

Label UI screenshot

### To reject this pull request

If you can't confirm the changes in this pull request are correct, click **Close pull request** at the bottom of this page to close it without merging. Work with your team to revert any changes that aren't correct.

<sup>\*</sup> You must have write or triage access to this repo to add labels.

**Comment by officedocspr** [comment]
## STOP  Caution: Large pull request

This **public** repo applies limits on the number of files that can be merged in a single pull request (PR):

- **Warning** Warning message and ability to unblock PR using the *Merge large pull request*<sup>\*</sup> label - 30
- **Block** Block message and PR is blocked - 100

This pull request will change **49** files, which exceeds the **warning** limit of **30**.

Before this pull request can be merged, you must review the list of files it contains and their changes to confirm they are correct and intentional. **This includes files you did not change and/or do not own**. If there are changes you aren't familiar with, contact the individuals who submitted the commits included in this pull request and review the changes with them.

**The individual who merges this pull request is responsible for ensuring the changes included in it are correct, and for resolving any issues that might result in merging it.**

### To merge this pull request

If you have determined that the changes in this pull request are correct, add the **Merge large pull request**<sup>\*</sup> label to it, wait for the **max/pr-file-count** check to pass, and then click **Merge**. To add a label, click the gear icon next to **Labels** and then select **Merge large pull request**<sup>\*</sup>.

Label UI screenshot

### To reject this pull request

If you can't confirm the changes in this pull request are correct, click **Close pull request** at the bottom of this page to close it without merging. Work with your team to revert any changes that aren't correct.

<sup>\*</sup> You must have write or triage access to this repo to add labels.

**Comment by lhcole613** [comment]
@pebaum Video redirects as per email.

FREELANCERS: Please do NOT merge.

**Comment by garycentric** [comment]
@lhcole613 , @pebaum 

This PR has created the following errors in the sync PR to the private repo. Please submit another PR to address these issues.

<a id="a8f2a63f2a67f506c881c8621af9e49f-b8ab0520"></a>
### [.openpublishing.redirection.json](https://github.com/MicrosoftDocs/microsoft-365-docs-pr/blob/repo_sync_working_branch/.openpublishing.redirection.json)
 - **Line 6125, Column 71**: **[Error: redirection-conflict]** `````The 'business-video/set-up-a-new-business-email-address.md' appears twice or more in the redirection mappings.`````

<a id="5bf3553dec56a0dad72185c076a638d7-b8ab0520"></a>
### [microsoft-365/admin/security-and-compliance/increase-threat-protection.md](https://github.com/MicrosoftDocs/microsoft-365-docs-pr/blob/repo_sync_working_branch/microsoft-365/admin/security-and-compliance/increase-threat-protection.md)
 - **Line 214, Column 29**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'increase-threat-protection'.`````

<a id="47ccfb2f4130bc5907491cf0658e3262-b8ab0520"></a>
### [microsoft-365/admin/security-and-compliance/secure-your-business-data.md](https://github.com/MicrosoftDocs/microsoft-365-docs-pr/blob/repo_sync_working_branch/microsoft-365/admin/security-and-compliance/secure-your-business-data.md)
 - **Line 47, Column 4**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#setup' in 'admin/security-and-compliance/secure-your-business-data.md'.`````
 - **Line 48, Column 4**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#train' in 'admin/security-and-compliance/secure-your-business-data.md'.`````
 - **Line 49, Column 4**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#admin' in 'admin/security-and-compliance/secure-your-business-data.md'.`````
 - **Line 50, Column 4**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#malware' in 'admin/security-and-compliance/secure-your-business-data.md'.`````
 - **Line 51, Column 4**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#ransomware' in 'admin/security-and-compliance/secure-your-business-data.md'.`````
 - **Line 52, Column 4**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#forwarding' in 'admin/security-and-compliance/secure-your-business-data.md'.`````
 - **Line 53, Column 4**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#encryption' in 'admin/security-and-compliance/secure-your-business-data.md'.`````
 - **Line 54, Column 4**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#phishing' in 'admin/security-and-compliance/secure-your-business-data.md'.`````
 - **Line 55, Column 4**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#atp' in 'admin/security-and-compliance/secure-your-business-data.md'.`````
 - **Line 56, Column 5**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#phishingatp' in 'admin/security-and-compliance/secure-your-business-data.md'.`````
 - **Line 119, Column 229**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'increase-threat-protection'.`````
 - **Line 145, Column 41**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'increase-threat-protection'.`````
 - **Line 241, Column 70**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'increase-threat-protection'.`````
 - **Line 310, Column 30**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'increase-threat-protection'.`````

<a id="5a0fe5eb383f4b9b471806345d2a09e6-b8ab0520"></a>
### [microsoft-365/business-video/TOC.yml](https://github.com/MicrosoftDocs/microsoft-365-docs-pr/blob/repo_sync_working_branch/microsoft-365/business-video/TOC.yml)
 - **Line 129, Column 17**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'turn-on-mfa.md'.`````

<a id="da165b939f9e7524218b9be5c2871da4-b8ab0520"></a>
### [microsoft-365/admin/setup/signup--apps-business.md](https://github.com/MicrosoftDocs/microsoft-365-docs-pr/blob/repo_sync_working_branch/microsoft-365/admin/setup/signup--apps-business.md)
 - **Line 64, Column 3**: **[Suggestion: column-header-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/column-header-missing?branch=main)]** `````Column headers are required for tables. Add appropriate header text, or remove any extra table cells that cause an extra column.`````

<a id="d145efefb4de48592afee1321f9ddb41-b8ab0520"></a>
### [microsoft-365/admin/simplified-signup/signup-business-standard.md](https://github.com/MicrosoftDocs/microsoft-365-docs-pr/blob/repo_sync_working_branch/microsoft-365/admin/simplified-signup/signup-business-standard.md)
 - **Line 66, Column 3**: **[Suggestion: column-header-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/column-header-missing?branch=main)]** `````Column headers are required for tables. Add appropriate header text, or remove any extra table cells that cause an extra column.`````

**Pull request merged**
