### PR TITLE
Update attack-surface-reduction-faq.yml

### PR DESCRIPTION
**Pull request by msbemba**
Per the lastest update https://docs.microsoft.com/en-us/mem/configmgr/hotfix/2111/12896009#:~:text=The%20Configuration%20Manager%20console%20now%20allows%20wildcards%20when%20defining%20Microsoft%20Defender%20Attack%20Surface%20Reduction%20(ASR)%20rules Microsoft endpoint configuration manager supportswildcards

### CODE REVIEW

**Comment by msbemba** [comment]
Per issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/9675

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@jweston-1 Please merge this PR. Thanks

**Comment by jweston-1** [comment]
looks good. merging.

**Pull request merged**
