### PR TITLE
Noting ingestion_time() vs. Timestamp

### PR DESCRIPTION
**Pull request by mjmelone**
Using the Timestamp field in custom detections can result in data loss if an endpoint queues an event. In reality customers likely won't need time-based filters in custom detections as they are pre-filtered.

### CODE REVIEW

**Comment by yogkumgit** [comment]
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

**Comment by schmurky** [comment]
Hi! currently discussing this edit offline with PM. Will update this thread for necessary updates, if any. Please hold. @yogkumgit @JohanFreelancer9

**Comment by yogkumgit** [comment]
@schmurky Any update?

**Comment by schmurky** [comment]
Yes, apologies for late update. This has been resolved by adding this note
Avoid filtering custom detections using the Timestamp column. The data used for custom detections is pre-filtered based on the detection frequency.
to this page: https://docs.microsoft.com/en-us/microsoft-365/security/defender/custom-detection-rules?view=o365-worldwide

**Comment by yogkumgit** [comment]
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

**Comment by schmurky** [comment]
I already added the note. This PR is okay to close. :)

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@schmurky Please merge this PR. Thanks

**Pull request merged**
