### PR TITLE
Update microsoft-defender-endpoint-linux.md

### PR DESCRIPTION
**Pull request by msbemba**
misleading RH versions. Changed it to 6.7 or higher so it includes all  major version (7, 8 or 9)

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/7271

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@mjcaparas Please merge this PR. Thanks. Thanks.

**Comment by mjcaparas** [comment]
No, I have suggested the same change to the PG. There is a distinction between the two bullet points.

**Pull request closed without merging**
