### PR TITLE
Update tune-performance-defender-antivirus.md

### LINKED ISSUE #11507: 'Seconds' parameter for New-MpPerformanceRecording does not exist
The [documentation](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/tune-performance-defender-antivirus?view=o365-worldwide#-seconds) for the `New-MpPerformanceRecording` cmdlet lists the `Sleep` option in the list of parameters for this cmdlet. However, this parameter is not accepted when running this cmdlet and the PS script behind it does not accept or reference this parameter. 

It would be exceptionally helpful for this parameter to exist in order to facilitate non-interactive runs. However, as it does not exist this reference should be removed from the documentation in order to avoid confusion. 

```
Specifies the duration of the performance recording in seconds. This is recommended for users conducting batch collections that require no interaction or prompt.

Type: Int32
Position: Named
Default value: 0
Accept pipeline input: False
Accept wildcard characters: False
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6e075325-c8a9-4152-352f-6399e036c896
* Version Independent ID: 03ff8166-3867-23f1-5dc3-75f603cfe919
* Content: [Performance analyzer for Microsoft Defender Antivirus](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/tune-performance-defender-antivirus?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/tune-performance-defender-antivirus.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/tune-performance-defender-antivirus.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

### PR DESCRIPTION
**Pull request by msbemba**
The second's parameter doesn't seem to work

Fixes https://github.com/MicrosoftDocs/microsoft-365-docs/issues/11507

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Review by JohanFreelancer9 — CHANGES_REQUESTED** [review]
Copy review..

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@yogkumgit  I dont see any changes to make.

**Comment by yogkumgit** [comment]
@JohanFreelancer9

**Review by v-britweston — APPROVED** [review]
Looks good.

**Pull request merged**
