### PR TITLE
Update customizing.md

### PR DESCRIPTION
**Pull request by ElaineAnsell**
Added Exception submission steps for customers who are not MMD enrolled.

@jaimeo , @VinnieFlynt , @dannoakes , please review this one sentence so customers who haven't yet enrolled in MMD know how to submit an Exception.

### CODE REVIEW

**Comment by yogkumgit** [comment]
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

**Comment by ElaineAnsell** [comment]
Adding @Jaime Ondrusek<mailto:jaimeo@microsoft.com> who should first review before this PR is published.  Thank you!

Regards,
Elaine

**Comment by dannoakes** [comment]
Please do not proceed with this yet as Microsoft account managers do not have access to request these on behalf of customers.

**Comment by jaimeo** [comment]
@ElaineAnsell @dannoakes let's take this internally to resolve.

**Review by JohanFreelancer9 — COMMENTED** [review]
The copy needs to be edited but I am waiting for a resolution on the issues raised before proceeding with the copy editor review.

**Comment by VinnieFlynt** [comment]
I sent Jaime email for some changes. Please hold until those are incorporated. Thx

**Comment by jaimeo** [comment]
@dannoakes what was concluded on this edit?

**Comment by yogkumgit** [comment]
@dannoakes Please reply.

**Comment by dannoakes** [comment]
I beleive this can be closed.

**Pull request closed without merging**
