### PR TITLE
Fix formatting

### PR DESCRIPTION
**Pull request by markaldridge**
Image wasn't being displayed

### CODE REVIEW

**Comment by mypil** [comment]
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by mypil** [comment]
@DulceMontemayor - PR has been copy edited and is ready for final review. 

Thank you.

cc: @kenwith

**Review by DulceMontemayor — APPROVED** [review]

**Comment by mypil** [comment]
@Dansimp - Can you please merge this approved PR?

Thank you.

**Review by DulceMontemayor — CHANGES_REQUESTED** [review]
|Phase 3: Configure & Onboard <br>[Phase 3: Configure & Onboard](config-mtpeval.md) |  Configure each Microsoft Threat Protection pillar for your Microsoft Threat Protection evaluation lab and onboard your endpoints.

**Comment by mypil** [comment]
@markaldridge - please apply the recommended changes to this PR from the author @DulceMontemayor. Thank you.  

> |Phase 3: Configure & Onboard
> [Phase 3: Configure & Onboard](config-mtpeval.md) | Configure each Microsoft Threat Protection pillar for your Microsoft Threat Protection evaluation lab and onboard your endpoints.

**Comment by markaldridge** [comment]
@mypil @DulceMontemayor 
Hopefully I've made the necessary changes 😃

**Comment by mypil** [comment]
@DulceMontemayor - We would like to follow up. Can you please assist to approve and merge this PR? Thank you.

**Review by DulceMontemayor — APPROVED** [review]

**Pull request merged**
