### PR TITLE
Update urls-and-ip-address-ranges.md

### PR DESCRIPTION
**Pull request by msbemba**
Adding protocol information to the related topics -https://docs.microsoft.com/en-us/exchange/mailbox-migration/migrating-imap-mailboxes/setting-up-your-imap-server-connection#to-get-the-name-of-your-source-email-server-by-using-outlook-on-the-web

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/3770

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@JoeDavies-MSFT  Please merge this PR. Thanks

**Comment by JoeDavies-MSFT** [comment]
@yogkumgit @msbemba I am closing this PR. The link you are adding is too specific for the endpoints article.

**Comment by msbemba** [comment]
I have created a New PR #https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3925 with article information to the related topics section.

**Pull request closed without merging**
