### PR TITLE
Update in the path

### PR DESCRIPTION
**Pull request by joinimran**
The registry path has been changed so updated the document accordingly.

Problem: https://github.com/MicrosoftDocs/windows-itpro-docs/issues/8304

### CODE REVIEW

**Comment by joinimran** [comment]
image

**Comment by joinimran** [comment]
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@Dansimp Please merge this PR. Thanks.

**Pull request merged**
