### PR TITLE
Update m365-lighthouse-view-opportunities.md

### LINKED ISSUE #12837: URL needed
where is the URL for "lighthouse" itself? Please include

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f6b0ae25-469d-c298-3899-3bcc24af1b90
* Version Independent ID: f6b0ae25-469d-c298-3899-3bcc24af1b90
* Content: [View opportunities in Sales Advisor in Microsoft 365 Lighthouse - Microsoft 365 Lighthouse](https://learn.microsoft.com/en-us/microsoft-365/lighthouse/m365-lighthouse-view-opportunities?view=o365-worldwide)
* Content Source: [microsoft-365/lighthouse/m365-lighthouse-view-opportunities.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/lighthouse/m365-lighthouse-view-opportunities.md)
* Service: **microsoft-365-lighthouse**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

### PR DESCRIPTION
**Pull request by msbemba**
Added URL's for Lighthouse in the document

Fixes https://github.com/MicrosoftDocs/microsoft-365-docs/issues/12837

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 PLease copy review

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by traya1** [comment]
closing/re-opening PR

**Comment by traya1** [comment]
This seems to be part of a wider outage/issue. Working on escalating this to the necessary team(s).

**Comment by traya1** [comment]
close/re-open PR

**Pull request merged**
