### PR TITLE
Update microsoft-defender-endpoint-mac.md

### PR DESCRIPTION
**Pull request by msbemba**
Updated the licensing requirement from windows 11 to windows 11 Enterprise E5

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/6599

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@Dansimp Please merge this PR. Thanks

**Comment by yogkumgit** [comment]
@Dansimp Gentle reminder.

**Pull request merged**
