### PR TITLE
Update cross-tenant-mailbox-migration.md

### PR DESCRIPTION
**Pull request by msbemba**
Fixed the syntax for Test-MigrationServerAvailability

### CODE REVIEW

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/9680

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@msbemba Please resolve validation check. Thanks

**Comment by msbemba** [comment]
@yogkumgit Validation has been passed

**Comment by yogkumgit** [comment]
@kelleyvice-msft Please merge this PR. Thanks

**Comment by yogkumgit** [comment]
@tiburd Please merge this PR. Thanks

**Comment by tiburd** [comment]
@msbemba 
Hi,

Are you able to update the branch?

I'm unable to update the branch. Thomas (admin) said that this might be because you might have checked a setting that allows others to update your PRs...

Please @ mention me after you update the branch so that I can merge the PR.

Thank you!

**Pull request merged**
